// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package schwab

// Generated from OpenAPI doc version 1.0.0 and generator version 2.799.0

import (
	"context"
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/config"
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/hooks"
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
	"github.com/Chalupa-Tech/go-schwab-api-individual/models/components"
	"github.com/Chalupa-Tech/go-schwab-api-individual/retry"
	"net/http"
	"time"
)

// HTTPClient provides an interface for supplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

// Pointer provides a helper function to return a pointer to a type
func Pointer[T any](v T) *T { return &v }

// SDK - Market Data: Trader API - Market data
type SDK struct {
	SDKVersion     string
	Accounts       *Accounts
	Orders         *Orders
	Transactions   *Transactions
	UserPreference *UserPreference
	// Get Quotes Web Service.
	Quotes *Quotes
	// Get Option Chains Web Service.
	OptionChains *OptionChains
	// Get Option Expiration Chain Web Service.
	OptionExpirationChain *OptionExpirationChain
	// Get Price History Web Service.
	PriceHistory *PriceHistory
	// Get Movers Web Service.
	Movers *Movers
	// Get MarketHours Web Service.
	MarketHours *MarketHours
	// Get Instruments Web Service.
	Instruments *Instruments

	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

type SDKOption func(*SDK)

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *SDK) {
		sdk.sdkConfiguration.Client = client
	}
}

// WithSecurity configures the SDK to use the provided security details
func WithSecurity(oauth string) SDKOption {
	return func(sdk *SDK) {
		security := components.Security{Oauth: oauth}
		sdk.sdkConfiguration.Security = utils.AsSecuritySource(&security)
	}
}

// WithSecuritySource configures the SDK to invoke the Security Source function on each method call to determine authentication
func WithSecuritySource(security func(context.Context) (components.Security, error)) SDKOption {
	return func(sdk *SDK) {
		sdk.sdkConfiguration.Security = func(ctx context.Context) (interface{}, error) {
			return security(ctx)
		}
	}
}

func WithRetryConfig(retryConfig retry.Config) SDKOption {
	return func(sdk *SDK) {
		sdk.sdkConfiguration.RetryConfig = &retryConfig
	}
}

// WithTimeout Optional request timeout applied to each operation
func WithTimeout(timeout time.Duration) SDKOption {
	return func(sdk *SDK) {
		sdk.sdkConfiguration.Timeout = &timeout
	}
}

// New creates a new instance of the SDK with the provided serverURL and options
func New(serverURL string, opts ...SDKOption) *SDK {
	sdk := &SDK{
		SDKVersion: "0.0.4",
		sdkConfiguration: config.SDKConfiguration{
			UserAgent: "speakeasy-sdk/go 0.0.4 2.799.0 1.0.0 github.com/Chalupa-Tech/go-schwab-api-individual",
		},
		hooks: hooks.New(),
	}
	for _, opt := range opts {
		opt(sdk)
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.Client == nil {
		sdk.sdkConfiguration.Client = &http.Client{Timeout: 60 * time.Second}
	}

	sdk.sdkConfiguration.ServerURL = serverURL

	sdk.sdkConfiguration = sdk.hooks.SDKInit(sdk.sdkConfiguration)

	sdk.Accounts = newAccounts(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Orders = newOrders(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Transactions = newTransactions(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.UserPreference = newUserPreference(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Quotes = newQuotes(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.OptionChains = newOptionChains(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.OptionExpirationChain = newOptionExpirationChain(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.PriceHistory = newPriceHistory(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Movers = newMovers(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.MarketHours = newMarketHours(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Instruments = newInstruments(sdk, sdk.sdkConfiguration, sdk.hooks)

	return sdk
}
