// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/models/components"
)

var CancelOrderServerList = []string{
	"https://api.schwabapi.com/trader/v1",
}

type CancelOrderRequest struct {
	// The encrypted ID of the account
	AccountNumber string `pathParam:"style=simple,explode=false,name=accountNumber"`
	// The ID of the order being cancelled
	OrderID int64 `pathParam:"style=simple,explode=false,name=orderId"`
}

func (c *CancelOrderRequest) GetAccountNumber() string {
	if c == nil {
		return ""
	}
	return c.AccountNumber
}

func (c *CancelOrderRequest) GetOrderID() int64 {
	if c == nil {
		return 0
	}
	return c.OrderID
}

type CancelOrderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Headers  map[string][]string
}

func (c *CancelOrderResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CancelOrderResponse) GetHeaders() map[string][]string {
	if c == nil {
		return map[string][]string{}
	}
	return c.Headers
}
