// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"undefined/internal/utils"
	"undefined/models/components"
)

type GetAccountRequest struct {
	// The encrypted ID of the account
	AccountNumber string `pathParam:"style=simple,explode=false,name=accountNumber"`
	// This allows one to determine
	// which fields they want returned. Possible values in this String can be:
	// <br><code>positions</code><br> Example:<br><code>fields=positions</code>
	Fields *string `queryParam:"style=form,explode=true,name=fields"`
}

func (g *GetAccountRequest) GetAccountNumber() string {
	if g == nil {
		return ""
	}
	return g.AccountNumber
}

func (g *GetAccountRequest) GetFields() *string {
	if g == nil {
		return nil
	}
	return g.Fields
}

type GetAccountResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A valid account, matching the provided input parameters
	Account *components.Account
	Headers map[string][]string
}

func (g GetAccountResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAccountResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAccountResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAccountResponse) GetAccount() *components.Account {
	if g == nil {
		return nil
	}
	return g.Account
}

func (g *GetAccountResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
