// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
	"github.com/Chalupa-Tech/go-schwab-api-individual/models/components"
)

type GetAccountNumbersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of valid "accounts", matching the provided input parameters.
	AccountNumberHashes []components.AccountNumberHash
	Headers             map[string][]string
}

func (g GetAccountNumbersResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAccountNumbersResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAccountNumbersResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAccountNumbersResponse) GetAccountNumberHashes() []components.AccountNumberHash {
	if g == nil {
		return nil
	}
	return g.AccountNumberHashes
}

func (g *GetAccountNumbersResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
