// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
	"github.com/Chalupa-Tech/go-schwab-api-individual/models/components"
)

type GetAccountsRequest struct {
	// This allows one to determine which fields they want returned. Possible value in this String can be:
	// <br><code>positions</code><br> Example:<br><code>fields=positions</code>
	Fields *string `queryParam:"style=form,explode=true,name=fields"`
}

func (g *GetAccountsRequest) GetFields() *string {
	if g == nil {
		return nil
	}
	return g.Fields
}

type GetAccountsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of valid "accounts", matching the provided input parameters.
	Accounts []components.Account
	Headers  map[string][]string
}

func (g GetAccountsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAccountsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAccountsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAccountsResponse) GetAccounts() []components.Account {
	if g == nil {
		return nil
	}
	return g.Accounts
}

func (g *GetAccountsResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
