// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"undefined/internal/utils"
	"undefined/models/components"
	"undefined/optionalnullable"
	"undefined/types"
)

type GetChainRequest struct {
	// Enter one symbol
	Symbol string `queryParam:"style=form,explode=true,name=symbol"`
	// Contract Type
	ContractType *components.QueryParamContractType `queryParam:"style=form,explode=true,name=contractType"`
	// The Number of strikes to return above or below the at-the-money price
	StrikeCount *int64 `queryParam:"style=form,explode=true,name=strikeCount"`
	// Underlying quotes to be included
	IncludeUnderlyingQuote *bool `queryParam:"style=form,explode=true,name=includeUnderlyingQuote"`
	// OptionChain strategy. Default is SINGLE. ANALYTICAL allows the use of volatility, underlyingPrice, interestRate, and daysToExpiration params to calculate theoretical values.
	Strategy *components.QueryParamStrategy `queryParam:"style=form,explode=true,name=strategy"`
	// Strike interval for spread strategy chains (see strategy param)
	Interval *float64 `queryParam:"style=form,explode=true,name=interval"`
	// Strike Price
	Strike *float64 `queryParam:"style=form,explode=true,name=strike"`
	// Range(ITM/NTM/OTM etc.)
	Range *string `queryParam:"style=form,explode=true,name=range"`
	// From date(pattern: yyyy-MM-dd)
	FromDate *types.Date `queryParam:"style=form,explode=true,name=fromDate"`
	// To date (pattern: yyyy-MM-dd)
	ToDate *types.Date `queryParam:"style=form,explode=true,name=toDate"`
	// Volatility to use in calculations.  Applies only to ANALYTICAL strategy chains (see strategy param)
	Volatility *float64 `queryParam:"style=form,explode=true,name=volatility"`
	// Underlying price to use in calculations. Applies only to ANALYTICAL strategy chains (see strategy param)
	UnderlyingPrice *float64 `queryParam:"style=form,explode=true,name=underlyingPrice"`
	// Interest rate to use in calculations. Applies only to ANALYTICAL strategy chains (see strategy param)
	InterestRate *float64 `queryParam:"style=form,explode=true,name=interestRate"`
	// Days to expiration to use in calculations. Applies only to ANALYTICAL strategy chains (see strategy param)
	DaysToExpiration *int `queryParam:"style=form,explode=true,name=daysToExpiration"`
	// Expiration month
	ExpMonth *components.QueryParamExpMonth `queryParam:"style=form,explode=true,name=expMonth"`
	// Option Type
	OptionType *string `queryParam:"style=form,explode=true,name=optionType"`
	// Applicable only if its retail token, entitlement of client PP-PayingPro, NP-NonPro and PN-NonPayingPro
	Entitlement optionalnullable.OptionalNullable[components.QueryParamEntitlement] `queryParam:"style=form,explode=true,name=entitlement"`
}

func (g GetChainRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetChainRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetChainRequest) GetSymbol() string {
	if g == nil {
		return ""
	}
	return g.Symbol
}

func (g *GetChainRequest) GetContractType() *components.QueryParamContractType {
	if g == nil {
		return nil
	}
	return g.ContractType
}

func (g *GetChainRequest) GetStrikeCount() *int64 {
	if g == nil {
		return nil
	}
	return g.StrikeCount
}

func (g *GetChainRequest) GetIncludeUnderlyingQuote() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeUnderlyingQuote
}

func (g *GetChainRequest) GetStrategy() *components.QueryParamStrategy {
	if g == nil {
		return nil
	}
	return g.Strategy
}

func (g *GetChainRequest) GetInterval() *float64 {
	if g == nil {
		return nil
	}
	return g.Interval
}

func (g *GetChainRequest) GetStrike() *float64 {
	if g == nil {
		return nil
	}
	return g.Strike
}

func (g *GetChainRequest) GetRange() *string {
	if g == nil {
		return nil
	}
	return g.Range
}

func (g *GetChainRequest) GetFromDate() *types.Date {
	if g == nil {
		return nil
	}
	return g.FromDate
}

func (g *GetChainRequest) GetToDate() *types.Date {
	if g == nil {
		return nil
	}
	return g.ToDate
}

func (g *GetChainRequest) GetVolatility() *float64 {
	if g == nil {
		return nil
	}
	return g.Volatility
}

func (g *GetChainRequest) GetUnderlyingPrice() *float64 {
	if g == nil {
		return nil
	}
	return g.UnderlyingPrice
}

func (g *GetChainRequest) GetInterestRate() *float64 {
	if g == nil {
		return nil
	}
	return g.InterestRate
}

func (g *GetChainRequest) GetDaysToExpiration() *int {
	if g == nil {
		return nil
	}
	return g.DaysToExpiration
}

func (g *GetChainRequest) GetExpMonth() *components.QueryParamExpMonth {
	if g == nil {
		return nil
	}
	return g.ExpMonth
}

func (g *GetChainRequest) GetOptionType() *string {
	if g == nil {
		return nil
	}
	return g.OptionType
}

func (g *GetChainRequest) GetEntitlement() optionalnullable.OptionalNullable[components.QueryParamEntitlement] {
	if g == nil {
		return nil
	}
	return g.Entitlement
}

type GetChainResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The Chain for the symbol was returned successfully.
	OptionChain *components.OptionChain
	Headers     map[string][]string
}

func (g GetChainResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetChainResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetChainResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetChainResponse) GetOptionChain() *components.OptionChain {
	if g == nil {
		return nil
	}
	return g.OptionChain
}

func (g *GetChainResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
