// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
	"github.com/Chalupa-Tech/go-schwab-api-individual/models/components"
)

var GetExpirationChainServerList = []string{
	"https://api.schwabapi.com/marketdata/v1",
	"https://api.schwabapi.com/marketdata/v1",
}

type GetExpirationChainRequest struct {
	// Enter one symbol
	Symbol string `queryParam:"style=form,explode=true,name=symbol"`
}

func (g *GetExpirationChainRequest) GetSymbol() string {
	if g == nil {
		return ""
	}
	return g.Symbol
}

type GetExpirationChainResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The Expiration Chain for the symbol was returned successfully.
	ExpirationChain *components.ExpirationChain
	Headers         map[string][]string
}

func (g GetExpirationChainResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetExpirationChainResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetExpirationChainResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetExpirationChainResponse) GetExpirationChain() *components.ExpirationChain {
	if g == nil {
		return nil
	}
	return g.ExpirationChain
}

func (g *GetExpirationChainResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
