// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"undefined/internal/utils"
	"undefined/models/components"
)

type GetInstrumentsByCusipRequest struct {
	// cusip of a security
	CusipID string `pathParam:"style=simple,explode=false,name=cusip_id"`
}

func (g *GetInstrumentsByCusipRequest) GetCusipID() string {
	if g == nil {
		return ""
	}
	return g.CusipID
}

type GetInstrumentsByCusipResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	InstrumentResponse *components.InstrumentResponse
	Headers            map[string][]string
}

func (g GetInstrumentsByCusipResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetInstrumentsByCusipResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetInstrumentsByCusipResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetInstrumentsByCusipResponse) GetInstrumentResponse() *components.InstrumentResponse {
	if g == nil {
		return nil
	}
	return g.InstrumentResponse
}

func (g *GetInstrumentsByCusipResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
