// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"undefined/internal/utils"
	"undefined/models/components"
)

type GetInstrumentsRequest struct {
	// symbol of a security
	Symbol string `queryParam:"style=form,explode=true,name=symbol"`
	// search by
	Projection components.QueryParamprojection `queryParam:"style=form,explode=true,name=projection"`
}

func (g *GetInstrumentsRequest) GetSymbol() string {
	if g == nil {
		return ""
	}
	return g.Symbol
}

func (g *GetInstrumentsRequest) GetProjection() components.QueryParamprojection {
	if g == nil {
		return components.QueryParamprojection("")
	}
	return g.Projection
}

// GetInstrumentsResponseBody - OK
type GetInstrumentsResponseBody struct {
	Instruments []components.InstrumentResponse `json:"instruments,omitzero"`
}

func (g GetInstrumentsResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetInstrumentsResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetInstrumentsResponseBody) GetInstruments() []components.InstrumentResponse {
	if g == nil {
		return nil
	}
	return g.Instruments
}

type GetInstrumentsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object  *GetInstrumentsResponseBody
	Headers map[string][]string
}

func (g GetInstrumentsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetInstrumentsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetInstrumentsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetInstrumentsResponse) GetObject() *GetInstrumentsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

func (g *GetInstrumentsResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
