// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
	"github.com/Chalupa-Tech/go-schwab-api-individual/models/components"
	"github.com/Chalupa-Tech/go-schwab-api-individual/types"
)

var GetMarketHoursServerList = []string{
	"https://api.schwabapi.com/marketdata/v1",
	"https://api.schwabapi.com/marketdata/v1",
}

type GetMarketHoursRequest struct {
	// List of markets
	Markets []components.QueryParamMarkets `queryParam:"style=form,explode=true,name=markets"`
	// Valid date range is from currentdate to 1 year from today. It will default to current day if not entered. Date format:YYYY-MM-DD
	Date *types.Date `queryParam:"style=form,explode=true,name=date"`
}

func (g GetMarketHoursRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMarketHoursRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMarketHoursRequest) GetMarkets() []components.QueryParamMarkets {
	if g == nil {
		return []components.QueryParamMarkets{}
	}
	return g.Markets
}

func (g *GetMarketHoursRequest) GetDate() *types.Date {
	if g == nil {
		return nil
	}
	return g.Date
}

type GetMarketHoursResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object  map[string]map[string]components.Hours
	Headers map[string][]string
}

func (g GetMarketHoursResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMarketHoursResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMarketHoursResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetMarketHoursResponse) GetObject() map[string]map[string]components.Hours {
	if g == nil {
		return nil
	}
	return g.Object
}

func (g *GetMarketHoursResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
