// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
	"github.com/Chalupa-Tech/go-schwab-api-individual/models/components"
	"github.com/Chalupa-Tech/go-schwab-api-individual/types"
)

var GetMarketHourServerList = []string{
	"https://api.schwabapi.com/marketdata/v1",
	"https://api.schwabapi.com/marketdata/v1",
}

type GetMarketHourRequest struct {
	// market id
	MarketID components.PathParamMarket `pathParam:"style=simple,explode=false,name=market_id"`
	// Valid date range is from currentdate to 1 year from today. It will default to current day if not entered. Date format:YYYY-MM-DD
	Date *types.Date `queryParam:"style=form,explode=true,name=date"`
}

func (g GetMarketHourRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMarketHourRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMarketHourRequest) GetMarketID() components.PathParamMarket {
	if g == nil {
		return components.PathParamMarket("")
	}
	return g.MarketID
}

func (g *GetMarketHourRequest) GetDate() *types.Date {
	if g == nil {
		return nil
	}
	return g.Date
}

type GetMarketHourResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object  map[string]map[string]components.Hours
	Headers map[string][]string
}

func (g GetMarketHourResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMarketHourResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMarketHourResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetMarketHourResponse) GetObject() map[string]map[string]components.Hours {
	if g == nil {
		return nil
	}
	return g.Object
}

func (g *GetMarketHourResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
