// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"undefined/internal/utils"
	"undefined/models/components"
)

type GetMoversRequest struct {
	// Index Symbol
	SymbolID components.PathParamSymbol `pathParam:"style=simple,explode=false,name=symbol_id"`
	// Sort by a particular attribute
	Sort *components.QueryParamSort `queryParam:"style=form,explode=true,name=sort"`
	// To return movers with the specified directions of up or down
	Frequency *components.QueryParamFrequency `default:"0" queryParam:"style=form,explode=true,name=frequency"`
}

func (g GetMoversRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMoversRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMoversRequest) GetSymbolID() components.PathParamSymbol {
	if g == nil {
		return components.PathParamSymbol("")
	}
	return g.SymbolID
}

func (g *GetMoversRequest) GetSort() *components.QueryParamSort {
	if g == nil {
		return nil
	}
	return g.Sort
}

func (g *GetMoversRequest) GetFrequency() *components.QueryParamFrequency {
	if g == nil {
		return nil
	}
	return g.Frequency
}

// GetMoversResponseBody - Analytics for the symbol was returned successfully.
type GetMoversResponseBody struct {
	Screeners []components.Screener `json:"screeners,omitzero"`
}

func (g GetMoversResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMoversResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMoversResponseBody) GetScreeners() []components.Screener {
	if g == nil {
		return nil
	}
	return g.Screeners
}

type GetMoversResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Analytics for the symbol was returned successfully.
	Object  *GetMoversResponseBody
	Headers map[string][]string
}

func (g GetMoversResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMoversResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMoversResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetMoversResponse) GetObject() *GetMoversResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

func (g *GetMoversResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
