// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
	"github.com/Chalupa-Tech/go-schwab-api-individual/models/components"
)

var GetOrdersByQueryParamServerList = []string{
	"https://api.schwabapi.com/trader/v1",
}

type GetOrdersByQueryParamRequest struct {
	// The max number of orders to retrieve. Default is 3000.
	MaxResults *int64 `queryParam:"style=form,explode=true,name=maxResults"`
	// Specifies that no orders entered before this time should be returned. Valid ISO-8601 formats are-
	// yyyy-MM-dd'T'HH:mm:ss.SSSZ Date must be within 60 days from today's date.
	// 'toEnteredTime' must also be set.
	FromEnteredTime string `queryParam:"style=form,explode=true,name=fromEnteredTime"`
	// Specifies that no orders entered after this time should be returned.Valid ISO-8601 formats are -
	// yyyy-MM-dd'T'HH:mm:ss.SSSZ. 'fromEnteredTime' must also be set.
	ToEnteredTime string `queryParam:"style=form,explode=true,name=toEnteredTime"`
	// Specifies that only orders of this status should be returned.
	Status *components.APIOrderStatus `queryParam:"style=form,explode=true,name=status"`
}

func (g *GetOrdersByQueryParamRequest) GetMaxResults() *int64 {
	if g == nil {
		return nil
	}
	return g.MaxResults
}

func (g *GetOrdersByQueryParamRequest) GetFromEnteredTime() string {
	if g == nil {
		return ""
	}
	return g.FromEnteredTime
}

func (g *GetOrdersByQueryParamRequest) GetToEnteredTime() string {
	if g == nil {
		return ""
	}
	return g.ToEnteredTime
}

func (g *GetOrdersByQueryParamRequest) GetStatus() *components.APIOrderStatus {
	if g == nil {
		return nil
	}
	return g.Status
}

type GetOrdersByQueryParamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A List of orders for the specified account or if its not mentioned,
	// for all the linked accounts, matching the provided input parameters.
	Orders  []components.Order
	Headers map[string][]string
}

func (g GetOrdersByQueryParamResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetOrdersByQueryParamResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetOrdersByQueryParamResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetOrdersByQueryParamResponse) GetOrders() []components.Order {
	if g == nil {
		return nil
	}
	return g.Orders
}

func (g *GetOrdersByQueryParamResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
