// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"undefined/internal/utils"
	"undefined/models/components"
)

type GetOrdersByPathParamRequest struct {
	// The encrypted ID of the account
	AccountNumber string `pathParam:"style=simple,explode=false,name=accountNumber"`
	// The max number of orders to retrieve. Default is 3000.
	MaxResults *int64 `queryParam:"style=form,explode=true,name=maxResults"`
	// Specifies that no orders entered before this time should be returned.
	// Valid ISO-8601 formats are :<br> <code>yyyy-MM-dd'T'HH:mm:ss.SSSZ</code>  Example fromEnteredTime is '2024-03-29T00:00:00.000Z'.
	// 'toEnteredTime' must also be set.
	FromEnteredTime string `queryParam:"style=form,explode=true,name=fromEnteredTime"`
	// Specifies that no orders entered after this time should be returned.Valid
	// ISO-8601 formats are :<br> <code>yyyy-MM-dd'T'HH:mm:ss.SSSZ</code>.  Example toEnteredTime is '2024-04-28T23:59:59.000Z'.
	// 'fromEnteredTime' must also be set.
	ToEnteredTime string `queryParam:"style=form,explode=true,name=toEnteredTime"`
	// Specifies that only orders of this status should be returned.
	Status *components.APIOrderStatus `queryParam:"style=form,explode=true,name=status"`
}

func (g *GetOrdersByPathParamRequest) GetAccountNumber() string {
	if g == nil {
		return ""
	}
	return g.AccountNumber
}

func (g *GetOrdersByPathParamRequest) GetMaxResults() *int64 {
	if g == nil {
		return nil
	}
	return g.MaxResults
}

func (g *GetOrdersByPathParamRequest) GetFromEnteredTime() string {
	if g == nil {
		return ""
	}
	return g.FromEnteredTime
}

func (g *GetOrdersByPathParamRequest) GetToEnteredTime() string {
	if g == nil {
		return ""
	}
	return g.ToEnteredTime
}

func (g *GetOrdersByPathParamRequest) GetStatus() *components.APIOrderStatus {
	if g == nil {
		return nil
	}
	return g.Status
}

type GetOrdersByPathParamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A List of orders for the account, matching the provided input parameters
	Orders  []components.Order
	Headers map[string][]string
}

func (g GetOrdersByPathParamResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetOrdersByPathParamResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetOrdersByPathParamResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetOrdersByPathParamResponse) GetOrders() []components.Order {
	if g == nil {
		return nil
	}
	return g.Orders
}

func (g *GetOrdersByPathParamResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
