// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
	"github.com/Chalupa-Tech/go-schwab-api-individual/models/components"
)

type GetPriceHistoryRequest struct {
	// The Equity symbol used to look up price history
	Symbol string `queryParam:"style=form,explode=true,name=symbol"`
	// The chart period being requested.
	PeriodType *components.QueryParamperiodtype `queryParam:"style=form,explode=true,name=periodType"`
	// The number of chart period types.<br><br> If the periodType is <br> &#8226; <b>day</b> - valid values are 1, 2, 3, 4, 5, 10<br> &#8226; <b>month</b> - valid values are 1, 2, 3, 6<br> &#8226; <b>year</b> - valid values are 1, 2, 3, 5, 10, 15, 20<br> &#8226; <b>ytd</b> - valid values are 1<br><br> If   the period is not specified and the periodType is<br> &#8226; <b>day</b> - default period is 10.<br> &#8226; <b>month</b> - default period is 1.<br> &#8226; <b>year</b> - default period is 1.<br> &#8226; <b>ytd</b> - default period is 1.<br>
	Period *int `queryParam:"style=form,explode=true,name=period"`
	// The time frequencyType<br><br> If the periodType is <br> &#8226; <b>day</b> - valid value is minute<br> &#8226; <b>month</b> - valid values are daily, weekly<br> &#8226; <b>year</b> - valid values are daily, weekly, monthly<br> &#8226; <b>ytd</b> - valid values are daily, weekly<br><br> If frequencyType  is not specified, default value depends on the periodType<br> &#8226; <b>day</b> - defaulted to minute.<br> &#8226; <b>month</b> - defaulted to weekly.<br> &#8226; <b>year</b> - defaulted to monthly.<br> &#8226; <b>ytd</b> - defaulted to weekly.<br>
	FrequencyType *components.QueryParamfrequencytype `queryParam:"style=form,explode=true,name=frequencyType"`
	// The time frequency duration<br><br> If the frequencyType is <br> &#8226; <b>minute</b> - valid values are 1, 5, 10, 15, 30<br> &#8226; <b>daily</b> - valid value is 1<br> &#8226; <b>weekly</b> - valid value is 1<br> &#8226; <b>monthly</b> - valid value is 1<br><br> If frequency  is not specified, default value is <b>1</b><br>
	Frequency *int `queryParam:"style=form,explode=true,name=frequency"`
	// The start date, Time   in milliseconds since the UNIX epoch eg 1451624400000<br>If not   specified startDate will be (endDate - period) excluding weekends and holidays.
	StartDate *int64 `queryParam:"style=form,explode=true,name=startDate"`
	// The end date, Time   in milliseconds since the UNIX epoch eg 1451624400000<br> If not   specified, the endDate will default to the market close of previous business day.
	EndDate *int64 `queryParam:"style=form,explode=true,name=endDate"`
	// Need extended hours data
	NeedExtendedHoursData *bool `queryParam:"style=form,explode=true,name=needExtendedHoursData"`
	// Need previous close price/date
	NeedPreviousClose *bool `queryParam:"style=form,explode=true,name=needPreviousClose"`
}

func (g *GetPriceHistoryRequest) GetSymbol() string {
	if g == nil {
		return ""
	}
	return g.Symbol
}

func (g *GetPriceHistoryRequest) GetPeriodType() *components.QueryParamperiodtype {
	if g == nil {
		return nil
	}
	return g.PeriodType
}

func (g *GetPriceHistoryRequest) GetPeriod() *int {
	if g == nil {
		return nil
	}
	return g.Period
}

func (g *GetPriceHistoryRequest) GetFrequencyType() *components.QueryParamfrequencytype {
	if g == nil {
		return nil
	}
	return g.FrequencyType
}

func (g *GetPriceHistoryRequest) GetFrequency() *int {
	if g == nil {
		return nil
	}
	return g.Frequency
}

func (g *GetPriceHistoryRequest) GetStartDate() *int64 {
	if g == nil {
		return nil
	}
	return g.StartDate
}

func (g *GetPriceHistoryRequest) GetEndDate() *int64 {
	if g == nil {
		return nil
	}
	return g.EndDate
}

func (g *GetPriceHistoryRequest) GetNeedExtendedHoursData() *bool {
	if g == nil {
		return nil
	}
	return g.NeedExtendedHoursData
}

func (g *GetPriceHistoryRequest) GetNeedPreviousClose() *bool {
	if g == nil {
		return nil
	}
	return g.NeedPreviousClose
}

type GetPriceHistoryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Get all candles for given date range
	CandleList *components.CandleList
	Headers    map[string][]string
}

func (g GetPriceHistoryResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPriceHistoryResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetPriceHistoryResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPriceHistoryResponse) GetCandleList() *components.CandleList {
	if g == nil {
		return nil
	}
	return g.CandleList
}

func (g *GetPriceHistoryResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
