// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"undefined/internal/utils"
	"undefined/models/components"
)

type GetQuoteRequest struct {
	// Symbol of instrument
	SymbolID string `pathParam:"style=simple,explode=false,name=symbol_id"`
	// Request for subset of data by passing coma separated list of root nodes, possible root nodes are quote, fundamental, extended, reference, regular. Sending `quote, fundamental` in request will return quote and fundamental data in response. Dont send this attribute for full response.
	Fields *string `default:"all" queryParam:"style=form,explode=true,name=fields"`
}

func (g GetQuoteRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetQuoteRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetQuoteRequest) GetSymbolID() string {
	if g == nil {
		return ""
	}
	return g.SymbolID
}

func (g *GetQuoteRequest) GetFields() *string {
	if g == nil {
		return nil
	}
	return g.Fields
}

type GetQuoteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Quote Response
	QuoteResponse map[string]components.QuoteResponseObject
	Headers       map[string][]string
}

func (g GetQuoteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetQuoteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetQuoteResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetQuoteResponse) GetQuoteResponse() map[string]components.QuoteResponseObject {
	if g == nil {
		return nil
	}
	return g.QuoteResponse
}

func (g *GetQuoteResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
