// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
	"github.com/Chalupa-Tech/go-schwab-api-individual/models/components"
)

var GetQuotesServerList = []string{
	"https://api.schwabapi.com/marketdata/v1",
	"https://api.schwabapi.com/marketdata/v1",
}

type GetQuotesRequest struct {
	// Comma separated list of symbol(s) to look up a quote
	Symbols *string `queryParam:"style=form,explode=true,name=symbols"`
	// Request for subset of data by passing coma separated list of root nodes, possible root nodes are quote, fundamental, extended, reference, regular. Sending `quote, fundamental` in request will return quote and fundamental data in response. Dont send this attribute for full response.
	Fields *string `default:"all" queryParam:"style=form,explode=true,name=fields"`
	// Include indicative symbol quotes for all ETF symbols in request. If ETF symbol ABC is in request and indicative=true API will return quotes for ABC and its corresponding indicative quote for $ABC.IV
	Indicative *bool `queryParam:"style=form,explode=true,name=indicative"`
}

func (g GetQuotesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetQuotesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetQuotesRequest) GetSymbols() *string {
	if g == nil {
		return nil
	}
	return g.Symbols
}

func (g *GetQuotesRequest) GetFields() *string {
	if g == nil {
		return nil
	}
	return g.Fields
}

func (g *GetQuotesRequest) GetIndicative() *bool {
	if g == nil {
		return nil
	}
	return g.Indicative
}

type GetQuotesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Quote Response
	QuoteResponse map[string]components.QuoteResponseObject
	Headers       map[string][]string
}

func (g GetQuotesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetQuotesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetQuotesResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetQuotesResponse) GetQuoteResponse() map[string]components.QuoteResponseObject {
	if g == nil {
		return nil
	}
	return g.QuoteResponse
}

func (g *GetQuotesResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
