// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
	"github.com/Chalupa-Tech/go-schwab-api-individual/models/components"
)

type GetTransactionsByPathParamRequest struct {
	// The encrypted ID of the account
	AccountNumber string `pathParam:"style=simple,explode=false,name=accountNumber"`
	// Specifies that no transactions entered before this time should be returned.
	// Valid ISO-8601 formats are :<br> <code>yyyy-MM-dd'T'HH:mm:ss.SSSZ</code> .  Example start date is '2024-03-28T21:10:42.000Z'. The 'endDate' must also be set.
	StartDate string `queryParam:"style=form,explode=true,name=startDate"`
	// Specifies that no transactions entered after this time should be returned.Valid
	// ISO-8601 formats are :<br> <code>yyyy-MM-dd'T'HH:mm:ss.SSSZ</code>. Example start date is '2024-05-10T21:10:42.000Z'.
	// The 'startDate' must also be set.
	EndDate string `queryParam:"style=form,explode=true,name=endDate"`
	// It filters all the transaction activities based on the symbol specified. <u>NOTE:</u> If there is any special character in the symbol, please send th encoded value.
	Symbol *string `queryParam:"style=form,explode=true,name=symbol"`
	// Specifies that only transactions of this status should be returned.
	Types components.TransactionType `queryParam:"style=form,explode=true,name=types"`
}

func (g *GetTransactionsByPathParamRequest) GetAccountNumber() string {
	if g == nil {
		return ""
	}
	return g.AccountNumber
}

func (g *GetTransactionsByPathParamRequest) GetStartDate() string {
	if g == nil {
		return ""
	}
	return g.StartDate
}

func (g *GetTransactionsByPathParamRequest) GetEndDate() string {
	if g == nil {
		return ""
	}
	return g.EndDate
}

func (g *GetTransactionsByPathParamRequest) GetSymbol() *string {
	if g == nil {
		return nil
	}
	return g.Symbol
}

func (g *GetTransactionsByPathParamRequest) GetTypes() components.TransactionType {
	if g == nil {
		return components.TransactionType("")
	}
	return g.Types
}

type GetTransactionsByPathParamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A List of orders for the account, matching the provided input
	// parameters
	Transactions []components.Transaction
	Headers      map[string][]string
}

func (g GetTransactionsByPathParamResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTransactionsByPathParamResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetTransactionsByPathParamResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetTransactionsByPathParamResponse) GetTransactions() []components.Transaction {
	if g == nil {
		return nil
	}
	return g.Transactions
}

func (g *GetTransactionsByPathParamResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
