// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
	"github.com/Chalupa-Tech/go-schwab-api-individual/models/components"
)

var GetTransactionsByIDServerList = []string{
	"https://api.schwabapi.com/trader/v1",
}

type GetTransactionsByIDRequest struct {
	// The encrypted ID of the account
	AccountNumber string `pathParam:"style=simple,explode=false,name=accountNumber"`
	// The ID of the transaction being retrieved.
	TransactionID int64 `pathParam:"style=simple,explode=false,name=transactionId"`
}

func (g *GetTransactionsByIDRequest) GetAccountNumber() string {
	if g == nil {
		return ""
	}
	return g.AccountNumber
}

func (g *GetTransactionsByIDRequest) GetTransactionID() int64 {
	if g == nil {
		return 0
	}
	return g.TransactionID
}

type GetTransactionsByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A List of orders for the account, matching the provided input parameters
	Transactions []components.Transaction
	Headers      map[string][]string
}

func (g GetTransactionsByIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTransactionsByIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetTransactionsByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetTransactionsByIDResponse) GetTransactions() []components.Transaction {
	if g == nil {
		return nil
	}
	return g.Transactions
}

func (g *GetTransactionsByIDResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
