// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"undefined/internal/utils"
	"undefined/models/components"
)

type GetUserPreferenceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of user preference values.
	UserPreferences []components.UserPreference
	Headers         map[string][]string
}

func (g GetUserPreferenceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetUserPreferenceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetUserPreferenceResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetUserPreferenceResponse) GetUserPreferences() []components.UserPreference {
	if g == nil {
		return nil
	}
	return g.UserPreferences
}

func (g *GetUserPreferenceResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
