// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/models/components"
)

var PlaceOrderServerList = []string{
	"https://api.schwabapi.com/trader/v1",
}

type PlaceOrderRequest struct {
	// The encrypted ID of the account
	AccountNumber string `pathParam:"style=simple,explode=false,name=accountNumber"`
	// The new Order Object.
	Body components.OrderRequest `request:"mediaType=application/json"`
}

func (p *PlaceOrderRequest) GetAccountNumber() string {
	if p == nil {
		return ""
	}
	return p.AccountNumber
}

func (p *PlaceOrderRequest) GetBody() components.OrderRequest {
	if p == nil {
		return components.OrderRequest{}
	}
	return p.Body
}

type PlaceOrderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Headers  map[string][]string
}

func (p *PlaceOrderResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PlaceOrderResponse) GetHeaders() map[string][]string {
	if p == nil {
		return map[string][]string{}
	}
	return p.Headers
}
