// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"undefined/internal/utils"
	"undefined/models/components"
)

type PreviewOrderRequest struct {
	// The encrypted ID of the account
	AccountNumber string `pathParam:"style=simple,explode=false,name=accountNumber"`
	// The Order Object.
	Body components.PreviewOrder `request:"mediaType=application/json"`
}

func (p *PreviewOrderRequest) GetAccountNumber() string {
	if p == nil {
		return ""
	}
	return p.AccountNumber
}

func (p *PreviewOrderRequest) GetBody() components.PreviewOrder {
	if p == nil {
		return components.PreviewOrder{}
	}
	return p.Body
}

type PreviewOrderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// An order object, matching the input parameters
	PreviewOrder *components.PreviewOrder
	Headers      map[string][]string
}

func (p PreviewOrderResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PreviewOrderResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PreviewOrderResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PreviewOrderResponse) GetPreviewOrder() *components.PreviewOrder {
	if p == nil {
		return nil
	}
	return p.PreviewOrder
}

func (p *PreviewOrderResponse) GetHeaders() map[string][]string {
	if p == nil {
		return map[string][]string{}
	}
	return p.Headers
}
