// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type AccountEquityAssetType string

const (
	AccountEquityAssetTypeEquity               AccountEquityAssetType = "EQUITY"
	AccountEquityAssetTypeOption               AccountEquityAssetType = "OPTION"
	AccountEquityAssetTypeIndex                AccountEquityAssetType = "INDEX"
	AccountEquityAssetTypeMutualFund           AccountEquityAssetType = "MUTUAL_FUND"
	AccountEquityAssetTypeCashEquivalent       AccountEquityAssetType = "CASH_EQUIVALENT"
	AccountEquityAssetTypeFixedIncome          AccountEquityAssetType = "FIXED_INCOME"
	AccountEquityAssetTypeCurrency             AccountEquityAssetType = "CURRENCY"
	AccountEquityAssetTypeCollectiveInvestment AccountEquityAssetType = "COLLECTIVE_INVESTMENT"
)

func (e AccountEquityAssetType) ToPointer() *AccountEquityAssetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AccountEquityAssetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EQUITY", "OPTION", "INDEX", "MUTUAL_FUND", "CASH_EQUIVALENT", "FIXED_INCOME", "CURRENCY", "COLLECTIVE_INVESTMENT":
			return true
		}
	}
	return false
}

type AccountEquity struct {
	AssetType    AccountEquityAssetType `json:"assetType"`
	Cusip        *string                `json:"cusip,omitzero"`
	Symbol       *string                `json:"symbol,omitzero"`
	Description  *string                `json:"description,omitzero"`
	InstrumentID *int64                 `json:"instrumentId,omitzero"`
	NetChange    *float64               `json:"netChange,omitzero"`
	Type         *string                `default:"AccountEquity" json:"_type"`
}

func (a AccountEquity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountEquity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountEquity) GetAssetType() AccountEquityAssetType {
	if a == nil {
		return AccountEquityAssetType("")
	}
	return a.AssetType
}

func (a *AccountEquity) GetCusip() *string {
	if a == nil {
		return nil
	}
	return a.Cusip
}

func (a *AccountEquity) GetSymbol() *string {
	if a == nil {
		return nil
	}
	return a.Symbol
}

func (a *AccountEquity) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AccountEquity) GetInstrumentID() *int64 {
	if a == nil {
		return nil
	}
	return a.InstrumentID
}

func (a *AccountEquity) GetNetChange() *float64 {
	if a == nil {
		return nil
	}
	return a.NetChange
}

func (a *AccountEquity) GetType() *string {
	if a == nil {
		return nil
	}
	return a.Type
}
