// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

type AccountCashEquivalentAssetType string

const (
	AccountCashEquivalentAssetTypeEquity               AccountCashEquivalentAssetType = "EQUITY"
	AccountCashEquivalentAssetTypeOption               AccountCashEquivalentAssetType = "OPTION"
	AccountCashEquivalentAssetTypeIndex                AccountCashEquivalentAssetType = "INDEX"
	AccountCashEquivalentAssetTypeMutualFund           AccountCashEquivalentAssetType = "MUTUAL_FUND"
	AccountCashEquivalentAssetTypeCashEquivalent       AccountCashEquivalentAssetType = "CASH_EQUIVALENT"
	AccountCashEquivalentAssetTypeFixedIncome          AccountCashEquivalentAssetType = "FIXED_INCOME"
	AccountCashEquivalentAssetTypeCurrency             AccountCashEquivalentAssetType = "CURRENCY"
	AccountCashEquivalentAssetTypeCollectiveInvestment AccountCashEquivalentAssetType = "COLLECTIVE_INVESTMENT"
)

func (e AccountCashEquivalentAssetType) ToPointer() *AccountCashEquivalentAssetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AccountCashEquivalentAssetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EQUITY", "OPTION", "INDEX", "MUTUAL_FUND", "CASH_EQUIVALENT", "FIXED_INCOME", "CURRENCY", "COLLECTIVE_INVESTMENT":
			return true
		}
	}
	return false
}

type AccountCashEquivalentType string

const (
	AccountCashEquivalentTypeSweepVehicle    AccountCashEquivalentType = "SWEEP_VEHICLE"
	AccountCashEquivalentTypeSavings         AccountCashEquivalentType = "SAVINGS"
	AccountCashEquivalentTypeMoneyMarketFund AccountCashEquivalentType = "MONEY_MARKET_FUND"
	AccountCashEquivalentTypeUnknown         AccountCashEquivalentType = "UNKNOWN"
)

func (e AccountCashEquivalentType) ToPointer() *AccountCashEquivalentType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AccountCashEquivalentType) IsExact() bool {
	if e != nil {
		switch *e {
		case "SWEEP_VEHICLE", "SAVINGS", "MONEY_MARKET_FUND", "UNKNOWN":
			return true
		}
	}
	return false
}

type AccountCashEquivalent struct {
	AssetType    AccountCashEquivalentAssetType `json:"assetType"`
	Cusip        *string                        `json:"cusip,omitzero"`
	Symbol       *string                        `json:"symbol,omitzero"`
	Description  *string                        `json:"description,omitzero"`
	InstrumentID *int64                         `json:"instrumentId,omitzero"`
	NetChange    *float64                       `json:"netChange,omitzero"`
	Type         *AccountCashEquivalentType     `json:"type,omitzero"`
}

func (a AccountCashEquivalent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountCashEquivalent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountCashEquivalent) GetAssetType() AccountCashEquivalentAssetType {
	if a == nil {
		return AccountCashEquivalentAssetType("")
	}
	return a.AssetType
}

func (a *AccountCashEquivalent) GetCusip() *string {
	if a == nil {
		return nil
	}
	return a.Cusip
}

func (a *AccountCashEquivalent) GetSymbol() *string {
	if a == nil {
		return nil
	}
	return a.Symbol
}

func (a *AccountCashEquivalent) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AccountCashEquivalent) GetInstrumentID() *int64 {
	if a == nil {
		return nil
	}
	return a.InstrumentID
}

func (a *AccountCashEquivalent) GetNetChange() *float64 {
	if a == nil {
		return nil
	}
	return a.NetChange
}

func (a *AccountCashEquivalent) GetType() *AccountCashEquivalentType {
	if a == nil {
		return nil
	}
	return a.Type
}
