// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Account struct {
	SecuritiesAccount *SecuritiesAccount `json:"securitiesAccount,omitzero"`
}

func (a *Account) GetSecuritiesAccount() *SecuritiesAccount {
	if a == nil {
		return nil
	}
	return a.SecuritiesAccount
}

func (a *Account) GetSecuritiesAccountMargin() *MarginAccount {
	if v := a.GetSecuritiesAccount(); v != nil {
		return v.MarginAccount
	}
	return nil
}

func (a *Account) GetSecuritiesAccountCash() *CashAccount {
	if v := a.GetSecuritiesAccount(); v != nil {
		return v.CashAccount
	}
	return nil
}
