// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

type AccountOptionAssetType string

const (
	AccountOptionAssetTypeEquity               AccountOptionAssetType = "EQUITY"
	AccountOptionAssetTypeOption               AccountOptionAssetType = "OPTION"
	AccountOptionAssetTypeIndex                AccountOptionAssetType = "INDEX"
	AccountOptionAssetTypeMutualFund           AccountOptionAssetType = "MUTUAL_FUND"
	AccountOptionAssetTypeCashEquivalent       AccountOptionAssetType = "CASH_EQUIVALENT"
	AccountOptionAssetTypeFixedIncome          AccountOptionAssetType = "FIXED_INCOME"
	AccountOptionAssetTypeCurrency             AccountOptionAssetType = "CURRENCY"
	AccountOptionAssetTypeCollectiveInvestment AccountOptionAssetType = "COLLECTIVE_INVESTMENT"
)

func (e AccountOptionAssetType) ToPointer() *AccountOptionAssetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AccountOptionAssetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EQUITY", "OPTION", "INDEX", "MUTUAL_FUND", "CASH_EQUIVALENT", "FIXED_INCOME", "CURRENCY", "COLLECTIVE_INVESTMENT":
			return true
		}
	}
	return false
}

type AccountOptionPutCall string

const (
	AccountOptionPutCallPut     AccountOptionPutCall = "PUT"
	AccountOptionPutCallCall    AccountOptionPutCall = "CALL"
	AccountOptionPutCallUnknown AccountOptionPutCall = "UNKNOWN"
)

func (e AccountOptionPutCall) ToPointer() *AccountOptionPutCall {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AccountOptionPutCall) IsExact() bool {
	if e != nil {
		switch *e {
		case "PUT", "CALL", "UNKNOWN":
			return true
		}
	}
	return false
}

type AccountOptionType string

const (
	AccountOptionTypeVanilla AccountOptionType = "VANILLA"
	AccountOptionTypeBinary  AccountOptionType = "BINARY"
	AccountOptionTypeBarrier AccountOptionType = "BARRIER"
	AccountOptionTypeUnknown AccountOptionType = "UNKNOWN"
)

func (e AccountOptionType) ToPointer() *AccountOptionType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AccountOptionType) IsExact() bool {
	if e != nil {
		switch *e {
		case "VANILLA", "BINARY", "BARRIER", "UNKNOWN":
			return true
		}
	}
	return false
}

type AccountOption struct {
	AssetType          AccountOptionAssetType        `json:"assetType"`
	Cusip              *string                       `json:"cusip,omitzero"`
	Symbol             *string                       `json:"symbol,omitzero"`
	Description        *string                       `json:"description,omitzero"`
	InstrumentID       *int64                        `json:"instrumentId,omitzero"`
	NetChange          *float64                      `json:"netChange,omitzero"`
	OptionDeliverables []AccountAPIOptionDeliverable `json:"optionDeliverables,omitzero"`
	PutCall            *AccountOptionPutCall         `json:"putCall,omitzero"`
	OptionMultiplier   *int                          `json:"optionMultiplier,omitzero"`
	Type               *AccountOptionType            `json:"type,omitzero"`
	UnderlyingSymbol   *string                       `json:"underlyingSymbol,omitzero"`
}

func (a AccountOption) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountOption) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountOption) GetAssetType() AccountOptionAssetType {
	if a == nil {
		return AccountOptionAssetType("")
	}
	return a.AssetType
}

func (a *AccountOption) GetCusip() *string {
	if a == nil {
		return nil
	}
	return a.Cusip
}

func (a *AccountOption) GetSymbol() *string {
	if a == nil {
		return nil
	}
	return a.Symbol
}

func (a *AccountOption) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AccountOption) GetInstrumentID() *int64 {
	if a == nil {
		return nil
	}
	return a.InstrumentID
}

func (a *AccountOption) GetNetChange() *float64 {
	if a == nil {
		return nil
	}
	return a.NetChange
}

func (a *AccountOption) GetOptionDeliverables() []AccountAPIOptionDeliverable {
	if a == nil {
		return nil
	}
	return a.OptionDeliverables
}

func (a *AccountOption) GetPutCall() *AccountOptionPutCall {
	if a == nil {
		return nil
	}
	return a.PutCall
}

func (a *AccountOption) GetOptionMultiplier() *int {
	if a == nil {
		return nil
	}
	return a.OptionMultiplier
}

func (a *AccountOption) GetType() *AccountOptionType {
	if a == nil {
		return nil
	}
	return a.Type
}

func (a *AccountOption) GetUnderlyingSymbol() *string {
	if a == nil {
		return nil
	}
	return a.UnderlyingSymbol
}
