// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"time"
	"undefined/internal/utils"
)

type AccountFixedIncomeAssetType string

const (
	AccountFixedIncomeAssetTypeEquity               AccountFixedIncomeAssetType = "EQUITY"
	AccountFixedIncomeAssetTypeOption               AccountFixedIncomeAssetType = "OPTION"
	AccountFixedIncomeAssetTypeIndex                AccountFixedIncomeAssetType = "INDEX"
	AccountFixedIncomeAssetTypeMutualFund           AccountFixedIncomeAssetType = "MUTUAL_FUND"
	AccountFixedIncomeAssetTypeCashEquivalent       AccountFixedIncomeAssetType = "CASH_EQUIVALENT"
	AccountFixedIncomeAssetTypeFixedIncome          AccountFixedIncomeAssetType = "FIXED_INCOME"
	AccountFixedIncomeAssetTypeCurrency             AccountFixedIncomeAssetType = "CURRENCY"
	AccountFixedIncomeAssetTypeCollectiveInvestment AccountFixedIncomeAssetType = "COLLECTIVE_INVESTMENT"
)

func (e AccountFixedIncomeAssetType) ToPointer() *AccountFixedIncomeAssetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AccountFixedIncomeAssetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EQUITY", "OPTION", "INDEX", "MUTUAL_FUND", "CASH_EQUIVALENT", "FIXED_INCOME", "CURRENCY", "COLLECTIVE_INVESTMENT":
			return true
		}
	}
	return false
}

type AccountFixedIncome struct {
	AssetType    AccountFixedIncomeAssetType `json:"assetType"`
	Cusip        *string                     `json:"cusip,omitzero"`
	Symbol       *string                     `json:"symbol,omitzero"`
	Description  *string                     `json:"description,omitzero"`
	InstrumentID *int64                      `json:"instrumentId,omitzero"`
	NetChange    *float64                    `json:"netChange,omitzero"`
	MaturityDate *time.Time                  `json:"maturityDate,omitzero"`
	Factor       *float64                    `json:"factor,omitzero"`
	VariableRate *float64                    `json:"variableRate,omitzero"`
}

func (a AccountFixedIncome) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountFixedIncome) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountFixedIncome) GetAssetType() AccountFixedIncomeAssetType {
	if a == nil {
		return AccountFixedIncomeAssetType("")
	}
	return a.AssetType
}

func (a *AccountFixedIncome) GetCusip() *string {
	if a == nil {
		return nil
	}
	return a.Cusip
}

func (a *AccountFixedIncome) GetSymbol() *string {
	if a == nil {
		return nil
	}
	return a.Symbol
}

func (a *AccountFixedIncome) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AccountFixedIncome) GetInstrumentID() *int64 {
	if a == nil {
		return nil
	}
	return a.InstrumentID
}

func (a *AccountFixedIncome) GetNetChange() *float64 {
	if a == nil {
		return nil
	}
	return a.NetChange
}

func (a *AccountFixedIncome) GetMaturityDate() *time.Time {
	if a == nil {
		return nil
	}
	return a.MaturityDate
}

func (a *AccountFixedIncome) GetFactor() *float64 {
	if a == nil {
		return nil
	}
	return a.Factor
}

func (a *AccountFixedIncome) GetVariableRate() *float64 {
	if a == nil {
		return nil
	}
	return a.VariableRate
}
