// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AccountNumberHash struct {
	AccountNumber *string `json:"accountNumber,omitzero"`
	HashValue     *string `json:"hashValue,omitzero"`
}

func (a *AccountNumberHash) GetAccountNumber() *string {
	if a == nil {
		return nil
	}
	return a.AccountNumber
}

func (a *AccountNumberHash) GetHashValue() *string {
	if a == nil {
		return nil
	}
	return a.HashValue
}
