// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

type APICurrencyType string

const (
	APICurrencyTypeUsd APICurrencyType = "USD"
	APICurrencyTypeCad APICurrencyType = "CAD"
	APICurrencyTypeEur APICurrencyType = "EUR"
	APICurrencyTypeJpy APICurrencyType = "JPY"
)

func (e APICurrencyType) ToPointer() *APICurrencyType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *APICurrencyType) IsExact() bool {
	if e != nil {
		switch *e {
		case "USD", "CAD", "EUR", "JPY":
			return true
		}
	}
	return false
}

type AccountAPIOptionDeliverable struct {
	Symbol           *int64           `integer:"string" json:"symbol,omitzero"`
	DeliverableUnits *float64         `json:"deliverableUnits,omitzero"`
	APICurrencyType  *APICurrencyType `json:"apiCurrencyType,omitzero"`
	AssetType        *AssetType       `json:"assetType,omitzero"`
}

func (a AccountAPIOptionDeliverable) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountAPIOptionDeliverable) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountAPIOptionDeliverable) GetSymbol() *int64 {
	if a == nil {
		return nil
	}
	return a.Symbol
}

func (a *AccountAPIOptionDeliverable) GetDeliverableUnits() *float64 {
	if a == nil {
		return nil
	}
	return a.DeliverableUnits
}

func (a *AccountAPIOptionDeliverable) GetAPICurrencyType() *APICurrencyType {
	if a == nil {
		return nil
	}
	return a.APICurrencyType
}

func (a *AccountAPIOptionDeliverable) GetAssetType() *AssetType {
	if a == nil {
		return nil
	}
	return a.AssetType
}
