// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"undefined/internal/utils"
)

type AccountsInstrumentType string

const (
	AccountsInstrumentTypeCashEquivalent AccountsInstrumentType = "CASH_EQUIVALENT"
	AccountsInstrumentTypeEquity         AccountsInstrumentType = "EQUITY"
	AccountsInstrumentTypeFixedIncome    AccountsInstrumentType = "FIXED_INCOME"
	AccountsInstrumentTypeMutualFund     AccountsInstrumentType = "MUTUAL_FUND"
	AccountsInstrumentTypeOption         AccountsInstrumentType = "OPTION"
)

type AccountsInstrument struct {
	AccountCashEquivalent  *AccountCashEquivalent  `queryParam:"inline" union:"member"`
	AccountsBaseInstrument *AccountsBaseInstrument `queryParam:"inline" union:"member"`
	AccountFixedIncome     *AccountFixedIncome     `queryParam:"inline" union:"member"`
	AccountsBaseInstrument *AccountsBaseInstrument `queryParam:"inline" union:"member"`
	AccountOption          *AccountOption          `queryParam:"inline" union:"member"`

	Type AccountsInstrumentType
}

func CreateAccountsInstrumentCashEquivalent(cashEquivalent AccountCashEquivalent) AccountsInstrument {
	typ := AccountsInstrumentTypeCashEquivalent

	typStr := AccountCashEquivalentAssetType(typ)
	cashEquivalent.AssetType = typStr

	return AccountsInstrument{
		AccountCashEquivalent: &cashEquivalent,
		Type:                  typ,
	}
}

func CreateAccountsInstrumentEquity(equity AccountsBaseInstrument) AccountsInstrument {
	typ := AccountsInstrumentTypeEquity

	typStr := AccountsBaseInstrumentAssetType(typ)
	equity.AssetType = typStr

	return AccountsInstrument{
		AccountsBaseInstrument: &equity,
		Type:                   typ,
	}
}

func CreateAccountsInstrumentFixedIncome(fixedIncome AccountFixedIncome) AccountsInstrument {
	typ := AccountsInstrumentTypeFixedIncome

	typStr := AccountFixedIncomeAssetType(typ)
	fixedIncome.AssetType = typStr

	return AccountsInstrument{
		AccountFixedIncome: &fixedIncome,
		Type:               typ,
	}
}

func CreateAccountsInstrumentMutualFund(mutualFund AccountsBaseInstrument) AccountsInstrument {
	typ := AccountsInstrumentTypeMutualFund

	typStr := AccountsBaseInstrumentAssetType(typ)
	mutualFund.AssetType = typStr

	return AccountsInstrument{
		AccountsBaseInstrument: &mutualFund,
		Type:                   typ,
	}
}

func CreateAccountsInstrumentOption(option AccountOption) AccountsInstrument {
	typ := AccountsInstrumentTypeOption

	typStr := AccountOptionAssetType(typ)
	option.AssetType = typStr

	return AccountsInstrument{
		AccountOption: &option,
		Type:          typ,
	}
}

func (u *AccountsInstrument) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		AssetType string `json:"assetType"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.AssetType {
	case "CASH_EQUIVALENT":
		accountCashEquivalent := new(AccountCashEquivalent)
		if err := utils.UnmarshalJSON(data, &accountCashEquivalent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (AssetType == CASH_EQUIVALENT) type AccountCashEquivalent within AccountsInstrument: %w", string(data), err)
		}

		u.AccountCashEquivalent = accountCashEquivalent
		u.Type = AccountsInstrumentTypeCashEquivalent
		return nil
	case "EQUITY":
		accountsBaseInstrument := new(AccountsBaseInstrument)
		if err := utils.UnmarshalJSON(data, &accountsBaseInstrument, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (AssetType == EQUITY) type AccountsBaseInstrument within AccountsInstrument: %w", string(data), err)
		}

		u.AccountsBaseInstrument = accountsBaseInstrument
		u.Type = AccountsInstrumentTypeEquity
		return nil
	case "FIXED_INCOME":
		accountFixedIncome := new(AccountFixedIncome)
		if err := utils.UnmarshalJSON(data, &accountFixedIncome, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (AssetType == FIXED_INCOME) type AccountFixedIncome within AccountsInstrument: %w", string(data), err)
		}

		u.AccountFixedIncome = accountFixedIncome
		u.Type = AccountsInstrumentTypeFixedIncome
		return nil
	case "MUTUAL_FUND":
		accountsBaseInstrument := new(AccountsBaseInstrument)
		if err := utils.UnmarshalJSON(data, &accountsBaseInstrument, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (AssetType == MUTUAL_FUND) type AccountsBaseInstrument within AccountsInstrument: %w", string(data), err)
		}

		u.AccountsBaseInstrument = accountsBaseInstrument
		u.Type = AccountsInstrumentTypeMutualFund
		return nil
	case "OPTION":
		accountOption := new(AccountOption)
		if err := utils.UnmarshalJSON(data, &accountOption, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (AssetType == OPTION) type AccountOption within AccountsInstrument: %w", string(data), err)
		}

		u.AccountOption = accountOption
		u.Type = AccountsInstrumentTypeOption
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for AccountsInstrument", string(data))
}

func (u AccountsInstrument) MarshalJSON() ([]byte, error) {
	if u.AccountCashEquivalent != nil {
		return utils.MarshalJSON(u.AccountCashEquivalent, "", true)
	}

	if u.AccountsBaseInstrument != nil {
		return utils.MarshalJSON(u.AccountsBaseInstrument, "", true)
	}

	if u.AccountFixedIncome != nil {
		return utils.MarshalJSON(u.AccountFixedIncome, "", true)
	}

	if u.AccountsBaseInstrument != nil {
		return utils.MarshalJSON(u.AccountsBaseInstrument, "", true)
	}

	if u.AccountOption != nil {
		return utils.MarshalJSON(u.AccountOption, "", true)
	}

	return nil, errors.New("could not marshal union type AccountsInstrument: all fields are null")
}
