// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type AccountsBaseInstrumentAssetType string

const (
	AccountsBaseInstrumentAssetTypeEquity               AccountsBaseInstrumentAssetType = "EQUITY"
	AccountsBaseInstrumentAssetTypeOption               AccountsBaseInstrumentAssetType = "OPTION"
	AccountsBaseInstrumentAssetTypeIndex                AccountsBaseInstrumentAssetType = "INDEX"
	AccountsBaseInstrumentAssetTypeMutualFund           AccountsBaseInstrumentAssetType = "MUTUAL_FUND"
	AccountsBaseInstrumentAssetTypeCashEquivalent       AccountsBaseInstrumentAssetType = "CASH_EQUIVALENT"
	AccountsBaseInstrumentAssetTypeFixedIncome          AccountsBaseInstrumentAssetType = "FIXED_INCOME"
	AccountsBaseInstrumentAssetTypeCurrency             AccountsBaseInstrumentAssetType = "CURRENCY"
	AccountsBaseInstrumentAssetTypeCollectiveInvestment AccountsBaseInstrumentAssetType = "COLLECTIVE_INVESTMENT"
)

func (e AccountsBaseInstrumentAssetType) ToPointer() *AccountsBaseInstrumentAssetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AccountsBaseInstrumentAssetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EQUITY", "OPTION", "INDEX", "MUTUAL_FUND", "CASH_EQUIVALENT", "FIXED_INCOME", "CURRENCY", "COLLECTIVE_INVESTMENT":
			return true
		}
	}
	return false
}

type AccountsBaseInstrument struct {
	AssetType    AccountsBaseInstrumentAssetType `json:"assetType"`
	Cusip        *string                         `json:"cusip,omitzero"`
	Symbol       *string                         `json:"symbol,omitzero"`
	Description  *string                         `json:"description,omitzero"`
	InstrumentID *int64                          `json:"instrumentId,omitzero"`
	NetChange    *float64                        `json:"netChange,omitzero"`
}

func (a AccountsBaseInstrument) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountsBaseInstrument) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountsBaseInstrument) GetAssetType() AccountsBaseInstrumentAssetType {
	if a == nil {
		return AccountsBaseInstrumentAssetType("")
	}
	return a.AssetType
}

func (a *AccountsBaseInstrument) GetCusip() *string {
	if a == nil {
		return nil
	}
	return a.Cusip
}

func (a *AccountsBaseInstrument) GetSymbol() *string {
	if a == nil {
		return nil
	}
	return a.Symbol
}

func (a *AccountsBaseInstrument) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AccountsBaseInstrument) GetInstrumentID() *int64 {
	if a == nil {
		return nil
	}
	return a.InstrumentID
}

func (a *AccountsBaseInstrument) GetNetChange() *float64 {
	if a == nil {
		return nil
	}
	return a.NetChange
}
