// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type AccountMutualFundAssetType string

const (
	AccountMutualFundAssetTypeEquity               AccountMutualFundAssetType = "EQUITY"
	AccountMutualFundAssetTypeOption               AccountMutualFundAssetType = "OPTION"
	AccountMutualFundAssetTypeIndex                AccountMutualFundAssetType = "INDEX"
	AccountMutualFundAssetTypeMutualFund           AccountMutualFundAssetType = "MUTUAL_FUND"
	AccountMutualFundAssetTypeCashEquivalent       AccountMutualFundAssetType = "CASH_EQUIVALENT"
	AccountMutualFundAssetTypeFixedIncome          AccountMutualFundAssetType = "FIXED_INCOME"
	AccountMutualFundAssetTypeCurrency             AccountMutualFundAssetType = "CURRENCY"
	AccountMutualFundAssetTypeCollectiveInvestment AccountMutualFundAssetType = "COLLECTIVE_INVESTMENT"
)

func (e AccountMutualFundAssetType) ToPointer() *AccountMutualFundAssetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AccountMutualFundAssetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EQUITY", "OPTION", "INDEX", "MUTUAL_FUND", "CASH_EQUIVALENT", "FIXED_INCOME", "CURRENCY", "COLLECTIVE_INVESTMENT":
			return true
		}
	}
	return false
}

type AccountMutualFund struct {
	AssetType    AccountMutualFundAssetType `json:"assetType"`
	Cusip        *string                    `json:"cusip,omitzero"`
	Symbol       *string                    `json:"symbol,omitzero"`
	Description  *string                    `json:"description,omitzero"`
	InstrumentID *int64                     `json:"instrumentId,omitzero"`
	NetChange    *float64                   `json:"netChange,omitzero"`
	Type         *string                    `default:"AccountMutualFund" json:"_type"`
}

func (a AccountMutualFund) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountMutualFund) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountMutualFund) GetAssetType() AccountMutualFundAssetType {
	if a == nil {
		return AccountMutualFundAssetType("")
	}
	return a.AssetType
}

func (a *AccountMutualFund) GetCusip() *string {
	if a == nil {
		return nil
	}
	return a.Cusip
}

func (a *AccountMutualFund) GetSymbol() *string {
	if a == nil {
		return nil
	}
	return a.Symbol
}

func (a *AccountMutualFund) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AccountMutualFund) GetInstrumentID() *int64 {
	if a == nil {
		return nil
	}
	return a.InstrumentID
}

func (a *AccountMutualFund) GetNetChange() *float64 {
	if a == nil {
		return nil
	}
	return a.NetChange
}

func (a *AccountMutualFund) GetType() *string {
	if a == nil {
		return nil
	}
	return a.Type
}
