// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AmountIndicator string

const (
	AmountIndicatorDollars    AmountIndicator = "DOLLARS"
	AmountIndicatorShares     AmountIndicator = "SHARES"
	AmountIndicatorAllShares  AmountIndicator = "ALL_SHARES"
	AmountIndicatorPercentage AmountIndicator = "PERCENTAGE"
	AmountIndicatorUnknown    AmountIndicator = "UNKNOWN"
)

func (e AmountIndicator) ToPointer() *AmountIndicator {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AmountIndicator) IsExact() bool {
	if e != nil {
		switch *e {
		case "DOLLARS", "SHARES", "ALL_SHARES", "PERCENTAGE", "UNKNOWN":
			return true
		}
	}
	return false
}
