// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type APIRuleAction string

const (
	APIRuleActionAccept  APIRuleAction = "ACCEPT"
	APIRuleActionAlert   APIRuleAction = "ALERT"
	APIRuleActionReject  APIRuleAction = "REJECT"
	APIRuleActionReview  APIRuleAction = "REVIEW"
	APIRuleActionUnknown APIRuleAction = "UNKNOWN"
)

func (e APIRuleAction) ToPointer() *APIRuleAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *APIRuleAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "ACCEPT", "ALERT", "REJECT", "REVIEW", "UNKNOWN":
			return true
		}
	}
	return false
}
