// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AssetType string

const (
	AssetTypeEquity               AssetType = "EQUITY"
	AssetTypeMutualFund           AssetType = "MUTUAL_FUND"
	AssetTypeOption               AssetType = "OPTION"
	AssetTypeFuture               AssetType = "FUTURE"
	AssetTypeForex                AssetType = "FOREX"
	AssetTypeIndex                AssetType = "INDEX"
	AssetTypeCashEquivalent       AssetType = "CASH_EQUIVALENT"
	AssetTypeFixedIncome          AssetType = "FIXED_INCOME"
	AssetTypeProduct              AssetType = "PRODUCT"
	AssetTypeCurrency             AssetType = "CURRENCY"
	AssetTypeCollectiveInvestment AssetType = "COLLECTIVE_INVESTMENT"
)

func (e AssetType) ToPointer() *AssetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AssetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EQUITY", "MUTUAL_FUND", "OPTION", "FUTURE", "FOREX", "INDEX", "CASH_EQUIVALENT", "FIXED_INCOME", "PRODUCT", "CURRENCY", "COLLECTIVE_INVESTMENT":
			return true
		}
	}
	return false
}
