// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AssetMainType - Instrument's asset type
type AssetMainType string

const (
	AssetMainTypeBond         AssetMainType = "BOND"
	AssetMainTypeEquity       AssetMainType = "EQUITY"
	AssetMainTypeForex        AssetMainType = "FOREX"
	AssetMainTypeFuture       AssetMainType = "FUTURE"
	AssetMainTypeFutureOption AssetMainType = "FUTURE_OPTION"
	AssetMainTypeIndex        AssetMainType = "INDEX"
	AssetMainTypeMutualFund   AssetMainType = "MUTUAL_FUND"
	AssetMainTypeOption       AssetMainType = "OPTION"
)

func (e AssetMainType) ToPointer() *AssetMainType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AssetMainType) IsExact() bool {
	if e != nil {
		switch *e {
		case "BOND", "EQUITY", "FOREX", "FUTURE", "FUTURE_OPTION", "INDEX", "MUTUAL_FUND", "OPTION":
			return true
		}
	}
	return false
}
