// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BondAssetType string

const (
	BondAssetTypeBond         BondAssetType = "BOND"
	BondAssetTypeEquity       BondAssetType = "EQUITY"
	BondAssetTypeEtf          BondAssetType = "ETF"
	BondAssetTypeExtended     BondAssetType = "EXTENDED"
	BondAssetTypeForex        BondAssetType = "FOREX"
	BondAssetTypeFuture       BondAssetType = "FUTURE"
	BondAssetTypeFutureOption BondAssetType = "FUTURE_OPTION"
	BondAssetTypeFundamental  BondAssetType = "FUNDAMENTAL"
	BondAssetTypeIndex        BondAssetType = "INDEX"
	BondAssetTypeIndicator    BondAssetType = "INDICATOR"
	BondAssetTypeMutualFund   BondAssetType = "MUTUAL_FUND"
	BondAssetTypeOption       BondAssetType = "OPTION"
	BondAssetTypeUnknown      BondAssetType = "UNKNOWN"
)

func (e BondAssetType) ToPointer() *BondAssetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *BondAssetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "BOND", "EQUITY", "ETF", "EXTENDED", "FOREX", "FUTURE", "FUTURE_OPTION", "FUNDAMENTAL", "INDEX", "INDICATOR", "MUTUAL_FUND", "OPTION", "UNKNOWN":
			return true
		}
	}
	return false
}

type Bond struct {
	Cusip          *string        `json:"cusip,omitzero"`
	Symbol         *string        `json:"symbol,omitzero"`
	Description    *string        `json:"description,omitzero"`
	Exchange       *string        `json:"exchange,omitzero"`
	AssetType      *BondAssetType `json:"assetType,omitzero"`
	BondFactor     *string        `json:"bondFactor,omitzero"`
	BondMultiplier *string        `json:"bondMultiplier,omitzero"`
	BondPrice      *float64       `json:"bondPrice,omitzero"`
}

func (b *Bond) GetCusip() *string {
	if b == nil {
		return nil
	}
	return b.Cusip
}

func (b *Bond) GetSymbol() *string {
	if b == nil {
		return nil
	}
	return b.Symbol
}

func (b *Bond) GetDescription() *string {
	if b == nil {
		return nil
	}
	return b.Description
}

func (b *Bond) GetExchange() *string {
	if b == nil {
		return nil
	}
	return b.Exchange
}

func (b *Bond) GetAssetType() *BondAssetType {
	if b == nil {
		return nil
	}
	return b.AssetType
}

func (b *Bond) GetBondFactor() *string {
	if b == nil {
		return nil
	}
	return b.BondFactor
}

func (b *Bond) GetBondMultiplier() *string {
	if b == nil {
		return nil
	}
	return b.BondMultiplier
}

func (b *Bond) GetBondPrice() *float64 {
	if b == nil {
		return nil
	}
	return b.BondPrice
}
