// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Candle struct {
	Close           *float64 `json:"close,omitzero"`
	Datetime        *int64   `json:"datetime,omitzero"`
	DatetimeIso8601 *string  `json:"datetimeISO8601,omitzero"`
	High            *float64 `json:"high,omitzero"`
	Low             *float64 `json:"low,omitzero"`
	Open            *float64 `json:"open,omitzero"`
	Volume          *int64   `json:"volume,omitzero"`
}

func (c *Candle) GetClose() *float64 {
	if c == nil {
		return nil
	}
	return c.Close
}

func (c *Candle) GetDatetime() *int64 {
	if c == nil {
		return nil
	}
	return c.Datetime
}

func (c *Candle) GetDatetimeIso8601() *string {
	if c == nil {
		return nil
	}
	return c.DatetimeIso8601
}

func (c *Candle) GetHigh() *float64 {
	if c == nil {
		return nil
	}
	return c.High
}

func (c *Candle) GetLow() *float64 {
	if c == nil {
		return nil
	}
	return c.Low
}

func (c *Candle) GetOpen() *float64 {
	if c == nil {
		return nil
	}
	return c.Open
}

func (c *Candle) GetVolume() *int64 {
	if c == nil {
		return nil
	}
	return c.Volume
}
