// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

type CandleList struct {
	Candles                  []Candle `json:"candles,omitzero"`
	Empty                    *bool    `json:"empty,omitzero"`
	PreviousClose            *float64 `json:"previousClose,omitzero"`
	PreviousCloseDate        *int64   `json:"previousCloseDate,omitzero"`
	PreviousCloseDateIso8601 *string  `json:"previousCloseDateISO8601,omitzero"`
	Symbol                   *string  `json:"symbol,omitzero"`
}

func (c CandleList) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CandleList) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CandleList) GetCandles() []Candle {
	if c == nil {
		return nil
	}
	return c.Candles
}

func (c *CandleList) GetEmpty() *bool {
	if c == nil {
		return nil
	}
	return c.Empty
}

func (c *CandleList) GetPreviousClose() *float64 {
	if c == nil {
		return nil
	}
	return c.PreviousClose
}

func (c *CandleList) GetPreviousCloseDate() *int64 {
	if c == nil {
		return nil
	}
	return c.PreviousCloseDate
}

func (c *CandleList) GetPreviousCloseDateIso8601() *string {
	if c == nil {
		return nil
	}
	return c.PreviousCloseDateIso8601
}

func (c *CandleList) GetSymbol() *string {
	if c == nil {
		return nil
	}
	return c.Symbol
}
