// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type CashInitialBalance struct {
	AccruedInterest            *float64 `json:"accruedInterest,omitzero"`
	CashAvailableForTrading    *float64 `json:"cashAvailableForTrading,omitzero"`
	CashAvailableForWithdrawal *float64 `json:"cashAvailableForWithdrawal,omitzero"`
	CashBalance                *float64 `json:"cashBalance,omitzero"`
	BondValue                  *float64 `json:"bondValue,omitzero"`
	CashReceipts               *float64 `json:"cashReceipts,omitzero"`
	LiquidationValue           *float64 `json:"liquidationValue,omitzero"`
	LongOptionMarketValue      *float64 `json:"longOptionMarketValue,omitzero"`
	LongStockValue             *float64 `json:"longStockValue,omitzero"`
	MoneyMarketFund            *float64 `json:"moneyMarketFund,omitzero"`
	MutualFundValue            *float64 `json:"mutualFundValue,omitzero"`
	ShortOptionMarketValue     *float64 `json:"shortOptionMarketValue,omitzero"`
	ShortStockValue            *float64 `json:"shortStockValue,omitzero"`
	IsInCall                   *float64 `json:"isInCall,omitzero"`
	UnsettledCash              *float64 `json:"unsettledCash,omitzero"`
	CashDebitCallValue         *float64 `json:"cashDebitCallValue,omitzero"`
	PendingDeposits            *float64 `json:"pendingDeposits,omitzero"`
	AccountValue               *float64 `json:"accountValue,omitzero"`
}

func (c CashInitialBalance) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CashInitialBalance) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CashInitialBalance) GetAccruedInterest() *float64 {
	if c == nil {
		return nil
	}
	return c.AccruedInterest
}

func (c *CashInitialBalance) GetCashAvailableForTrading() *float64 {
	if c == nil {
		return nil
	}
	return c.CashAvailableForTrading
}

func (c *CashInitialBalance) GetCashAvailableForWithdrawal() *float64 {
	if c == nil {
		return nil
	}
	return c.CashAvailableForWithdrawal
}

func (c *CashInitialBalance) GetCashBalance() *float64 {
	if c == nil {
		return nil
	}
	return c.CashBalance
}

func (c *CashInitialBalance) GetBondValue() *float64 {
	if c == nil {
		return nil
	}
	return c.BondValue
}

func (c *CashInitialBalance) GetCashReceipts() *float64 {
	if c == nil {
		return nil
	}
	return c.CashReceipts
}

func (c *CashInitialBalance) GetLiquidationValue() *float64 {
	if c == nil {
		return nil
	}
	return c.LiquidationValue
}

func (c *CashInitialBalance) GetLongOptionMarketValue() *float64 {
	if c == nil {
		return nil
	}
	return c.LongOptionMarketValue
}

func (c *CashInitialBalance) GetLongStockValue() *float64 {
	if c == nil {
		return nil
	}
	return c.LongStockValue
}

func (c *CashInitialBalance) GetMoneyMarketFund() *float64 {
	if c == nil {
		return nil
	}
	return c.MoneyMarketFund
}

func (c *CashInitialBalance) GetMutualFundValue() *float64 {
	if c == nil {
		return nil
	}
	return c.MutualFundValue
}

func (c *CashInitialBalance) GetShortOptionMarketValue() *float64 {
	if c == nil {
		return nil
	}
	return c.ShortOptionMarketValue
}

func (c *CashInitialBalance) GetShortStockValue() *float64 {
	if c == nil {
		return nil
	}
	return c.ShortStockValue
}

func (c *CashInitialBalance) GetIsInCall() *float64 {
	if c == nil {
		return nil
	}
	return c.IsInCall
}

func (c *CashInitialBalance) GetUnsettledCash() *float64 {
	if c == nil {
		return nil
	}
	return c.UnsettledCash
}

func (c *CashInitialBalance) GetCashDebitCallValue() *float64 {
	if c == nil {
		return nil
	}
	return c.CashDebitCallValue
}

func (c *CashInitialBalance) GetPendingDeposits() *float64 {
	if c == nil {
		return nil
	}
	return c.PendingDeposits
}

func (c *CashInitialBalance) GetAccountValue() *float64 {
	if c == nil {
		return nil
	}
	return c.AccountValue
}
