// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

type CashAccountType string

const (
	CashAccountTypeCash   CashAccountType = "CASH"
	CashAccountTypeMargin CashAccountType = "MARGIN"
)

func (e CashAccountType) ToPointer() *CashAccountType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CashAccountType) IsExact() bool {
	if e != nil {
		switch *e {
		case "CASH", "MARGIN":
			return true
		}
	}
	return false
}

type CashAccount struct {
	Type                    *CashAccountType    `json:"type,omitzero"`
	AccountNumber           *string             `json:"accountNumber,omitzero"`
	RoundTrips              *int                `json:"roundTrips,omitzero"`
	IsDayTrader             *bool               `default:"false" json:"isDayTrader"`
	IsClosingOnlyRestricted *bool               `default:"false" json:"isClosingOnlyRestricted"`
	PfcbFlag                *bool               `default:"false" json:"pfcbFlag"`
	Positions               []Position          `json:"positions,omitzero"`
	InitialBalances         *CashInitialBalance `json:"initialBalances,omitzero"`
	CurrentBalances         *CashBalance        `json:"currentBalances,omitzero"`
	ProjectedBalances       *CashBalance        `json:"projectedBalances,omitzero"`
}

func (c CashAccount) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CashAccount) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CashAccount) GetType() *CashAccountType {
	if c == nil {
		return nil
	}
	return c.Type
}

func (c *CashAccount) GetAccountNumber() *string {
	if c == nil {
		return nil
	}
	return c.AccountNumber
}

func (c *CashAccount) GetRoundTrips() *int {
	if c == nil {
		return nil
	}
	return c.RoundTrips
}

func (c *CashAccount) GetIsDayTrader() *bool {
	if c == nil {
		return nil
	}
	return c.IsDayTrader
}

func (c *CashAccount) GetIsClosingOnlyRestricted() *bool {
	if c == nil {
		return nil
	}
	return c.IsClosingOnlyRestricted
}

func (c *CashAccount) GetPfcbFlag() *bool {
	if c == nil {
		return nil
	}
	return c.PfcbFlag
}

func (c *CashAccount) GetPositions() []Position {
	if c == nil {
		return nil
	}
	return c.Positions
}

func (c *CashAccount) GetInitialBalances() *CashInitialBalance {
	if c == nil {
		return nil
	}
	return c.InitialBalances
}

func (c *CashAccount) GetCurrentBalances() *CashBalance {
	if c == nil {
		return nil
	}
	return c.CurrentBalances
}

func (c *CashAccount) GetProjectedBalances() *CashBalance {
	if c == nil {
		return nil
	}
	return c.ProjectedBalances
}
