// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type CashBalance struct {
	CashAvailableForTrading      *float64 `json:"cashAvailableForTrading,omitzero"`
	CashAvailableForWithdrawal   *float64 `json:"cashAvailableForWithdrawal,omitzero"`
	CashCall                     *float64 `json:"cashCall,omitzero"`
	LongNonMarginableMarketValue *float64 `json:"longNonMarginableMarketValue,omitzero"`
	TotalCash                    *float64 `json:"totalCash,omitzero"`
	CashDebitCallValue           *float64 `json:"cashDebitCallValue,omitzero"`
	UnsettledCash                *float64 `json:"unsettledCash,omitzero"`
}

func (c CashBalance) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CashBalance) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CashBalance) GetCashAvailableForTrading() *float64 {
	if c == nil {
		return nil
	}
	return c.CashAvailableForTrading
}

func (c *CashBalance) GetCashAvailableForWithdrawal() *float64 {
	if c == nil {
		return nil
	}
	return c.CashAvailableForWithdrawal
}

func (c *CashBalance) GetCashCall() *float64 {
	if c == nil {
		return nil
	}
	return c.CashCall
}

func (c *CashBalance) GetLongNonMarginableMarketValue() *float64 {
	if c == nil {
		return nil
	}
	return c.LongNonMarginableMarketValue
}

func (c *CashBalance) GetTotalCash() *float64 {
	if c == nil {
		return nil
	}
	return c.TotalCash
}

func (c *CashBalance) GetCashDebitCallValue() *float64 {
	if c == nil {
		return nil
	}
	return c.CashDebitCallValue
}

func (c *CashBalance) GetUnsettledCash() *float64 {
	if c == nil {
		return nil
	}
	return c.UnsettledCash
}
