// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type CollectiveInvestmentAssetType string

const (
	CollectiveInvestmentAssetTypeEquity               CollectiveInvestmentAssetType = "EQUITY"
	CollectiveInvestmentAssetTypeOption               CollectiveInvestmentAssetType = "OPTION"
	CollectiveInvestmentAssetTypeIndex                CollectiveInvestmentAssetType = "INDEX"
	CollectiveInvestmentAssetTypeMutualFund           CollectiveInvestmentAssetType = "MUTUAL_FUND"
	CollectiveInvestmentAssetTypeCashEquivalent       CollectiveInvestmentAssetType = "CASH_EQUIVALENT"
	CollectiveInvestmentAssetTypeFixedIncome          CollectiveInvestmentAssetType = "FIXED_INCOME"
	CollectiveInvestmentAssetTypeCurrency             CollectiveInvestmentAssetType = "CURRENCY"
	CollectiveInvestmentAssetTypeCollectiveInvestment CollectiveInvestmentAssetType = "COLLECTIVE_INVESTMENT"
)

func (e CollectiveInvestmentAssetType) ToPointer() *CollectiveInvestmentAssetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CollectiveInvestmentAssetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EQUITY", "OPTION", "INDEX", "MUTUAL_FUND", "CASH_EQUIVALENT", "FIXED_INCOME", "CURRENCY", "COLLECTIVE_INVESTMENT":
			return true
		}
	}
	return false
}

type CollectiveInvestmentType string

const (
	CollectiveInvestmentTypeUnitInvestmentTrust CollectiveInvestmentType = "UNIT_INVESTMENT_TRUST"
	CollectiveInvestmentTypeExchangeTradedFund  CollectiveInvestmentType = "EXCHANGE_TRADED_FUND"
	CollectiveInvestmentTypeClosedEndFund       CollectiveInvestmentType = "CLOSED_END_FUND"
	CollectiveInvestmentTypeIndex               CollectiveInvestmentType = "INDEX"
	CollectiveInvestmentTypeUnits               CollectiveInvestmentType = "UNITS"
)

func (e CollectiveInvestmentType) ToPointer() *CollectiveInvestmentType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CollectiveInvestmentType) IsExact() bool {
	if e != nil {
		switch *e {
		case "UNIT_INVESTMENT_TRUST", "EXCHANGE_TRADED_FUND", "CLOSED_END_FUND", "INDEX", "UNITS":
			return true
		}
	}
	return false
}

type CollectiveInvestment struct {
	AssetType    CollectiveInvestmentAssetType `json:"assetType"`
	Cusip        *string                       `json:"cusip,omitzero"`
	Symbol       *string                       `json:"symbol,omitzero"`
	Description  *string                       `json:"description,omitzero"`
	InstrumentID *int64                        `json:"instrumentId,omitzero"`
	NetChange    *float64                      `json:"netChange,omitzero"`
	Type         *CollectiveInvestmentType     `json:"type,omitzero"`
}

func (c CollectiveInvestment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectiveInvestment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CollectiveInvestment) GetAssetType() CollectiveInvestmentAssetType {
	if c == nil {
		return CollectiveInvestmentAssetType("")
	}
	return c.AssetType
}

func (c *CollectiveInvestment) GetCusip() *string {
	if c == nil {
		return nil
	}
	return c.Cusip
}

func (c *CollectiveInvestment) GetSymbol() *string {
	if c == nil {
		return nil
	}
	return c.Symbol
}

func (c *CollectiveInvestment) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CollectiveInvestment) GetInstrumentID() *int64 {
	if c == nil {
		return nil
	}
	return c.InstrumentID
}

func (c *CollectiveInvestment) GetNetChange() *float64 {
	if c == nil {
		return nil
	}
	return c.NetChange
}

func (c *CollectiveInvestment) GetType() *CollectiveInvestmentType {
	if c == nil {
		return nil
	}
	return c.Type
}
