// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

type Commission struct {
	CommissionLegs []CommissionLeg `json:"commissionLegs,omitzero"`
}

func (c Commission) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Commission) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Commission) GetCommissionLegs() []CommissionLeg {
	if c == nil {
		return nil
	}
	return c.CommissionLegs
}
