// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CommissionValue struct {
	Value *float64 `json:"value,omitzero"`
	Type  *FeeType `json:"type,omitzero"`
}

func (c *CommissionValue) GetValue() *float64 {
	if c == nil {
		return nil
	}
	return c.Value
}

func (c *CommissionValue) GetType() *FeeType {
	if c == nil {
		return nil
	}
	return c.Type
}
