// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

type CommissionLeg struct {
	CommissionValues []CommissionValue `json:"commissionValues,omitzero"`
}

func (c CommissionLeg) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CommissionLeg) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CommissionLeg) GetCommissionValues() []CommissionValue {
	if c == nil {
		return nil
	}
	return c.CommissionValues
}
