// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type CommissionAndFee struct {
	Commission     *Commission `json:"commission,omitzero"`
	Fee            *Fees       `json:"fee,omitzero"`
	TrueCommission *Commission `json:"trueCommission,omitzero"`
}

func (c CommissionAndFee) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CommissionAndFee) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CommissionAndFee) GetCommission() *Commission {
	if c == nil {
		return nil
	}
	return c.Commission
}

func (c *CommissionAndFee) GetFee() *Fees {
	if c == nil {
		return nil
	}
	return c.Fee
}

func (c *CommissionAndFee) GetTrueCommission() *Commission {
	if c == nil {
		return nil
	}
	return c.TrueCommission
}
