// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ComplexOrderStrategyType string

const (
	ComplexOrderStrategyTypeNone                   ComplexOrderStrategyType = "NONE"
	ComplexOrderStrategyTypeCovered                ComplexOrderStrategyType = "COVERED"
	ComplexOrderStrategyTypeVertical               ComplexOrderStrategyType = "VERTICAL"
	ComplexOrderStrategyTypeBackRatio              ComplexOrderStrategyType = "BACK_RATIO"
	ComplexOrderStrategyTypeCalendar               ComplexOrderStrategyType = "CALENDAR"
	ComplexOrderStrategyTypeDiagonal               ComplexOrderStrategyType = "DIAGONAL"
	ComplexOrderStrategyTypeStraddle               ComplexOrderStrategyType = "STRADDLE"
	ComplexOrderStrategyTypeStrangle               ComplexOrderStrategyType = "STRANGLE"
	ComplexOrderStrategyTypeCollarSynthetic        ComplexOrderStrategyType = "COLLAR_SYNTHETIC"
	ComplexOrderStrategyTypeButterfly              ComplexOrderStrategyType = "BUTTERFLY"
	ComplexOrderStrategyTypeCondor                 ComplexOrderStrategyType = "CONDOR"
	ComplexOrderStrategyTypeIronCondor             ComplexOrderStrategyType = "IRON_CONDOR"
	ComplexOrderStrategyTypeVerticalRoll           ComplexOrderStrategyType = "VERTICAL_ROLL"
	ComplexOrderStrategyTypeCollarWithStock        ComplexOrderStrategyType = "COLLAR_WITH_STOCK"
	ComplexOrderStrategyTypeDoubleDiagonal         ComplexOrderStrategyType = "DOUBLE_DIAGONAL"
	ComplexOrderStrategyTypeUnbalancedButterfly    ComplexOrderStrategyType = "UNBALANCED_BUTTERFLY"
	ComplexOrderStrategyTypeUnbalancedCondor       ComplexOrderStrategyType = "UNBALANCED_CONDOR"
	ComplexOrderStrategyTypeUnbalancedIronCondor   ComplexOrderStrategyType = "UNBALANCED_IRON_CONDOR"
	ComplexOrderStrategyTypeUnbalancedVerticalRoll ComplexOrderStrategyType = "UNBALANCED_VERTICAL_ROLL"
	ComplexOrderStrategyTypeMutualFundSwap         ComplexOrderStrategyType = "MUTUAL_FUND_SWAP"
	ComplexOrderStrategyTypeCustom                 ComplexOrderStrategyType = "CUSTOM"
)

func (e ComplexOrderStrategyType) ToPointer() *ComplexOrderStrategyType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ComplexOrderStrategyType) IsExact() bool {
	if e != nil {
		switch *e {
		case "NONE", "COVERED", "VERTICAL", "BACK_RATIO", "CALENDAR", "DIAGONAL", "STRADDLE", "STRANGLE", "COLLAR_SYNTHETIC", "BUTTERFLY", "CONDOR", "IRON_CONDOR", "VERTICAL_ROLL", "COLLAR_WITH_STOCK", "DOUBLE_DIAGONAL", "UNBALANCED_BUTTERFLY", "UNBALANCED_CONDOR", "UNBALANCED_IRON_CONDOR", "UNBALANCED_VERTICAL_ROLL", "MUTUAL_FUND_SWAP", "CUSTOM":
			return true
		}
	}
	return false
}
