// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ContractType - Indicates call or put
type ContractType string

const (
	ContractTypeP ContractType = "P"
	ContractTypeC ContractType = "C"
)

func (e ContractType) ToPointer() *ContractType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ContractType) IsExact() bool {
	if e != nil {
		switch *e {
		case "P", "C":
			return true
		}
	}
	return false
}
