// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DivFreq - Dividend frequency 1 – once a year or annually 2 – 2x a year or semi-annualy 3 - 3x a year (ex. ARCO, EBRPF) 4 – 4x a year or quarterly 6 - 6x per yr or every other month 11 – 11x a year (ex. FBND, FCOR) 12 – 12x a year or monthly
type DivFreq int64

const (
	DivFreqOne    DivFreq = 1
	DivFreqTwo    DivFreq = 2
	DivFreqThree  DivFreq = 3
	DivFreqFour   DivFreq = 4
	DivFreqSix    DivFreq = 6
	DivFreqEleven DivFreq = 11
	DivFreqTwelve DivFreq = 12
)

func (e DivFreq) ToPointer() *DivFreq {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DivFreq) IsExact() bool {
	if e != nil {
		switch *e {
		case 1, 2, 3, 4, 6, 11, 12:
			return true
		}
	}
	return false
}
