// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Duration string

const (
	DurationDay               Duration = "DAY"
	DurationGoodTillCancel    Duration = "GOOD_TILL_CANCEL"
	DurationFillOrKill        Duration = "FILL_OR_KILL"
	DurationImmediateOrCancel Duration = "IMMEDIATE_OR_CANCEL"
	DurationEndOfWeek         Duration = "END_OF_WEEK"
	DurationEndOfMonth        Duration = "END_OF_MONTH"
	DurationNextEndOfMonth    Duration = "NEXT_END_OF_MONTH"
	DurationUnknown           Duration = "UNKNOWN"
)

func (e Duration) ToPointer() *Duration {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Duration) IsExact() bool {
	if e != nil {
		switch *e {
		case "DAY", "GOOD_TILL_CANCEL", "FILL_OR_KILL", "IMMEDIATE_OR_CANCEL", "END_OF_WEEK", "END_OF_MONTH", "NEXT_END_OF_MONTH", "UNKNOWN":
			return true
		}
	}
	return false
}
