// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
	"github.com/Chalupa-Tech/go-schwab-api-individual/optionalnullable"
)

// EquityResponse - Quote info of Equity security
type EquityResponse struct {
	// Instrument's asset type
	AssetMainType *AssetMainType `json:"assetMainType,omitzero"`
	// Asset Sub Type (only there if applicable)
	AssetSubType optionalnullable.OptionalNullable[EquityAssetSubType] `json:"assetSubType,omitzero"`
	// SSID of instrument
	Ssid *int64 `json:"ssid,omitzero"`
	// Symbol of instrument
	Symbol *string `json:"symbol,omitzero"`
	// is quote realtime
	Realtime *bool `json:"realtime,omitzero"`
	// NBBO - realtime, NFL - Non-fee liable quote.
	QuoteType optionalnullable.OptionalNullable[QuoteType] `json:"quoteType,omitzero"`
	// Quote data for extended hours
	Extended *ExtendedMarket `json:"extended,omitzero"`
	// Fundamentals of a security
	Fundamental *Fundamental `json:"fundamental,omitzero"`
	// Quote data of Equity security
	Quote *QuoteEquity `json:"quote,omitzero"`
	// Reference data of Equity security
	Reference *ReferenceEquity `json:"reference,omitzero"`
	// Market info of security
	Regular *RegularMarket `json:"regular,omitzero"`
}

func (e EquityResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EquityResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EquityResponse) GetAssetMainType() *AssetMainType {
	if e == nil {
		return nil
	}
	return e.AssetMainType
}

func (e *EquityResponse) GetAssetSubType() optionalnullable.OptionalNullable[EquityAssetSubType] {
	if e == nil {
		return nil
	}
	return e.AssetSubType
}

func (e *EquityResponse) GetSsid() *int64 {
	if e == nil {
		return nil
	}
	return e.Ssid
}

func (e *EquityResponse) GetSymbol() *string {
	if e == nil {
		return nil
	}
	return e.Symbol
}

func (e *EquityResponse) GetRealtime() *bool {
	if e == nil {
		return nil
	}
	return e.Realtime
}

func (e *EquityResponse) GetQuoteType() optionalnullable.OptionalNullable[QuoteType] {
	if e == nil {
		return nil
	}
	return e.QuoteType
}

func (e *EquityResponse) GetExtended() *ExtendedMarket {
	if e == nil {
		return nil
	}
	return e.Extended
}

func (e *EquityResponse) GetFundamental() *Fundamental {
	if e == nil {
		return nil
	}
	return e.Fundamental
}

func (e *EquityResponse) GetQuote() *QuoteEquity {
	if e == nil {
		return nil
	}
	return e.Quote
}

func (e *EquityResponse) GetReference() *ReferenceEquity {
	if e == nil {
		return nil
	}
	return e.Reference
}

func (e *EquityResponse) GetRegular() *RegularMarket {
	if e == nil {
		return nil
	}
	return e.Regular
}
