// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// EquityAssetSubType - Asset Sub Type (only there if applicable)
type EquityAssetSubType string

const (
	EquityAssetSubTypeCoe EquityAssetSubType = "COE"
	EquityAssetSubTypePrf EquityAssetSubType = "PRF"
	EquityAssetSubTypeAdr EquityAssetSubType = "ADR"
	EquityAssetSubTypeGdr EquityAssetSubType = "GDR"
	EquityAssetSubTypeCef EquityAssetSubType = "CEF"
	EquityAssetSubTypeEtf EquityAssetSubType = "ETF"
	EquityAssetSubTypeEtn EquityAssetSubType = "ETN"
	EquityAssetSubTypeUit EquityAssetSubType = "UIT"
	EquityAssetSubTypeWar EquityAssetSubType = "WAR"
	EquityAssetSubTypeRgt EquityAssetSubType = "RGT"
)

func (e EquityAssetSubType) ToPointer() *EquityAssetSubType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *EquityAssetSubType) IsExact() bool {
	if e != nil {
		switch *e {
		case "COE", "PRF", "ADR", "GDR", "CEF", "ETF", "ETN", "UIT", "WAR", "RGT":
			return true
		}
	}
	return false
}
