// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

// ErrorStatus - The HTTP status code .
type ErrorStatus string

const (
	ErrorStatusFourHundred        ErrorStatus = "400"
	ErrorStatusFourHundredAndOne  ErrorStatus = "401"
	ErrorStatusFourHundredAndFour ErrorStatus = "404"
	ErrorStatusFiveHundred        ErrorStatus = "500"
)

func (e ErrorStatus) ToPointer() *ErrorStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ErrorStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "400", "401", "404", "500":
			return true
		}
	}
	return false
}

type Error struct {
	// Unique error id.
	ID *string `json:"id,omitzero"`
	// The HTTP status code .
	Status *ErrorStatus `json:"status,omitzero"`
	// Short error description.
	Title *string `json:"title,omitzero"`
	// Detailed error description.
	Detail *string `json:"detail,omitzero"`
	// Who is responsible for triggering these errors.
	Source *ErrorSource `json:"source,omitzero"`
}

func (e Error) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Error) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *Error) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *Error) GetStatus() *ErrorStatus {
	if e == nil {
		return nil
	}
	return e.Status
}

func (e *Error) GetTitle() *string {
	if e == nil {
		return nil
	}
	return e.Title
}

func (e *Error) GetDetail() *string {
	if e == nil {
		return nil
	}
	return e.Detail
}

func (e *Error) GetSource() *ErrorSource {
	if e == nil {
		return nil
	}
	return e.Source
}
