// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

// ErrorSource - Who is responsible for triggering these errors.
type ErrorSource struct {
	// list of attributes which lead to this error message.
	Pointer []string `json:"pointer,omitzero"`
	// parameter name which lead to this error message.
	Parameter *string `json:"parameter,omitzero"`
	// header name which lead to this error message.
	Header *string `json:"header,omitzero"`
}

func (e ErrorSource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ErrorSource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ErrorSource) GetPointer() []string {
	if e == nil {
		return nil
	}
	return e.Pointer
}

func (e *ErrorSource) GetParameter() *string {
	if e == nil {
		return nil
	}
	return e.Parameter
}

func (e *ErrorSource) GetHeader() *string {
	if e == nil {
		return nil
	}
	return e.Header
}
