// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"time"
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type ExecutionLeg struct {
	LegID             *int64     `json:"legId,omitzero"`
	Price             *float64   `json:"price,omitzero"`
	Quantity          *float64   `json:"quantity,omitzero"`
	MismarkedQuantity *float64   `json:"mismarkedQuantity,omitzero"`
	InstrumentID      *int64     `json:"instrumentId,omitzero"`
	Time              *time.Time `json:"time,omitzero"`
}

func (e ExecutionLeg) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExecutionLeg) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExecutionLeg) GetLegID() *int64 {
	if e == nil {
		return nil
	}
	return e.LegID
}

func (e *ExecutionLeg) GetPrice() *float64 {
	if e == nil {
		return nil
	}
	return e.Price
}

func (e *ExecutionLeg) GetQuantity() *float64 {
	if e == nil {
		return nil
	}
	return e.Quantity
}

func (e *ExecutionLeg) GetMismarkedQuantity() *float64 {
	if e == nil {
		return nil
	}
	return e.MismarkedQuantity
}

func (e *ExecutionLeg) GetInstrumentID() *int64 {
	if e == nil {
		return nil
	}
	return e.InstrumentID
}

func (e *ExecutionLeg) GetTime() *time.Time {
	if e == nil {
		return nil
	}
	return e.Time
}
