// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ExerciseType - option contract exercise type America or European
type ExerciseType string

const (
	ExerciseTypeA ExerciseType = "A"
	ExerciseTypeE ExerciseType = "E"
)

func (e ExerciseType) ToPointer() *ExerciseType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ExerciseType) IsExact() bool {
	if e != nil {
		switch *e {
		case "A", "E":
			return true
		}
	}
	return false
}
