// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Expiration - expiration type
type Expiration struct {
	DaysToExpiration *int    `json:"daysToExpiration,omitzero"`
	Expiration       *string `json:"expiration,omitzero"`
	// M for End Of Month Expiration Calendar Cycle. (To match the last business day of the month), Q for Quarterly expirations (last business day of the quarter month MAR/JUN/SEP/DEC), W for Weekly expiration (also called Friday Short Term Expirations) and S for Expires 3rd Friday of the month (also known as regular options).
	ExpirationType *ExpirationType `json:"expirationType,omitzero"`
	Standard       *bool           `json:"standard,omitzero"`
	// option contract settlement type AM or PM
	SettlementType *SettlementType `json:"settlementType,omitzero"`
	OptionRoots    *string         `json:"optionRoots,omitzero"`
}

func (e *Expiration) GetDaysToExpiration() *int {
	if e == nil {
		return nil
	}
	return e.DaysToExpiration
}

func (e *Expiration) GetExpiration() *string {
	if e == nil {
		return nil
	}
	return e.Expiration
}

func (e *Expiration) GetExpirationType() *ExpirationType {
	if e == nil {
		return nil
	}
	return e.ExpirationType
}

func (e *Expiration) GetStandard() *bool {
	if e == nil {
		return nil
	}
	return e.Standard
}

func (e *Expiration) GetSettlementType() *SettlementType {
	if e == nil {
		return nil
	}
	return e.SettlementType
}

func (e *Expiration) GetOptionRoots() *string {
	if e == nil {
		return nil
	}
	return e.OptionRoots
}
