// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ExpirationType - M for End Of Month Expiration Calendar Cycle. (To match the last business day of the month), Q for Quarterly expirations (last business day of the quarter month MAR/JUN/SEP/DEC), W for Weekly expiration (also called Friday Short Term Expirations) and S for Expires 3rd Friday of the month (also known as regular options).
type ExpirationType string

const (
	ExpirationTypeM ExpirationType = "M"
	ExpirationTypeQ ExpirationType = "Q"
	ExpirationTypeS ExpirationType = "S"
	ExpirationTypeW ExpirationType = "W"
)

func (e ExpirationType) ToPointer() *ExpirationType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ExpirationType) IsExact() bool {
	if e != nil {
		switch *e {
		case "M", "Q", "S", "W":
			return true
		}
	}
	return false
}
