// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type ExpirationChain struct {
	Status         *string      `json:"status,omitzero"`
	ExpirationList []Expiration `json:"expirationList,omitzero"`
}

func (e ExpirationChain) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExpirationChain) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExpirationChain) GetStatus() *string {
	if e == nil {
		return nil
	}
	return e.Status
}

func (e *ExpirationChain) GetExpirationList() []Expiration {
	if e == nil {
		return nil
	}
	return e.ExpirationList
}
