// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

// ExtendedMarket - Quote data for extended hours
type ExtendedMarket struct {
	// Extended market ask price
	AskPrice *float64 `json:"askPrice,omitzero"`
	// Extended market ask size
	AskSize *int `json:"askSize,omitzero"`
	// Extended market bid price
	BidPrice *float64 `json:"bidPrice,omitzero"`
	// Extended market bid size
	BidSize *int `json:"bidSize,omitzero"`
	// Extended market last price
	LastPrice *float64 `json:"lastPrice,omitzero"`
	// Regular market last size
	LastSize *int `json:"lastSize,omitzero"`
	// mark price
	Mark *float64 `json:"mark,omitzero"`
	// Extended market quote time in milliseconds since Epoch
	QuoteTime *int64 `json:"quoteTime,omitzero"`
	// Total volume
	TotalVolume *float64 `json:"totalVolume,omitzero"`
	// Extended market trade time in milliseconds since Epoch
	TradeTime *int64 `json:"tradeTime,omitzero"`
}

func (e ExtendedMarket) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExtendedMarket) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExtendedMarket) GetAskPrice() *float64 {
	if e == nil {
		return nil
	}
	return e.AskPrice
}

func (e *ExtendedMarket) GetAskSize() *int {
	if e == nil {
		return nil
	}
	return e.AskSize
}

func (e *ExtendedMarket) GetBidPrice() *float64 {
	if e == nil {
		return nil
	}
	return e.BidPrice
}

func (e *ExtendedMarket) GetBidSize() *int {
	if e == nil {
		return nil
	}
	return e.BidSize
}

func (e *ExtendedMarket) GetLastPrice() *float64 {
	if e == nil {
		return nil
	}
	return e.LastPrice
}

func (e *ExtendedMarket) GetLastSize() *int {
	if e == nil {
		return nil
	}
	return e.LastSize
}

func (e *ExtendedMarket) GetMark() *float64 {
	if e == nil {
		return nil
	}
	return e.Mark
}

func (e *ExtendedMarket) GetQuoteTime() *int64 {
	if e == nil {
		return nil
	}
	return e.QuoteTime
}

func (e *ExtendedMarket) GetTotalVolume() *float64 {
	if e == nil {
		return nil
	}
	return e.TotalVolume
}

func (e *ExtendedMarket) GetTradeTime() *int64 {
	if e == nil {
		return nil
	}
	return e.TradeTime
}
