// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

type FeeLeg struct {
	FeeValues []FeeValue `json:"feeValues,omitzero"`
}

func (f FeeLeg) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FeeLeg) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FeeLeg) GetFeeValues() []FeeValue {
	if f == nil {
		return nil
	}
	return f.FeeValues
}
