// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type Fees struct {
	FeeLegs []FeeLeg `json:"feeLegs,omitzero"`
}

func (f Fees) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *Fees) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *Fees) GetFeeLegs() []FeeLeg {
	if f == nil {
		return nil
	}
	return f.FeeLegs
}
