// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FeeType string

const (
	FeeTypeCommission             FeeType = "COMMISSION"
	FeeTypeSecFee                 FeeType = "SEC_FEE"
	FeeTypeStrFee                 FeeType = "STR_FEE"
	FeeTypeRFee                   FeeType = "R_FEE"
	FeeTypeCdscFee                FeeType = "CDSC_FEE"
	FeeTypeOptRegFee              FeeType = "OPT_REG_FEE"
	FeeTypeAdditionalFee          FeeType = "ADDITIONAL_FEE"
	FeeTypeMiscellaneousFee       FeeType = "MISCELLANEOUS_FEE"
	FeeTypeFtt                    FeeType = "FTT"
	FeeTypeFuturesClearingFee     FeeType = "FUTURES_CLEARING_FEE"
	FeeTypeFuturesDeskOfficeFee   FeeType = "FUTURES_DESK_OFFICE_FEE"
	FeeTypeFuturesExchangeFee     FeeType = "FUTURES_EXCHANGE_FEE"
	FeeTypeFuturesGlobexFee       FeeType = "FUTURES_GLOBEX_FEE"
	FeeTypeFuturesNfaFee          FeeType = "FUTURES_NFA_FEE"
	FeeTypeFuturesPitBrokerageFee FeeType = "FUTURES_PIT_BROKERAGE_FEE"
	FeeTypeFuturesTransactionFee  FeeType = "FUTURES_TRANSACTION_FEE"
	FeeTypeLowProceedsCommission  FeeType = "LOW_PROCEEDS_COMMISSION"
	FeeTypeBaseCharge             FeeType = "BASE_CHARGE"
	FeeTypeGeneralCharge          FeeType = "GENERAL_CHARGE"
	FeeTypeGstFee                 FeeType = "GST_FEE"
	FeeTypeTafFee                 FeeType = "TAF_FEE"
	FeeTypeIndexOptionFee         FeeType = "INDEX_OPTION_FEE"
	FeeTypeTefraTax               FeeType = "TEFRA_TAX"
	FeeTypeStateTax               FeeType = "STATE_TAX"
	FeeTypeUnknown                FeeType = "UNKNOWN"
)

func (e FeeType) ToPointer() *FeeType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *FeeType) IsExact() bool {
	if e != nil {
		switch *e {
		case "COMMISSION", "SEC_FEE", "STR_FEE", "R_FEE", "CDSC_FEE", "OPT_REG_FEE", "ADDITIONAL_FEE", "MISCELLANEOUS_FEE", "FTT", "FUTURES_CLEARING_FEE", "FUTURES_DESK_OFFICE_FEE", "FUTURES_EXCHANGE_FEE", "FUTURES_GLOBEX_FEE", "FUTURES_NFA_FEE", "FUTURES_PIT_BROKERAGE_FEE", "FUTURES_TRANSACTION_FEE", "LOW_PROCEEDS_COMMISSION", "BASE_CHARGE", "GENERAL_CHARGE", "GST_FEE", "TAF_FEE", "INDEX_OPTION_FEE", "TEFRA_TAX", "STATE_TAX", "UNKNOWN":
			return true
		}
	}
	return false
}
