// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FeeValue struct {
	Value *float64 `json:"value,omitzero"`
	Type  *FeeType `json:"type,omitzero"`
}

func (f *FeeValue) GetValue() *float64 {
	if f == nil {
		return nil
	}
	return f.Value
}

func (f *FeeValue) GetType() *FeeType {
	if f == nil {
		return nil
	}
	return f.Type
}
