// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type ForexAssetType string

const (
	ForexAssetTypeEquity               ForexAssetType = "EQUITY"
	ForexAssetTypeOption               ForexAssetType = "OPTION"
	ForexAssetTypeIndex                ForexAssetType = "INDEX"
	ForexAssetTypeMutualFund           ForexAssetType = "MUTUAL_FUND"
	ForexAssetTypeCashEquivalent       ForexAssetType = "CASH_EQUIVALENT"
	ForexAssetTypeFixedIncome          ForexAssetType = "FIXED_INCOME"
	ForexAssetTypeCurrency             ForexAssetType = "CURRENCY"
	ForexAssetTypeCollectiveInvestment ForexAssetType = "COLLECTIVE_INVESTMENT"
)

func (e ForexAssetType) ToPointer() *ForexAssetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ForexAssetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EQUITY", "OPTION", "INDEX", "MUTUAL_FUND", "CASH_EQUIVALENT", "FIXED_INCOME", "CURRENCY", "COLLECTIVE_INVESTMENT":
			return true
		}
	}
	return false
}

type ForexType string

const (
	ForexTypeStandard ForexType = "STANDARD"
	ForexTypeNbbo     ForexType = "NBBO"
	ForexTypeUnknown  ForexType = "UNKNOWN"
)

func (e ForexType) ToPointer() *ForexType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ForexType) IsExact() bool {
	if e != nil {
		switch *e {
		case "STANDARD", "NBBO", "UNKNOWN":
			return true
		}
	}
	return false
}

type Forex struct {
	AssetType       ForexAssetType             `json:"assetType"`
	Cusip           *string                    `json:"cusip,omitzero"`
	Symbol          *string                    `json:"symbol,omitzero"`
	Description     *string                    `json:"description,omitzero"`
	InstrumentID    *int64                     `json:"instrumentId,omitzero"`
	NetChange       *float64                   `json:"netChange,omitzero"`
	Type            *ForexType                 `json:"type,omitzero"`
	BaseCurrency    *TransactionBaseInstrument `json:"baseCurrency,omitzero"`
	CounterCurrency *TransactionBaseInstrument `json:"counterCurrency,omitzero"`
}

func (f Forex) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *Forex) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *Forex) GetAssetType() ForexAssetType {
	if f == nil {
		return ForexAssetType("")
	}
	return f.AssetType
}

func (f *Forex) GetCusip() *string {
	if f == nil {
		return nil
	}
	return f.Cusip
}

func (f *Forex) GetSymbol() *string {
	if f == nil {
		return nil
	}
	return f.Symbol
}

func (f *Forex) GetDescription() *string {
	if f == nil {
		return nil
	}
	return f.Description
}

func (f *Forex) GetInstrumentID() *int64 {
	if f == nil {
		return nil
	}
	return f.InstrumentID
}

func (f *Forex) GetNetChange() *float64 {
	if f == nil {
		return nil
	}
	return f.NetChange
}

func (f *Forex) GetType() *ForexType {
	if f == nil {
		return nil
	}
	return f.Type
}

func (f *Forex) GetBaseCurrency() *TransactionBaseInstrument {
	if f == nil {
		return nil
	}
	return f.BaseCurrency
}

func (f *Forex) GetCounterCurrency() *TransactionBaseInstrument {
	if f == nil {
		return nil
	}
	return f.CounterCurrency
}
