// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

// ForexResponse - Quote info of Forex security
type ForexResponse struct {
	// Instrument's asset type
	AssetMainType *AssetMainType `json:"assetMainType,omitzero"`
	// SSID of instrument
	Ssid *int64 `json:"ssid,omitzero"`
	// Symbol of instrument
	Symbol *string `json:"symbol,omitzero"`
	// is quote realtime
	Realtime *bool `json:"realtime,omitzero"`
	// Quote data of Forex security
	Quote *QuoteForex `json:"quote,omitzero"`
	// Reference data of Forex security
	Reference *ReferenceForex `json:"reference,omitzero"`
}

func (f ForexResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *ForexResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *ForexResponse) GetAssetMainType() *AssetMainType {
	if f == nil {
		return nil
	}
	return f.AssetMainType
}

func (f *ForexResponse) GetSsid() *int64 {
	if f == nil {
		return nil
	}
	return f.Ssid
}

func (f *ForexResponse) GetSymbol() *string {
	if f == nil {
		return nil
	}
	return f.Symbol
}

func (f *ForexResponse) GetRealtime() *bool {
	if f == nil {
		return nil
	}
	return f.Realtime
}

func (f *ForexResponse) GetQuote() *QuoteForex {
	if f == nil {
		return nil
	}
	return f.Quote
}

func (f *ForexResponse) GetReference() *ReferenceForex {
	if f == nil {
		return nil
	}
	return f.Reference
}
