// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// FundStrategy "A" - Active "L" - Leveraged "P" - Passive "Q" - Quantitative "S" - Short
type FundStrategy string

const (
	FundStrategyA FundStrategy = "A"
	FundStrategyL FundStrategy = "L"
	FundStrategyP FundStrategy = "P"
	FundStrategyQ FundStrategy = "Q"
	FundStrategyS FundStrategy = "S"
)

func (e FundStrategy) ToPointer() *FundStrategy {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *FundStrategy) IsExact() bool {
	if e != nil {
		switch *e {
		case "A", "L", "P", "Q", "S":
			return true
		}
	}
	return false
}
