// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
	"github.com/Chalupa-Tech/go-schwab-api-individual/optionalnullable"
	"time"
)

// Fundamental - Fundamentals of a security
type Fundamental struct {
	// Average 10 day volume
	Avg10DaysVolume *float64 `json:"avg10DaysVolume,omitzero"`
	// Average 1 day volume
	Avg1YearVolume *float64 `json:"avg1YearVolume,omitzero"`
	// Declaration date in yyyy-mm-ddThh:mm:ssZ
	DeclarationDate *time.Time `json:"declarationDate,omitzero"`
	// Dividend Amount
	DivAmount *float64 `json:"divAmount,omitzero"`
	// Dividend date in yyyy-mm-ddThh:mm:ssZ
	DivExDate *string `json:"divExDate,omitzero"`
	// Dividend frequency 1 – once a year or annually 2 – 2x a year or semi-annualy 3 - 3x a year (ex. ARCO, EBRPF) 4 – 4x a year or quarterly 6 - 6x per yr or every other month 11 – 11x a year (ex. FBND, FCOR) 12 – 12x a year or monthly
	DivFreq optionalnullable.OptionalNullable[DivFreq] `json:"divFreq,omitzero"`
	// Dividend Pay Amount
	DivPayAmount *float64 `json:"divPayAmount,omitzero"`
	// Dividend pay date in yyyy-mm-ddThh:mm:ssZ
	DivPayDate *time.Time `json:"divPayDate,omitzero"`
	// Dividend yield
	DivYield *float64 `json:"divYield,omitzero"`
	// Earnings per Share
	Eps *float64 `json:"eps,omitzero"`
	// Fund Leverage Factor + > 0 <-
	FundLeverageFactor *float64 `json:"fundLeverageFactor,omitzero"`
	// FundStrategy "A" - Active "L" - Leveraged "P" - Passive "Q" - Quantitative "S" - Short
	FundStrategy optionalnullable.OptionalNullable[FundStrategy] `json:"fundStrategy,omitzero"`
	// Next Dividend date
	NextDivExDate *time.Time `json:"nextDivExDate,omitzero"`
	// Next Dividend pay date
	NextDivPayDate *time.Time `json:"nextDivPayDate,omitzero"`
	// P/E Ratio
	PeRatio *float64 `json:"peRatio,omitzero"`
}

func (f Fundamental) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *Fundamental) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *Fundamental) GetAvg10DaysVolume() *float64 {
	if f == nil {
		return nil
	}
	return f.Avg10DaysVolume
}

func (f *Fundamental) GetAvg1YearVolume() *float64 {
	if f == nil {
		return nil
	}
	return f.Avg1YearVolume
}

func (f *Fundamental) GetDeclarationDate() *time.Time {
	if f == nil {
		return nil
	}
	return f.DeclarationDate
}

func (f *Fundamental) GetDivAmount() *float64 {
	if f == nil {
		return nil
	}
	return f.DivAmount
}

func (f *Fundamental) GetDivExDate() *string {
	if f == nil {
		return nil
	}
	return f.DivExDate
}

func (f *Fundamental) GetDivFreq() optionalnullable.OptionalNullable[DivFreq] {
	if f == nil {
		return nil
	}
	return f.DivFreq
}

func (f *Fundamental) GetDivPayAmount() *float64 {
	if f == nil {
		return nil
	}
	return f.DivPayAmount
}

func (f *Fundamental) GetDivPayDate() *time.Time {
	if f == nil {
		return nil
	}
	return f.DivPayDate
}

func (f *Fundamental) GetDivYield() *float64 {
	if f == nil {
		return nil
	}
	return f.DivYield
}

func (f *Fundamental) GetEps() *float64 {
	if f == nil {
		return nil
	}
	return f.Eps
}

func (f *Fundamental) GetFundLeverageFactor() *float64 {
	if f == nil {
		return nil
	}
	return f.FundLeverageFactor
}

func (f *Fundamental) GetFundStrategy() optionalnullable.OptionalNullable[FundStrategy] {
	if f == nil {
		return nil
	}
	return f.FundStrategy
}

func (f *Fundamental) GetNextDivExDate() *time.Time {
	if f == nil {
		return nil
	}
	return f.NextDivExDate
}

func (f *Fundamental) GetNextDivPayDate() *time.Time {
	if f == nil {
		return nil
	}
	return f.NextDivPayDate
}

func (f *Fundamental) GetPeRatio() *float64 {
	if f == nil {
		return nil
	}
	return f.PeRatio
}
