// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FundamentalInst struct {
	Symbol              *string  `json:"symbol,omitzero"`
	High52              *float64 `json:"high52,omitzero"`
	Low52               *float64 `json:"low52,omitzero"`
	DividendAmount      *float64 `json:"dividendAmount,omitzero"`
	DividendYield       *float64 `json:"dividendYield,omitzero"`
	DividendDate        *string  `json:"dividendDate,omitzero"`
	PeRatio             *float64 `json:"peRatio,omitzero"`
	PegRatio            *float64 `json:"pegRatio,omitzero"`
	PbRatio             *float64 `json:"pbRatio,omitzero"`
	PrRatio             *float64 `json:"prRatio,omitzero"`
	PcfRatio            *float64 `json:"pcfRatio,omitzero"`
	GrossMarginTTM      *float64 `json:"grossMarginTTM,omitzero"`
	GrossMarginMRQ      *float64 `json:"grossMarginMRQ,omitzero"`
	NetProfitMarginTTM  *float64 `json:"netProfitMarginTTM,omitzero"`
	NetProfitMarginMRQ  *float64 `json:"netProfitMarginMRQ,omitzero"`
	OperatingMarginTTM  *float64 `json:"operatingMarginTTM,omitzero"`
	OperatingMarginMRQ  *float64 `json:"operatingMarginMRQ,omitzero"`
	ReturnOnEquity      *float64 `json:"returnOnEquity,omitzero"`
	ReturnOnAssets      *float64 `json:"returnOnAssets,omitzero"`
	ReturnOnInvestment  *float64 `json:"returnOnInvestment,omitzero"`
	QuickRatio          *float64 `json:"quickRatio,omitzero"`
	CurrentRatio        *float64 `json:"currentRatio,omitzero"`
	InterestCoverage    *float64 `json:"interestCoverage,omitzero"`
	TotalDebtToCapital  *float64 `json:"totalDebtToCapital,omitzero"`
	LtDebtToEquity      *float64 `json:"ltDebtToEquity,omitzero"`
	TotalDebtToEquity   *float64 `json:"totalDebtToEquity,omitzero"`
	EpsTTM              *float64 `json:"epsTTM,omitzero"`
	EpsChangePercentTTM *float64 `json:"epsChangePercentTTM,omitzero"`
	EpsChangeYear       *float64 `json:"epsChangeYear,omitzero"`
	EpsChange           *float64 `json:"epsChange,omitzero"`
	RevChangeYear       *float64 `json:"revChangeYear,omitzero"`
	RevChangeTTM        *float64 `json:"revChangeTTM,omitzero"`
	RevChangeIn         *float64 `json:"revChangeIn,omitzero"`
	SharesOutstanding   *float64 `json:"sharesOutstanding,omitzero"`
	MarketCapFloat      *float64 `json:"marketCapFloat,omitzero"`
	MarketCap           *float64 `json:"marketCap,omitzero"`
	BookValuePerShare   *float64 `json:"bookValuePerShare,omitzero"`
	ShortIntToFloat     *float64 `json:"shortIntToFloat,omitzero"`
	ShortIntDayToCover  *float64 `json:"shortIntDayToCover,omitzero"`
	DivGrowthRate3Year  *float64 `json:"divGrowthRate3Year,omitzero"`
	DividendPayAmount   *float64 `json:"dividendPayAmount,omitzero"`
	DividendPayDate     *string  `json:"dividendPayDate,omitzero"`
	Beta                *float64 `json:"beta,omitzero"`
	Vol1DayAvg          *float64 `json:"vol1DayAvg,omitzero"`
	Vol10DayAvg         *float64 `json:"vol10DayAvg,omitzero"`
	Vol3MonthAvg        *float64 `json:"vol3MonthAvg,omitzero"`
	Avg10DaysVolume     *int64   `json:"avg10DaysVolume,omitzero"`
	Avg1DayVolume       *int64   `json:"avg1DayVolume,omitzero"`
	Avg3MonthVolume     *int64   `json:"avg3MonthVolume,omitzero"`
	DeclarationDate     *string  `json:"declarationDate,omitzero"`
	DividendFreq        *int     `json:"dividendFreq,omitzero"`
	Eps                 *float64 `json:"eps,omitzero"`
	CorpactionDate      *string  `json:"corpactionDate,omitzero"`
	DtnVolume           *int64   `json:"dtnVolume,omitzero"`
	NextDividendPayDate *string  `json:"nextDividendPayDate,omitzero"`
	NextDividendDate    *string  `json:"nextDividendDate,omitzero"`
	FundLeverageFactor  *float64 `json:"fundLeverageFactor,omitzero"`
	FundStrategy        *string  `json:"fundStrategy,omitzero"`
}

func (f *FundamentalInst) GetSymbol() *string {
	if f == nil {
		return nil
	}
	return f.Symbol
}

func (f *FundamentalInst) GetHigh52() *float64 {
	if f == nil {
		return nil
	}
	return f.High52
}

func (f *FundamentalInst) GetLow52() *float64 {
	if f == nil {
		return nil
	}
	return f.Low52
}

func (f *FundamentalInst) GetDividendAmount() *float64 {
	if f == nil {
		return nil
	}
	return f.DividendAmount
}

func (f *FundamentalInst) GetDividendYield() *float64 {
	if f == nil {
		return nil
	}
	return f.DividendYield
}

func (f *FundamentalInst) GetDividendDate() *string {
	if f == nil {
		return nil
	}
	return f.DividendDate
}

func (f *FundamentalInst) GetPeRatio() *float64 {
	if f == nil {
		return nil
	}
	return f.PeRatio
}

func (f *FundamentalInst) GetPegRatio() *float64 {
	if f == nil {
		return nil
	}
	return f.PegRatio
}

func (f *FundamentalInst) GetPbRatio() *float64 {
	if f == nil {
		return nil
	}
	return f.PbRatio
}

func (f *FundamentalInst) GetPrRatio() *float64 {
	if f == nil {
		return nil
	}
	return f.PrRatio
}

func (f *FundamentalInst) GetPcfRatio() *float64 {
	if f == nil {
		return nil
	}
	return f.PcfRatio
}

func (f *FundamentalInst) GetGrossMarginTTM() *float64 {
	if f == nil {
		return nil
	}
	return f.GrossMarginTTM
}

func (f *FundamentalInst) GetGrossMarginMRQ() *float64 {
	if f == nil {
		return nil
	}
	return f.GrossMarginMRQ
}

func (f *FundamentalInst) GetNetProfitMarginTTM() *float64 {
	if f == nil {
		return nil
	}
	return f.NetProfitMarginTTM
}

func (f *FundamentalInst) GetNetProfitMarginMRQ() *float64 {
	if f == nil {
		return nil
	}
	return f.NetProfitMarginMRQ
}

func (f *FundamentalInst) GetOperatingMarginTTM() *float64 {
	if f == nil {
		return nil
	}
	return f.OperatingMarginTTM
}

func (f *FundamentalInst) GetOperatingMarginMRQ() *float64 {
	if f == nil {
		return nil
	}
	return f.OperatingMarginMRQ
}

func (f *FundamentalInst) GetReturnOnEquity() *float64 {
	if f == nil {
		return nil
	}
	return f.ReturnOnEquity
}

func (f *FundamentalInst) GetReturnOnAssets() *float64 {
	if f == nil {
		return nil
	}
	return f.ReturnOnAssets
}

func (f *FundamentalInst) GetReturnOnInvestment() *float64 {
	if f == nil {
		return nil
	}
	return f.ReturnOnInvestment
}

func (f *FundamentalInst) GetQuickRatio() *float64 {
	if f == nil {
		return nil
	}
	return f.QuickRatio
}

func (f *FundamentalInst) GetCurrentRatio() *float64 {
	if f == nil {
		return nil
	}
	return f.CurrentRatio
}

func (f *FundamentalInst) GetInterestCoverage() *float64 {
	if f == nil {
		return nil
	}
	return f.InterestCoverage
}

func (f *FundamentalInst) GetTotalDebtToCapital() *float64 {
	if f == nil {
		return nil
	}
	return f.TotalDebtToCapital
}

func (f *FundamentalInst) GetLtDebtToEquity() *float64 {
	if f == nil {
		return nil
	}
	return f.LtDebtToEquity
}

func (f *FundamentalInst) GetTotalDebtToEquity() *float64 {
	if f == nil {
		return nil
	}
	return f.TotalDebtToEquity
}

func (f *FundamentalInst) GetEpsTTM() *float64 {
	if f == nil {
		return nil
	}
	return f.EpsTTM
}

func (f *FundamentalInst) GetEpsChangePercentTTM() *float64 {
	if f == nil {
		return nil
	}
	return f.EpsChangePercentTTM
}

func (f *FundamentalInst) GetEpsChangeYear() *float64 {
	if f == nil {
		return nil
	}
	return f.EpsChangeYear
}

func (f *FundamentalInst) GetEpsChange() *float64 {
	if f == nil {
		return nil
	}
	return f.EpsChange
}

func (f *FundamentalInst) GetRevChangeYear() *float64 {
	if f == nil {
		return nil
	}
	return f.RevChangeYear
}

func (f *FundamentalInst) GetRevChangeTTM() *float64 {
	if f == nil {
		return nil
	}
	return f.RevChangeTTM
}

func (f *FundamentalInst) GetRevChangeIn() *float64 {
	if f == nil {
		return nil
	}
	return f.RevChangeIn
}

func (f *FundamentalInst) GetSharesOutstanding() *float64 {
	if f == nil {
		return nil
	}
	return f.SharesOutstanding
}

func (f *FundamentalInst) GetMarketCapFloat() *float64 {
	if f == nil {
		return nil
	}
	return f.MarketCapFloat
}

func (f *FundamentalInst) GetMarketCap() *float64 {
	if f == nil {
		return nil
	}
	return f.MarketCap
}

func (f *FundamentalInst) GetBookValuePerShare() *float64 {
	if f == nil {
		return nil
	}
	return f.BookValuePerShare
}

func (f *FundamentalInst) GetShortIntToFloat() *float64 {
	if f == nil {
		return nil
	}
	return f.ShortIntToFloat
}

func (f *FundamentalInst) GetShortIntDayToCover() *float64 {
	if f == nil {
		return nil
	}
	return f.ShortIntDayToCover
}

func (f *FundamentalInst) GetDivGrowthRate3Year() *float64 {
	if f == nil {
		return nil
	}
	return f.DivGrowthRate3Year
}

func (f *FundamentalInst) GetDividendPayAmount() *float64 {
	if f == nil {
		return nil
	}
	return f.DividendPayAmount
}

func (f *FundamentalInst) GetDividendPayDate() *string {
	if f == nil {
		return nil
	}
	return f.DividendPayDate
}

func (f *FundamentalInst) GetBeta() *float64 {
	if f == nil {
		return nil
	}
	return f.Beta
}

func (f *FundamentalInst) GetVol1DayAvg() *float64 {
	if f == nil {
		return nil
	}
	return f.Vol1DayAvg
}

func (f *FundamentalInst) GetVol10DayAvg() *float64 {
	if f == nil {
		return nil
	}
	return f.Vol10DayAvg
}

func (f *FundamentalInst) GetVol3MonthAvg() *float64 {
	if f == nil {
		return nil
	}
	return f.Vol3MonthAvg
}

func (f *FundamentalInst) GetAvg10DaysVolume() *int64 {
	if f == nil {
		return nil
	}
	return f.Avg10DaysVolume
}

func (f *FundamentalInst) GetAvg1DayVolume() *int64 {
	if f == nil {
		return nil
	}
	return f.Avg1DayVolume
}

func (f *FundamentalInst) GetAvg3MonthVolume() *int64 {
	if f == nil {
		return nil
	}
	return f.Avg3MonthVolume
}

func (f *FundamentalInst) GetDeclarationDate() *string {
	if f == nil {
		return nil
	}
	return f.DeclarationDate
}

func (f *FundamentalInst) GetDividendFreq() *int {
	if f == nil {
		return nil
	}
	return f.DividendFreq
}

func (f *FundamentalInst) GetEps() *float64 {
	if f == nil {
		return nil
	}
	return f.Eps
}

func (f *FundamentalInst) GetCorpactionDate() *string {
	if f == nil {
		return nil
	}
	return f.CorpactionDate
}

func (f *FundamentalInst) GetDtnVolume() *int64 {
	if f == nil {
		return nil
	}
	return f.DtnVolume
}

func (f *FundamentalInst) GetNextDividendPayDate() *string {
	if f == nil {
		return nil
	}
	return f.NextDividendPayDate
}

func (f *FundamentalInst) GetNextDividendDate() *string {
	if f == nil {
		return nil
	}
	return f.NextDividendDate
}

func (f *FundamentalInst) GetFundLeverageFactor() *float64 {
	if f == nil {
		return nil
	}
	return f.FundLeverageFactor
}

func (f *FundamentalInst) GetFundStrategy() *string {
	if f == nil {
		return nil
	}
	return f.FundStrategy
}
