// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
	"time"
)

type FutureType string

const (
	FutureTypeStandard FutureType = "STANDARD"
	FutureTypeUnknown  FutureType = "UNKNOWN"
)

func (e FutureType) ToPointer() *FutureType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *FutureType) IsExact() bool {
	if e != nil {
		switch *e {
		case "STANDARD", "UNKNOWN":
			return true
		}
	}
	return false
}

type Future struct {
	ActiveContract  *bool       `default:"false" json:"activeContract"`
	Type            *FutureType `json:"type,omitzero"`
	ExpirationDate  *time.Time  `json:"expirationDate,omitzero"`
	LastTradingDate *time.Time  `json:"lastTradingDate,omitzero"`
	FirstNoticeDate *time.Time  `json:"firstNoticeDate,omitzero"`
	Multiplier      *float64    `json:"multiplier,omitzero"`
}

func (f Future) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *Future) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *Future) GetActiveContract() *bool {
	if f == nil {
		return nil
	}
	return f.ActiveContract
}

func (f *Future) GetType() *FutureType {
	if f == nil {
		return nil
	}
	return f.Type
}

func (f *Future) GetExpirationDate() *time.Time {
	if f == nil {
		return nil
	}
	return f.ExpirationDate
}

func (f *Future) GetLastTradingDate() *time.Time {
	if f == nil {
		return nil
	}
	return f.LastTradingDate
}

func (f *Future) GetFirstNoticeDate() *time.Time {
	if f == nil {
		return nil
	}
	return f.FirstNoticeDate
}

func (f *Future) GetMultiplier() *float64 {
	if f == nil {
		return nil
	}
	return f.Multiplier
}
