// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

// FutureResponse - Quote info of Future security
type FutureResponse struct {
	// Instrument's asset type
	AssetMainType *AssetMainType `json:"assetMainType,omitzero"`
	// SSID of instrument
	Ssid *int64 `json:"ssid,omitzero"`
	// Symbol of instrument
	Symbol *string `json:"symbol,omitzero"`
	// is quote realtime
	Realtime *bool `json:"realtime,omitzero"`
	// Quote data of Future security
	Quote *QuoteFuture `json:"quote,omitzero"`
	// Reference data of Future security
	Reference *ReferenceFuture `json:"reference,omitzero"`
}

func (f FutureResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FutureResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FutureResponse) GetAssetMainType() *AssetMainType {
	if f == nil {
		return nil
	}
	return f.AssetMainType
}

func (f *FutureResponse) GetSsid() *int64 {
	if f == nil {
		return nil
	}
	return f.Ssid
}

func (f *FutureResponse) GetSymbol() *string {
	if f == nil {
		return nil
	}
	return f.Symbol
}

func (f *FutureResponse) GetRealtime() *bool {
	if f == nil {
		return nil
	}
	return f.Realtime
}

func (f *FutureResponse) GetQuote() *QuoteFuture {
	if f == nil {
		return nil
	}
	return f.Quote
}

func (f *FutureResponse) GetReference() *ReferenceFuture {
	if f == nil {
		return nil
	}
	return f.Reference
}
