// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

// FutureOptionResponse - Quote info of Future Option security
type FutureOptionResponse struct {
	// Instrument's asset type
	AssetMainType *AssetMainType `json:"assetMainType,omitzero"`
	// SSID of instrument
	Ssid *int64 `json:"ssid,omitzero"`
	// Symbol of instrument
	Symbol *string `json:"symbol,omitzero"`
	// is quote realtime
	Realtime *bool `json:"realtime,omitzero"`
	// Quote data of Option security
	Quote *QuoteFutureOption `json:"quote,omitzero"`
	// Reference data of Future Option security
	Reference *ReferenceFutureOption `json:"reference,omitzero"`
}

func (f FutureOptionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FutureOptionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FutureOptionResponse) GetAssetMainType() *AssetMainType {
	if f == nil {
		return nil
	}
	return f.AssetMainType
}

func (f *FutureOptionResponse) GetSsid() *int64 {
	if f == nil {
		return nil
	}
	return f.Ssid
}

func (f *FutureOptionResponse) GetSymbol() *string {
	if f == nil {
		return nil
	}
	return f.Symbol
}

func (f *FutureOptionResponse) GetRealtime() *bool {
	if f == nil {
		return nil
	}
	return f.Realtime
}

func (f *FutureOptionResponse) GetQuote() *QuoteFutureOption {
	if f == nil {
		return nil
	}
	return f.Quote
}

func (f *FutureOptionResponse) GetReference() *ReferenceFutureOption {
	if f == nil {
		return nil
	}
	return f.Reference
}
