// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

type MarketType string

const (
	MarketTypeBond         MarketType = "BOND"
	MarketTypeEquity       MarketType = "EQUITY"
	MarketTypeEtf          MarketType = "ETF"
	MarketTypeExtended     MarketType = "EXTENDED"
	MarketTypeForex        MarketType = "FOREX"
	MarketTypeFuture       MarketType = "FUTURE"
	MarketTypeFutureOption MarketType = "FUTURE_OPTION"
	MarketTypeFundamental  MarketType = "FUNDAMENTAL"
	MarketTypeIndex        MarketType = "INDEX"
	MarketTypeIndicator    MarketType = "INDICATOR"
	MarketTypeMutualFund   MarketType = "MUTUAL_FUND"
	MarketTypeOption       MarketType = "OPTION"
	MarketTypeUnknown      MarketType = "UNKNOWN"
)

func (e MarketType) ToPointer() *MarketType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *MarketType) IsExact() bool {
	if e != nil {
		switch *e {
		case "BOND", "EQUITY", "ETF", "EXTENDED", "FOREX", "FUTURE", "FUTURE_OPTION", "FUNDAMENTAL", "INDEX", "INDICATOR", "MUTUAL_FUND", "OPTION", "UNKNOWN":
			return true
		}
	}
	return false
}

type Hours struct {
	Date         *string               `json:"date,omitzero"`
	MarketType   *MarketType           `json:"marketType,omitzero"`
	Exchange     *string               `json:"exchange,omitzero"`
	Category     *string               `json:"category,omitzero"`
	Product      *string               `json:"product,omitzero"`
	ProductName  *string               `json:"productName,omitzero"`
	IsOpen       *bool                 `json:"isOpen,omitzero"`
	SessionHours map[string][]Interval `json:"sessionHours,omitzero"`
}

func (h Hours) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *Hours) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *Hours) GetDate() *string {
	if h == nil {
		return nil
	}
	return h.Date
}

func (h *Hours) GetMarketType() *MarketType {
	if h == nil {
		return nil
	}
	return h.MarketType
}

func (h *Hours) GetExchange() *string {
	if h == nil {
		return nil
	}
	return h.Exchange
}

func (h *Hours) GetCategory() *string {
	if h == nil {
		return nil
	}
	return h.Category
}

func (h *Hours) GetProduct() *string {
	if h == nil {
		return nil
	}
	return h.Product
}

func (h *Hours) GetProductName() *string {
	if h == nil {
		return nil
	}
	return h.ProductName
}

func (h *Hours) GetIsOpen() *bool {
	if h == nil {
		return nil
	}
	return h.IsOpen
}

func (h *Hours) GetSessionHours() map[string][]Interval {
	if h == nil {
		return nil
	}
	return h.SessionHours
}
