// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type IndexType string

const (
	IndexTypeBroadBased  IndexType = "BROAD_BASED"
	IndexTypeNarrowBased IndexType = "NARROW_BASED"
	IndexTypeUnknown     IndexType = "UNKNOWN"
)

func (e IndexType) ToPointer() *IndexType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *IndexType) IsExact() bool {
	if e != nil {
		switch *e {
		case "BROAD_BASED", "NARROW_BASED", "UNKNOWN":
			return true
		}
	}
	return false
}

type Index struct {
	ActiveContract *bool      `default:"false" json:"activeContract"`
	Type           *IndexType `json:"type,omitzero"`
}

func (i Index) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *Index) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *Index) GetActiveContract() *bool {
	if i == nil {
		return nil
	}
	return i.ActiveContract
}

func (i *Index) GetType() *IndexType {
	if i == nil {
		return nil
	}
	return i.Type
}
