// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

// IndexResponse - Quote info of Index security
type IndexResponse struct {
	// Instrument's asset type
	AssetMainType *AssetMainType `json:"assetMainType,omitzero"`
	// SSID of instrument
	Ssid *int64 `json:"ssid,omitzero"`
	// Symbol of instrument
	Symbol *string `json:"symbol,omitzero"`
	// is quote realtime
	Realtime *bool `json:"realtime,omitzero"`
	// Quote data of Index security
	Quote *QuoteIndex `json:"quote,omitzero"`
	// Reference data of Index security
	Reference *ReferenceIndex `json:"reference,omitzero"`
}

func (i IndexResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IndexResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *IndexResponse) GetAssetMainType() *AssetMainType {
	if i == nil {
		return nil
	}
	return i.AssetMainType
}

func (i *IndexResponse) GetSsid() *int64 {
	if i == nil {
		return nil
	}
	return i.Ssid
}

func (i *IndexResponse) GetSymbol() *string {
	if i == nil {
		return nil
	}
	return i.Symbol
}

func (i *IndexResponse) GetRealtime() *bool {
	if i == nil {
		return nil
	}
	return i.Realtime
}

func (i *IndexResponse) GetQuote() *QuoteIndex {
	if i == nil {
		return nil
	}
	return i.Quote
}

func (i *IndexResponse) GetReference() *ReferenceIndex {
	if i == nil {
		return nil
	}
	return i.Reference
}
