// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type IndexAssetType string

const (
	IndexAssetTypeEquity               IndexAssetType = "EQUITY"
	IndexAssetTypeOption               IndexAssetType = "OPTION"
	IndexAssetTypeIndex                IndexAssetType = "INDEX"
	IndexAssetTypeMutualFund           IndexAssetType = "MUTUAL_FUND"
	IndexAssetTypeCashEquivalent       IndexAssetType = "CASH_EQUIVALENT"
	IndexAssetTypeFixedIncome          IndexAssetType = "FIXED_INCOME"
	IndexAssetTypeCurrency             IndexAssetType = "CURRENCY"
	IndexAssetTypeCollectiveInvestment IndexAssetType = "COLLECTIVE_INVESTMENT"
)

func (e IndexAssetType) ToPointer() *IndexAssetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *IndexAssetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EQUITY", "OPTION", "INDEX", "MUTUAL_FUND", "CASH_EQUIVALENT", "FIXED_INCOME", "CURRENCY", "COLLECTIVE_INVESTMENT":
			return true
		}
	}
	return false
}

type IndexType string

const (
	IndexTypeBroadBased  IndexType = "BROAD_BASED"
	IndexTypeNarrowBased IndexType = "NARROW_BASED"
	IndexTypeUnknown     IndexType = "UNKNOWN"
)

func (e IndexType) ToPointer() *IndexType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *IndexType) IsExact() bool {
	if e != nil {
		switch *e {
		case "BROAD_BASED", "NARROW_BASED", "UNKNOWN":
			return true
		}
	}
	return false
}

type Index struct {
	AssetType      IndexAssetType `json:"assetType"`
	Cusip          *string        `json:"cusip,omitzero"`
	Symbol         *string        `json:"symbol,omitzero"`
	Description    *string        `json:"description,omitzero"`
	InstrumentID   *int64         `json:"instrumentId,omitzero"`
	NetChange      *float64       `json:"netChange,omitzero"`
	ActiveContract *bool          `default:"false" json:"activeContract"`
	Type           *IndexType     `json:"type,omitzero"`
}

func (i Index) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *Index) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *Index) GetAssetType() IndexAssetType {
	if i == nil {
		return IndexAssetType("")
	}
	return i.AssetType
}

func (i *Index) GetCusip() *string {
	if i == nil {
		return nil
	}
	return i.Cusip
}

func (i *Index) GetSymbol() *string {
	if i == nil {
		return nil
	}
	return i.Symbol
}

func (i *Index) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *Index) GetInstrumentID() *int64 {
	if i == nil {
		return nil
	}
	return i.InstrumentID
}

func (i *Index) GetNetChange() *float64 {
	if i == nil {
		return nil
	}
	return i.NetChange
}

func (i *Index) GetActiveContract() *bool {
	if i == nil {
		return nil
	}
	return i.ActiveContract
}

func (i *Index) GetType() *IndexType {
	if i == nil {
		return nil
	}
	return i.Type
}
