// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Instruction string

const (
	InstructionBuy             Instruction = "BUY"
	InstructionSell            Instruction = "SELL"
	InstructionBuyToCover      Instruction = "BUY_TO_COVER"
	InstructionSellShort       Instruction = "SELL_SHORT"
	InstructionBuyToOpen       Instruction = "BUY_TO_OPEN"
	InstructionBuyToClose      Instruction = "BUY_TO_CLOSE"
	InstructionSellToOpen      Instruction = "SELL_TO_OPEN"
	InstructionSellToClose     Instruction = "SELL_TO_CLOSE"
	InstructionExchange        Instruction = "EXCHANGE"
	InstructionSellShortExempt Instruction = "SELL_SHORT_EXEMPT"
)

func (e Instruction) ToPointer() *Instruction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Instruction) IsExact() bool {
	if e != nil {
		switch *e {
		case "BUY", "SELL", "BUY_TO_COVER", "SELL_SHORT", "BUY_TO_OPEN", "BUY_TO_CLOSE", "SELL_TO_OPEN", "SELL_TO_CLOSE", "EXCHANGE", "SELL_SHORT_EXEMPT":
			return true
		}
	}
	return false
}
