// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type InstrumentAssetType string

const (
	InstrumentAssetTypeBond         InstrumentAssetType = "BOND"
	InstrumentAssetTypeEquity       InstrumentAssetType = "EQUITY"
	InstrumentAssetTypeEtf          InstrumentAssetType = "ETF"
	InstrumentAssetTypeExtended     InstrumentAssetType = "EXTENDED"
	InstrumentAssetTypeForex        InstrumentAssetType = "FOREX"
	InstrumentAssetTypeFuture       InstrumentAssetType = "FUTURE"
	InstrumentAssetTypeFutureOption InstrumentAssetType = "FUTURE_OPTION"
	InstrumentAssetTypeFundamental  InstrumentAssetType = "FUNDAMENTAL"
	InstrumentAssetTypeIndex        InstrumentAssetType = "INDEX"
	InstrumentAssetTypeIndicator    InstrumentAssetType = "INDICATOR"
	InstrumentAssetTypeMutualFund   InstrumentAssetType = "MUTUAL_FUND"
	InstrumentAssetTypeOption       InstrumentAssetType = "OPTION"
	InstrumentAssetTypeUnknown      InstrumentAssetType = "UNKNOWN"
)

func (e InstrumentAssetType) ToPointer() *InstrumentAssetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *InstrumentAssetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "BOND", "EQUITY", "ETF", "EXTENDED", "FOREX", "FUTURE", "FUTURE_OPTION", "FUNDAMENTAL", "INDEX", "INDICATOR", "MUTUAL_FUND", "OPTION", "UNKNOWN":
			return true
		}
	}
	return false
}

type Instrument struct {
	Cusip       *string              `json:"cusip,omitzero"`
	Symbol      *string              `json:"symbol,omitzero"`
	Description *string              `json:"description,omitzero"`
	Exchange    *string              `json:"exchange,omitzero"`
	AssetType   *InstrumentAssetType `json:"assetType,omitzero"`
}

func (i *Instrument) GetCusip() *string {
	if i == nil {
		return nil
	}
	return i.Cusip
}

func (i *Instrument) GetSymbol() *string {
	if i == nil {
		return nil
	}
	return i.Symbol
}

func (i *Instrument) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *Instrument) GetExchange() *string {
	if i == nil {
		return nil
	}
	return i.Exchange
}

func (i *Instrument) GetAssetType() *InstrumentAssetType {
	if i == nil {
		return nil
	}
	return i.AssetType
}
