// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Interval struct {
	Start *string `json:"start,omitzero"`
	End   *string `json:"end,omitzero"`
}

func (i *Interval) GetStart() *string {
	if i == nil {
		return nil
	}
	return i.Start
}

func (i *Interval) GetEnd() *string {
	if i == nil {
		return nil
	}
	return i.End
}
