// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

type MarginBalance struct {
	AvailableFunds                   *float64 `json:"availableFunds,omitzero"`
	AvailableFundsNonMarginableTrade *float64 `json:"availableFundsNonMarginableTrade,omitzero"`
	BuyingPower                      *float64 `json:"buyingPower,omitzero"`
	BuyingPowerNonMarginableTrade    *float64 `json:"buyingPowerNonMarginableTrade,omitzero"`
	DayTradingBuyingPower            *float64 `json:"dayTradingBuyingPower,omitzero"`
	DayTradingBuyingPowerCall        *float64 `json:"dayTradingBuyingPowerCall,omitzero"`
	Equity                           *float64 `json:"equity,omitzero"`
	EquityPercentage                 *float64 `json:"equityPercentage,omitzero"`
	LongMarginValue                  *float64 `json:"longMarginValue,omitzero"`
	MaintenanceCall                  *float64 `json:"maintenanceCall,omitzero"`
	MaintenanceRequirement           *float64 `json:"maintenanceRequirement,omitzero"`
	MarginBalance                    *float64 `json:"marginBalance,omitzero"`
	RegTCall                         *float64 `json:"regTCall,omitzero"`
	ShortBalance                     *float64 `json:"shortBalance,omitzero"`
	ShortMarginValue                 *float64 `json:"shortMarginValue,omitzero"`
	Sma                              *float64 `json:"sma,omitzero"`
	IsInCall                         *float64 `json:"isInCall,omitzero"`
	StockBuyingPower                 *float64 `json:"stockBuyingPower,omitzero"`
	OptionBuyingPower                *float64 `json:"optionBuyingPower,omitzero"`
}

func (m MarginBalance) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MarginBalance) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MarginBalance) GetAvailableFunds() *float64 {
	if m == nil {
		return nil
	}
	return m.AvailableFunds
}

func (m *MarginBalance) GetAvailableFundsNonMarginableTrade() *float64 {
	if m == nil {
		return nil
	}
	return m.AvailableFundsNonMarginableTrade
}

func (m *MarginBalance) GetBuyingPower() *float64 {
	if m == nil {
		return nil
	}
	return m.BuyingPower
}

func (m *MarginBalance) GetBuyingPowerNonMarginableTrade() *float64 {
	if m == nil {
		return nil
	}
	return m.BuyingPowerNonMarginableTrade
}

func (m *MarginBalance) GetDayTradingBuyingPower() *float64 {
	if m == nil {
		return nil
	}
	return m.DayTradingBuyingPower
}

func (m *MarginBalance) GetDayTradingBuyingPowerCall() *float64 {
	if m == nil {
		return nil
	}
	return m.DayTradingBuyingPowerCall
}

func (m *MarginBalance) GetEquity() *float64 {
	if m == nil {
		return nil
	}
	return m.Equity
}

func (m *MarginBalance) GetEquityPercentage() *float64 {
	if m == nil {
		return nil
	}
	return m.EquityPercentage
}

func (m *MarginBalance) GetLongMarginValue() *float64 {
	if m == nil {
		return nil
	}
	return m.LongMarginValue
}

func (m *MarginBalance) GetMaintenanceCall() *float64 {
	if m == nil {
		return nil
	}
	return m.MaintenanceCall
}

func (m *MarginBalance) GetMaintenanceRequirement() *float64 {
	if m == nil {
		return nil
	}
	return m.MaintenanceRequirement
}

func (m *MarginBalance) GetMarginBalance() *float64 {
	if m == nil {
		return nil
	}
	return m.MarginBalance
}

func (m *MarginBalance) GetRegTCall() *float64 {
	if m == nil {
		return nil
	}
	return m.RegTCall
}

func (m *MarginBalance) GetShortBalance() *float64 {
	if m == nil {
		return nil
	}
	return m.ShortBalance
}

func (m *MarginBalance) GetShortMarginValue() *float64 {
	if m == nil {
		return nil
	}
	return m.ShortMarginValue
}

func (m *MarginBalance) GetSma() *float64 {
	if m == nil {
		return nil
	}
	return m.Sma
}

func (m *MarginBalance) GetIsInCall() *float64 {
	if m == nil {
		return nil
	}
	return m.IsInCall
}

func (m *MarginBalance) GetStockBuyingPower() *float64 {
	if m == nil {
		return nil
	}
	return m.StockBuyingPower
}

func (m *MarginBalance) GetOptionBuyingPower() *float64 {
	if m == nil {
		return nil
	}
	return m.OptionBuyingPower
}
