// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type MarginInitialBalance struct {
	AccruedInterest                  *float64 `json:"accruedInterest,omitzero"`
	AvailableFundsNonMarginableTrade *float64 `json:"availableFundsNonMarginableTrade,omitzero"`
	BondValue                        *float64 `json:"bondValue,omitzero"`
	BuyingPower                      *float64 `json:"buyingPower,omitzero"`
	CashBalance                      *float64 `json:"cashBalance,omitzero"`
	CashAvailableForTrading          *float64 `json:"cashAvailableForTrading,omitzero"`
	CashReceipts                     *float64 `json:"cashReceipts,omitzero"`
	DayTradingBuyingPower            *float64 `json:"dayTradingBuyingPower,omitzero"`
	DayTradingBuyingPowerCall        *float64 `json:"dayTradingBuyingPowerCall,omitzero"`
	DayTradingEquityCall             *float64 `json:"dayTradingEquityCall,omitzero"`
	Equity                           *float64 `json:"equity,omitzero"`
	EquityPercentage                 *float64 `json:"equityPercentage,omitzero"`
	LiquidationValue                 *float64 `json:"liquidationValue,omitzero"`
	LongMarginValue                  *float64 `json:"longMarginValue,omitzero"`
	LongOptionMarketValue            *float64 `json:"longOptionMarketValue,omitzero"`
	LongStockValue                   *float64 `json:"longStockValue,omitzero"`
	MaintenanceCall                  *float64 `json:"maintenanceCall,omitzero"`
	MaintenanceRequirement           *float64 `json:"maintenanceRequirement,omitzero"`
	Margin                           *float64 `json:"margin,omitzero"`
	MarginEquity                     *float64 `json:"marginEquity,omitzero"`
	MoneyMarketFund                  *float64 `json:"moneyMarketFund,omitzero"`
	MutualFundValue                  *float64 `json:"mutualFundValue,omitzero"`
	RegTCall                         *float64 `json:"regTCall,omitzero"`
	ShortMarginValue                 *float64 `json:"shortMarginValue,omitzero"`
	ShortOptionMarketValue           *float64 `json:"shortOptionMarketValue,omitzero"`
	ShortStockValue                  *float64 `json:"shortStockValue,omitzero"`
	TotalCash                        *float64 `json:"totalCash,omitzero"`
	IsInCall                         *bool    `json:"isInCall,omitzero"`
	UnsettledCash                    *float64 `json:"unsettledCash,omitzero"`
	PendingDeposits                  *float64 `json:"pendingDeposits,omitzero"`
	MarginBalance                    *float64 `json:"marginBalance,omitzero"`
	ShortBalance                     *float64 `json:"shortBalance,omitzero"`
	AccountValue                     *float64 `json:"accountValue,omitzero"`
}

func (m MarginInitialBalance) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MarginInitialBalance) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MarginInitialBalance) GetAccruedInterest() *float64 {
	if m == nil {
		return nil
	}
	return m.AccruedInterest
}

func (m *MarginInitialBalance) GetAvailableFundsNonMarginableTrade() *float64 {
	if m == nil {
		return nil
	}
	return m.AvailableFundsNonMarginableTrade
}

func (m *MarginInitialBalance) GetBondValue() *float64 {
	if m == nil {
		return nil
	}
	return m.BondValue
}

func (m *MarginInitialBalance) GetBuyingPower() *float64 {
	if m == nil {
		return nil
	}
	return m.BuyingPower
}

func (m *MarginInitialBalance) GetCashBalance() *float64 {
	if m == nil {
		return nil
	}
	return m.CashBalance
}

func (m *MarginInitialBalance) GetCashAvailableForTrading() *float64 {
	if m == nil {
		return nil
	}
	return m.CashAvailableForTrading
}

func (m *MarginInitialBalance) GetCashReceipts() *float64 {
	if m == nil {
		return nil
	}
	return m.CashReceipts
}

func (m *MarginInitialBalance) GetDayTradingBuyingPower() *float64 {
	if m == nil {
		return nil
	}
	return m.DayTradingBuyingPower
}

func (m *MarginInitialBalance) GetDayTradingBuyingPowerCall() *float64 {
	if m == nil {
		return nil
	}
	return m.DayTradingBuyingPowerCall
}

func (m *MarginInitialBalance) GetDayTradingEquityCall() *float64 {
	if m == nil {
		return nil
	}
	return m.DayTradingEquityCall
}

func (m *MarginInitialBalance) GetEquity() *float64 {
	if m == nil {
		return nil
	}
	return m.Equity
}

func (m *MarginInitialBalance) GetEquityPercentage() *float64 {
	if m == nil {
		return nil
	}
	return m.EquityPercentage
}

func (m *MarginInitialBalance) GetLiquidationValue() *float64 {
	if m == nil {
		return nil
	}
	return m.LiquidationValue
}

func (m *MarginInitialBalance) GetLongMarginValue() *float64 {
	if m == nil {
		return nil
	}
	return m.LongMarginValue
}

func (m *MarginInitialBalance) GetLongOptionMarketValue() *float64 {
	if m == nil {
		return nil
	}
	return m.LongOptionMarketValue
}

func (m *MarginInitialBalance) GetLongStockValue() *float64 {
	if m == nil {
		return nil
	}
	return m.LongStockValue
}

func (m *MarginInitialBalance) GetMaintenanceCall() *float64 {
	if m == nil {
		return nil
	}
	return m.MaintenanceCall
}

func (m *MarginInitialBalance) GetMaintenanceRequirement() *float64 {
	if m == nil {
		return nil
	}
	return m.MaintenanceRequirement
}

func (m *MarginInitialBalance) GetMargin() *float64 {
	if m == nil {
		return nil
	}
	return m.Margin
}

func (m *MarginInitialBalance) GetMarginEquity() *float64 {
	if m == nil {
		return nil
	}
	return m.MarginEquity
}

func (m *MarginInitialBalance) GetMoneyMarketFund() *float64 {
	if m == nil {
		return nil
	}
	return m.MoneyMarketFund
}

func (m *MarginInitialBalance) GetMutualFundValue() *float64 {
	if m == nil {
		return nil
	}
	return m.MutualFundValue
}

func (m *MarginInitialBalance) GetRegTCall() *float64 {
	if m == nil {
		return nil
	}
	return m.RegTCall
}

func (m *MarginInitialBalance) GetShortMarginValue() *float64 {
	if m == nil {
		return nil
	}
	return m.ShortMarginValue
}

func (m *MarginInitialBalance) GetShortOptionMarketValue() *float64 {
	if m == nil {
		return nil
	}
	return m.ShortOptionMarketValue
}

func (m *MarginInitialBalance) GetShortStockValue() *float64 {
	if m == nil {
		return nil
	}
	return m.ShortStockValue
}

func (m *MarginInitialBalance) GetTotalCash() *float64 {
	if m == nil {
		return nil
	}
	return m.TotalCash
}

func (m *MarginInitialBalance) GetIsInCall() *bool {
	if m == nil {
		return nil
	}
	return m.IsInCall
}

func (m *MarginInitialBalance) GetUnsettledCash() *float64 {
	if m == nil {
		return nil
	}
	return m.UnsettledCash
}

func (m *MarginInitialBalance) GetPendingDeposits() *float64 {
	if m == nil {
		return nil
	}
	return m.PendingDeposits
}

func (m *MarginInitialBalance) GetMarginBalance() *float64 {
	if m == nil {
		return nil
	}
	return m.MarginBalance
}

func (m *MarginInitialBalance) GetShortBalance() *float64 {
	if m == nil {
		return nil
	}
	return m.ShortBalance
}

func (m *MarginInitialBalance) GetAccountValue() *float64 {
	if m == nil {
		return nil
	}
	return m.AccountValue
}
