// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

type MarginAccountType string

const (
	MarginAccountTypeCash   MarginAccountType = "CASH"
	MarginAccountTypeMargin MarginAccountType = "MARGIN"
)

func (e MarginAccountType) ToPointer() *MarginAccountType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *MarginAccountType) IsExact() bool {
	if e != nil {
		switch *e {
		case "CASH", "MARGIN":
			return true
		}
	}
	return false
}

type MarginAccount struct {
	Type                    *MarginAccountType    `json:"type,omitzero"`
	AccountNumber           *string               `json:"accountNumber,omitzero"`
	RoundTrips              *int                  `json:"roundTrips,omitzero"`
	IsDayTrader             *bool                 `default:"false" json:"isDayTrader"`
	IsClosingOnlyRestricted *bool                 `default:"false" json:"isClosingOnlyRestricted"`
	PfcbFlag                *bool                 `default:"false" json:"pfcbFlag"`
	Positions               []Position            `json:"positions,omitzero"`
	InitialBalances         *MarginInitialBalance `json:"initialBalances,omitzero"`
	CurrentBalances         *MarginBalance        `json:"currentBalances,omitzero"`
	ProjectedBalances       *MarginBalance        `json:"projectedBalances,omitzero"`
}

func (m MarginAccount) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MarginAccount) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MarginAccount) GetType() *MarginAccountType {
	if m == nil {
		return nil
	}
	return m.Type
}

func (m *MarginAccount) GetAccountNumber() *string {
	if m == nil {
		return nil
	}
	return m.AccountNumber
}

func (m *MarginAccount) GetRoundTrips() *int {
	if m == nil {
		return nil
	}
	return m.RoundTrips
}

func (m *MarginAccount) GetIsDayTrader() *bool {
	if m == nil {
		return nil
	}
	return m.IsDayTrader
}

func (m *MarginAccount) GetIsClosingOnlyRestricted() *bool {
	if m == nil {
		return nil
	}
	return m.IsClosingOnlyRestricted
}

func (m *MarginAccount) GetPfcbFlag() *bool {
	if m == nil {
		return nil
	}
	return m.PfcbFlag
}

func (m *MarginAccount) GetPositions() []Position {
	if m == nil {
		return nil
	}
	return m.Positions
}

func (m *MarginAccount) GetInitialBalances() *MarginInitialBalance {
	if m == nil {
		return nil
	}
	return m.InitialBalances
}

func (m *MarginAccount) GetCurrentBalances() *MarginBalance {
	if m == nil {
		return nil
	}
	return m.CurrentBalances
}

func (m *MarginAccount) GetProjectedBalances() *MarginBalance {
	if m == nil {
		return nil
	}
	return m.ProjectedBalances
}
