// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// MutualFundAssetSubType - Asset Sub Type (only there if applicable)
type MutualFundAssetSubType string

const (
	MutualFundAssetSubTypeOef MutualFundAssetSubType = "OEF"
	MutualFundAssetSubTypeCef MutualFundAssetSubType = "CEF"
	MutualFundAssetSubTypeMmf MutualFundAssetSubType = "MMF"
)

func (e MutualFundAssetSubType) ToPointer() *MutualFundAssetSubType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *MutualFundAssetSubType) IsExact() bool {
	if e != nil {
		switch *e {
		case "OEF", "CEF", "MMF":
			return true
		}
	}
	return false
}
