// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
	"undefined/optionalnullable"
)

// MutualFundResponse - Quote info of MutualFund security
type MutualFundResponse struct {
	// Instrument's asset type
	AssetMainType *AssetMainType `json:"assetMainType,omitzero"`
	// Asset Sub Type (only there if applicable)
	AssetSubType optionalnullable.OptionalNullable[MutualFundAssetSubType] `json:"assetSubType,omitzero"`
	// SSID of instrument
	Ssid *int64 `json:"ssid,omitzero"`
	// Symbol of instrument
	Symbol *string `json:"symbol,omitzero"`
	// is quote realtime
	Realtime *bool `json:"realtime,omitzero"`
	// Fundamentals of a security
	Fundamental *Fundamental `json:"fundamental,omitzero"`
	// Quote data of Mutual Fund security
	Quote *QuoteMutualFund `json:"quote,omitzero"`
	// Reference data of MutualFund security
	Reference *ReferenceMutualFund `json:"reference,omitzero"`
}

func (m MutualFundResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MutualFundResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MutualFundResponse) GetAssetMainType() *AssetMainType {
	if m == nil {
		return nil
	}
	return m.AssetMainType
}

func (m *MutualFundResponse) GetAssetSubType() optionalnullable.OptionalNullable[MutualFundAssetSubType] {
	if m == nil {
		return nil
	}
	return m.AssetSubType
}

func (m *MutualFundResponse) GetSsid() *int64 {
	if m == nil {
		return nil
	}
	return m.Ssid
}

func (m *MutualFundResponse) GetSymbol() *string {
	if m == nil {
		return nil
	}
	return m.Symbol
}

func (m *MutualFundResponse) GetRealtime() *bool {
	if m == nil {
		return nil
	}
	return m.Realtime
}

func (m *MutualFundResponse) GetFundamental() *Fundamental {
	if m == nil {
		return nil
	}
	return m.Fundamental
}

func (m *MutualFundResponse) GetQuote() *QuoteMutualFund {
	if m == nil {
		return nil
	}
	return m.Quote
}

func (m *MutualFundResponse) GetReference() *ReferenceMutualFund {
	if m == nil {
		return nil
	}
	return m.Reference
}
