// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type Offer struct {
	Level2Permissions *bool   `default:"false" json:"level2Permissions"`
	MktDataPermission *string `json:"mktDataPermission,omitzero"`
}

func (o Offer) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *Offer) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *Offer) GetLevel2Permissions() *bool {
	if o == nil {
		return nil
	}
	return o.Level2Permissions
}

func (o *Offer) GetMktDataPermission() *string {
	if o == nil {
		return nil
	}
	return o.MktDataPermission
}
