// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

// OptionResponse - Quote info of Option security
type OptionResponse struct {
	// Instrument's asset type
	AssetMainType *AssetMainType `json:"assetMainType,omitzero"`
	// SSID of instrument
	Ssid *int64 `json:"ssid,omitzero"`
	// Symbol of instrument
	Symbol *string `json:"symbol,omitzero"`
	// is quote realtime
	Realtime *bool `json:"realtime,omitzero"`
	// Quote data of Option security
	Quote *QuoteOption `json:"quote,omitzero"`
	// Reference data of Option security
	Reference *ReferenceOption `json:"reference,omitzero"`
}

func (o OptionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OptionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OptionResponse) GetAssetMainType() *AssetMainType {
	if o == nil {
		return nil
	}
	return o.AssetMainType
}

func (o *OptionResponse) GetSsid() *int64 {
	if o == nil {
		return nil
	}
	return o.Ssid
}

func (o *OptionResponse) GetSymbol() *string {
	if o == nil {
		return nil
	}
	return o.Symbol
}

func (o *OptionResponse) GetRealtime() *bool {
	if o == nil {
		return nil
	}
	return o.Realtime
}

func (o *OptionResponse) GetQuote() *QuoteOption {
	if o == nil {
		return nil
	}
	return o.Quote
}

func (o *OptionResponse) GetReference() *ReferenceOption {
	if o == nil {
		return nil
	}
	return o.Reference
}
