// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"

	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type Strategy string

const (
	StrategySingle     Strategy = "SINGLE"
	StrategyAnalytical Strategy = "ANALYTICAL"
	StrategyCovered    Strategy = "COVERED"
	StrategyVertical   Strategy = "VERTICAL"
	StrategyCalendar   Strategy = "CALENDAR"
	StrategyStrangle   Strategy = "STRANGLE"
	StrategyStraddle   Strategy = "STRADDLE"
	StrategyButterfly  Strategy = "BUTTERFLY"
	StrategyCondor     Strategy = "CONDOR"
	StrategyDiagonal   Strategy = "DIAGONAL"
	StrategyCollar     Strategy = "COLLAR"
	StrategyRoll       Strategy = "ROLL"
)

func (e Strategy) ToPointer() *Strategy {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Strategy) IsExact() bool {
	if e != nil {
		switch *e {
		case "SINGLE", "ANALYTICAL", "COVERED", "VERTICAL", "CALENDAR", "STRANGLE", "STRADDLE", "BUTTERFLY", "CONDOR", "DIAGONAL", "COLLAR", "ROLL":
			return true
		}
	}
	return false
}

type OptionChain struct {
	Symbol           *string                              `json:"symbol,omitzero"`
	Status           *string                              `json:"status,omitzero"`
	Underlying       *Underlying                          `json:"underlying,omitzero"`
	Strategy         *Strategy                            `json:"strategy,omitzero"`
	Interval         *float64                             `json:"interval,omitzero"`
	IsDelayed        *bool                                `json:"isDelayed,omitzero"`
	IsIndex          *bool                                `json:"isIndex,omitzero"`
	DaysToExpiration *float64                             `json:"daysToExpiration,omitzero"`
	InterestRate     *float64                             `json:"interestRate,omitzero"`
	UnderlyingPrice  *float64                             `json:"underlyingPrice,omitzero"`
	Volatility       *float64                             `json:"volatility,omitzero"`
	CallExpDateMap   map[string]map[string]OptionContract `json:"callExpDateMap,omitzero"`
	PutExpDateMap    map[string]map[string]OptionContract `json:"putExpDateMap,omitzero"`
}

func (o OptionChain) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OptionChain) UnmarshalJSON(data []byte) error {
	type OptionChainAlias OptionChain
	aux := &struct {
		CallExpDateMap json.RawMessage `json:"callExpDateMap,omitzero"`
		PutExpDateMap  json.RawMessage `json:"putExpDateMap,omitzero"`
		*OptionChainAlias
	}{
		OptionChainAlias: (*OptionChainAlias)(o),
	}

	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}

	processMap := func(raw json.RawMessage) (map[string]map[string]OptionContract, error) {
		if len(raw) == 0 {
			return nil, nil
		}
		// Try unmarshaling as map first
		var m map[string]map[string]OptionContract
		if err := json.Unmarshal(raw, &m); err == nil {
			return m, nil
		}
		// If map fails, try empty array (or any array, treated as empty/nil map)
		var arr []interface{}
		if err := json.Unmarshal(raw, &arr); err == nil {
			return nil, nil
		}
		return nil, json.Unmarshal(raw, &m) // return original map error
	}

	var err error
	o.CallExpDateMap, err = processMap(aux.CallExpDateMap)
	if err != nil {
		return err
	}
	o.PutExpDateMap, err = processMap(aux.PutExpDateMap)
	if err != nil {
		return err
	}

	return nil
}

func (o *OptionChain) GetSymbol() *string {
	if o == nil {
		return nil
	}
	return o.Symbol
}

func (o *OptionChain) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *OptionChain) GetUnderlying() *Underlying {
	if o == nil {
		return nil
	}
	return o.Underlying
}

func (o *OptionChain) GetStrategy() *Strategy {
	if o == nil {
		return nil
	}
	return o.Strategy
}

func (o *OptionChain) GetInterval() *float64 {
	if o == nil {
		return nil
	}
	return o.Interval
}

func (o *OptionChain) GetIsDelayed() *bool {
	if o == nil {
		return nil
	}
	return o.IsDelayed
}

func (o *OptionChain) GetIsIndex() *bool {
	if o == nil {
		return nil
	}
	return o.IsIndex
}

func (o *OptionChain) GetDaysToExpiration() *float64 {
	if o == nil {
		return nil
	}
	return o.DaysToExpiration
}

func (o *OptionChain) GetInterestRate() *float64 {
	if o == nil {
		return nil
	}
	return o.InterestRate
}

func (o *OptionChain) GetUnderlyingPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.UnderlyingPrice
}

func (o *OptionChain) GetVolatility() *float64 {
	if o == nil {
		return nil
	}
	return o.Volatility
}

func (o *OptionChain) GetCallExpDateMap() map[string]map[string]OptionContract {
	if o == nil {
		return nil
	}
	return o.CallExpDateMap
}

func (o *OptionChain) GetPutExpDateMap() map[string]map[string]OptionContract {
	if o == nil {
		return nil
	}
	return o.PutExpDateMap
}
