// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type OptionContractObjectPutCall string

const (
	OptionContractObjectPutCallPut  OptionContractObjectPutCall = "PUT"
	OptionContractObjectPutCallCall OptionContractObjectPutCall = "CALL"
)

func (e OptionContractObjectPutCall) ToPointer() *OptionContractObjectPutCall {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *OptionContractObjectPutCall) IsExact() bool {
	if e != nil {
		switch *e {
		case "PUT", "CALL":
			return true
		}
	}
	return false
}

type OptionContractObject struct {
	PutCall                *OptionContractObjectPutCall `json:"putCall,omitzero"`
	Symbol                 *string                      `json:"symbol,omitzero"`
	Description            *string                      `json:"description,omitzero"`
	ExchangeName           *string                      `json:"exchangeName,omitzero"`
	BidPrice               *float64                     `json:"bidPrice,omitzero"`
	AskPrice               *float64                     `json:"askPrice,omitzero"`
	LastPrice              *float64                     `json:"lastPrice,omitzero"`
	MarkPrice              *float64                     `json:"markPrice,omitzero"`
	BidSize                *int                         `json:"bidSize,omitzero"`
	AskSize                *int                         `json:"askSize,omitzero"`
	LastSize               *int                         `json:"lastSize,omitzero"`
	HighPrice              *float64                     `json:"highPrice,omitzero"`
	LowPrice               *float64                     `json:"lowPrice,omitzero"`
	OpenPrice              *float64                     `json:"openPrice,omitzero"`
	ClosePrice             *float64                     `json:"closePrice,omitzero"`
	TotalVolume            *int                         `json:"totalVolume,omitzero"`
	TradeDate              *float64                     `json:"tradeDate,omitzero"`
	QuoteTimeInLong        *int                         `json:"quoteTimeInLong,omitzero"`
	TradeTimeInLong        *int                         `json:"tradeTimeInLong,omitzero"`
	NetChange              *float64                     `json:"netChange,omitzero"`
	Volatility             *float64                     `json:"volatility,omitzero"`
	Delta                  *float64                     `json:"delta,omitzero"`
	Gamma                  *float64                     `json:"gamma,omitzero"`
	Theta                  *float64                     `json:"theta,omitzero"`
	Vega                   *float64                     `json:"vega,omitzero"`
	Rho                    *float64                     `json:"rho,omitzero"`
	TimeValue              *float64                     `json:"timeValue,omitzero"`
	OpenInterest           *float64                     `json:"openInterest,omitzero"`
	IsInTheMoney           *bool                        `json:"isInTheMoney,omitzero"`
	TheoreticalOptionValue *float64                     `json:"theoreticalOptionValue,omitzero"`
	TheoreticalVolatility  *float64                     `json:"theoreticalVolatility,omitzero"`
	IsMini                 *bool                        `json:"isMini,omitzero"`
	IsNonStandard          *bool                        `json:"isNonStandard,omitzero"`
	OptionDeliverablesList []OptionDeliverables         `json:"optionDeliverablesList,omitzero"`
	StrikePrice            *float64                     `json:"strikePrice,omitzero"`
	ExpirationDate         *string                      `json:"expirationDate,omitzero"`
	DaysToExpiration       *float64                     `json:"daysToExpiration,omitzero"`
	// M for End Of Month Expiration Calendar Cycle. (To match the last business day of the month), Q for Quarterly expirations (last business day of the quarter month MAR/JUN/SEP/DEC), W for Weekly expiration (also called Friday Short Term Expirations) and S for Expires 3rd Friday of the month (also known as regular options).
	ExpirationType *ExpirationType `json:"expirationType,omitzero"`
	LastTradingDay *float64        `json:"lastTradingDay,omitzero"`
	Multiplier     *float64        `json:"multiplier,omitzero"`
	// option contract settlement type AM or PM
	SettlementType    *SettlementType `json:"settlementType,omitzero"`
	DeliverableNote   *string         `json:"deliverableNote,omitzero"`
	IsIndexOption     *bool           `json:"isIndexOption,omitzero"`
	PercentChange     *float64        `json:"percentChange,omitzero"`
	MarkChange        *float64        `json:"markChange,omitzero"`
	MarkPercentChange *float64        `json:"markPercentChange,omitzero"`
	IsPennyPilot      *bool           `json:"isPennyPilot,omitzero"`
	IntrinsicValue    *float64        `json:"intrinsicValue,omitzero"`
	OptionRoot        *string         `json:"optionRoot,omitzero"`
}

func (o OptionContractObject) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OptionContractObject) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OptionContractObject) GetPutCall() *OptionContractObjectPutCall {
	if o == nil {
		return nil
	}
	return o.PutCall
}

func (o *OptionContractObject) GetSymbol() *string {
	if o == nil {
		return nil
	}
	return o.Symbol
}

func (o *OptionContractObject) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *OptionContractObject) GetExchangeName() *string {
	if o == nil {
		return nil
	}
	return o.ExchangeName
}

func (o *OptionContractObject) GetBidPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.BidPrice
}

func (o *OptionContractObject) GetAskPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.AskPrice
}

func (o *OptionContractObject) GetLastPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.LastPrice
}

func (o *OptionContractObject) GetMarkPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.MarkPrice
}

func (o *OptionContractObject) GetBidSize() *int {
	if o == nil {
		return nil
	}
	return o.BidSize
}

func (o *OptionContractObject) GetAskSize() *int {
	if o == nil {
		return nil
	}
	return o.AskSize
}

func (o *OptionContractObject) GetLastSize() *int {
	if o == nil {
		return nil
	}
	return o.LastSize
}

func (o *OptionContractObject) GetHighPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.HighPrice
}

func (o *OptionContractObject) GetLowPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.LowPrice
}

func (o *OptionContractObject) GetOpenPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.OpenPrice
}

func (o *OptionContractObject) GetClosePrice() *float64 {
	if o == nil {
		return nil
	}
	return o.ClosePrice
}

func (o *OptionContractObject) GetTotalVolume() *int {
	if o == nil {
		return nil
	}
	return o.TotalVolume
}

func (o *OptionContractObject) GetTradeDate() *float64 {
	if o == nil {
		return nil
	}
	return o.TradeDate
}

func (o *OptionContractObject) GetQuoteTimeInLong() *int {
	if o == nil {
		return nil
	}
	return o.QuoteTimeInLong
}

func (o *OptionContractObject) GetTradeTimeInLong() *int {
	if o == nil {
		return nil
	}
	return o.TradeTimeInLong
}

func (o *OptionContractObject) GetNetChange() *float64 {
	if o == nil {
		return nil
	}
	return o.NetChange
}

func (o *OptionContractObject) GetVolatility() *float64 {
	if o == nil {
		return nil
	}
	return o.Volatility
}

func (o *OptionContractObject) GetDelta() *float64 {
	if o == nil {
		return nil
	}
	return o.Delta
}

func (o *OptionContractObject) GetGamma() *float64 {
	if o == nil {
		return nil
	}
	return o.Gamma
}

func (o *OptionContractObject) GetTheta() *float64 {
	if o == nil {
		return nil
	}
	return o.Theta
}

func (o *OptionContractObject) GetVega() *float64 {
	if o == nil {
		return nil
	}
	return o.Vega
}

func (o *OptionContractObject) GetRho() *float64 {
	if o == nil {
		return nil
	}
	return o.Rho
}

func (o *OptionContractObject) GetTimeValue() *float64 {
	if o == nil {
		return nil
	}
	return o.TimeValue
}

func (o *OptionContractObject) GetOpenInterest() *float64 {
	if o == nil {
		return nil
	}
	return o.OpenInterest
}

func (o *OptionContractObject) GetIsInTheMoney() *bool {
	if o == nil {
		return nil
	}
	return o.IsInTheMoney
}

func (o *OptionContractObject) GetTheoreticalOptionValue() *float64 {
	if o == nil {
		return nil
	}
	return o.TheoreticalOptionValue
}

func (o *OptionContractObject) GetTheoreticalVolatility() *float64 {
	if o == nil {
		return nil
	}
	return o.TheoreticalVolatility
}

func (o *OptionContractObject) GetIsMini() *bool {
	if o == nil {
		return nil
	}
	return o.IsMini
}

func (o *OptionContractObject) GetIsNonStandard() *bool {
	if o == nil {
		return nil
	}
	return o.IsNonStandard
}

func (o *OptionContractObject) GetOptionDeliverablesList() []OptionDeliverables {
	if o == nil {
		return nil
	}
	return o.OptionDeliverablesList
}

func (o *OptionContractObject) GetStrikePrice() *float64 {
	if o == nil {
		return nil
	}
	return o.StrikePrice
}

func (o *OptionContractObject) GetExpirationDate() *string {
	if o == nil {
		return nil
	}
	return o.ExpirationDate
}

func (o *OptionContractObject) GetDaysToExpiration() *float64 {
	if o == nil {
		return nil
	}
	return o.DaysToExpiration
}

func (o *OptionContractObject) GetExpirationType() *ExpirationType {
	if o == nil {
		return nil
	}
	return o.ExpirationType
}

func (o *OptionContractObject) GetLastTradingDay() *float64 {
	if o == nil {
		return nil
	}
	return o.LastTradingDay
}

func (o *OptionContractObject) GetMultiplier() *float64 {
	if o == nil {
		return nil
	}
	return o.Multiplier
}

func (o *OptionContractObject) GetSettlementType() *SettlementType {
	if o == nil {
		return nil
	}
	return o.SettlementType
}

func (o *OptionContractObject) GetDeliverableNote() *string {
	if o == nil {
		return nil
	}
	return o.DeliverableNote
}

func (o *OptionContractObject) GetIsIndexOption() *bool {
	if o == nil {
		return nil
	}
	return o.IsIndexOption
}

func (o *OptionContractObject) GetPercentChange() *float64 {
	if o == nil {
		return nil
	}
	return o.PercentChange
}

func (o *OptionContractObject) GetMarkChange() *float64 {
	if o == nil {
		return nil
	}
	return o.MarkChange
}

func (o *OptionContractObject) GetMarkPercentChange() *float64 {
	if o == nil {
		return nil
	}
	return o.MarkPercentChange
}

func (o *OptionContractObject) GetIsPennyPilot() *bool {
	if o == nil {
		return nil
	}
	return o.IsPennyPilot
}

func (o *OptionContractObject) GetIntrinsicValue() *float64 {
	if o == nil {
		return nil
	}
	return o.IntrinsicValue
}

func (o *OptionContractObject) GetOptionRoot() *string {
	if o == nil {
		return nil
	}
	return o.OptionRoot
}
