// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type OptionContractType string

const (
	OptionContractTypeOptionContractObject        OptionContractType = "OptionContractObject"
	OptionContractTypeArrayOfOptionContractObject OptionContractType = "arrayOfOptionContractObject"
)

type OptionContract struct {
	OptionContractObject        *OptionContractObject  `queryParam:"inline" union:"member"`
	ArrayOfOptionContractObject []OptionContractObject `queryParam:"inline" union:"member"`

	Type OptionContractType
}

func CreateOptionContractOptionContractObject(optionContractObject OptionContractObject) OptionContract {
	typ := OptionContractTypeOptionContractObject

	return OptionContract{
		OptionContractObject: &optionContractObject,
		Type:                 typ,
	}
}

func CreateOptionContractArrayOfOptionContractObject(arrayOfOptionContractObject []OptionContractObject) OptionContract {
	typ := OptionContractTypeArrayOfOptionContractObject

	return OptionContract{
		ArrayOfOptionContractObject: arrayOfOptionContractObject,
		Type:                        typ,
	}
}

func (u *OptionContract) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var optionContractObject OptionContractObject = OptionContractObject{}
	if err := utils.UnmarshalJSON(data, &optionContractObject, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  OptionContractTypeOptionContractObject,
			Value: &optionContractObject,
		})
	}

	var arrayOfOptionContractObject []OptionContractObject = []OptionContractObject{}
	if err := utils.UnmarshalJSON(data, &arrayOfOptionContractObject, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  OptionContractTypeArrayOfOptionContractObject,
			Value: arrayOfOptionContractObject,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for OptionContract", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for OptionContract", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(OptionContractType)
	switch best.Type {
	case OptionContractTypeOptionContractObject:
		u.OptionContractObject = best.Value.(*OptionContractObject)
		return nil
	case OptionContractTypeArrayOfOptionContractObject:
		u.ArrayOfOptionContractObject = best.Value.([]OptionContractObject)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for OptionContract", string(data))
}

func (u OptionContract) MarshalJSON() ([]byte, error) {
	if u.OptionContractObject != nil {
		return utils.MarshalJSON(u.OptionContractObject, "", true)
	}

	if u.ArrayOfOptionContractObject != nil {
		return utils.MarshalJSON(u.ArrayOfOptionContractObject, "", true)
	}

	return nil, errors.New("could not marshal union type OptionContract: all fields are null")
}
