// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type OptionDeliverables struct {
	Symbol           *string  `json:"symbol,omitzero"`
	AssetType        *string  `json:"assetType,omitzero"`
	DeliverableUnits *float64 `json:"deliverableUnits,omitzero"`
	CurrencyType     *string  `json:"currencyType,omitzero"`
}

func (o *OptionDeliverables) GetSymbol() *string {
	if o == nil {
		return nil
	}
	return o.Symbol
}

func (o *OptionDeliverables) GetAssetType() *string {
	if o == nil {
		return nil
	}
	return o.AssetType
}

func (o *OptionDeliverables) GetDeliverableUnits() *float64 {
	if o == nil {
		return nil
	}
	return o.DeliverableUnits
}

func (o *OptionDeliverables) GetCurrencyType() *string {
	if o == nil {
		return nil
	}
	return o.CurrencyType
}
