// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type OrderValidationDetail struct {
	ValidationRuleName *string        `json:"validationRuleName,omitzero"`
	Message            *string        `json:"message,omitzero"`
	ActivityMessage    *string        `json:"activityMessage,omitzero"`
	OriginalSeverity   *APIRuleAction `json:"originalSeverity,omitzero"`
	OverrideName       *string        `json:"overrideName,omitzero"`
	OverrideSeverity   *APIRuleAction `json:"overrideSeverity,omitzero"`
}

func (o *OrderValidationDetail) GetValidationRuleName() *string {
	if o == nil {
		return nil
	}
	return o.ValidationRuleName
}

func (o *OrderValidationDetail) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *OrderValidationDetail) GetActivityMessage() *string {
	if o == nil {
		return nil
	}
	return o.ActivityMessage
}

func (o *OrderValidationDetail) GetOriginalSeverity() *APIRuleAction {
	if o == nil {
		return nil
	}
	return o.OriginalSeverity
}

func (o *OrderValidationDetail) GetOverrideName() *string {
	if o == nil {
		return nil
	}
	return o.OverrideName
}

func (o *OrderValidationDetail) GetOverrideSeverity() *APIRuleAction {
	if o == nil {
		return nil
	}
	return o.OverrideSeverity
}
