// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type OrderStrategyType string

const (
	OrderStrategyTypeSingle     OrderStrategyType = "SINGLE"
	OrderStrategyTypeCancel     OrderStrategyType = "CANCEL"
	OrderStrategyTypeRecall     OrderStrategyType = "RECALL"
	OrderStrategyTypePair       OrderStrategyType = "PAIR"
	OrderStrategyTypeFlatten    OrderStrategyType = "FLATTEN"
	OrderStrategyTypeTwoDaySwap OrderStrategyType = "TWO_DAY_SWAP"
	OrderStrategyTypeBlastAll   OrderStrategyType = "BLAST_ALL"
	OrderStrategyTypeOco        OrderStrategyType = "OCO"
	OrderStrategyTypeTrigger    OrderStrategyType = "TRIGGER"
)

func (e OrderStrategyType) ToPointer() *OrderStrategyType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *OrderStrategyType) IsExact() bool {
	if e != nil {
		switch *e {
		case "SINGLE", "CANCEL", "RECALL", "PAIR", "FLATTEN", "TWO_DAY_SWAP", "BLAST_ALL", "OCO", "TRIGGER":
			return true
		}
	}
	return false
}
