// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type OrderActivityActivityType string

const (
	OrderActivityActivityTypeExecution   OrderActivityActivityType = "EXECUTION"
	OrderActivityActivityTypeOrderAction OrderActivityActivityType = "ORDER_ACTION"
)

func (e OrderActivityActivityType) ToPointer() *OrderActivityActivityType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *OrderActivityActivityType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EXECUTION", "ORDER_ACTION":
			return true
		}
	}
	return false
}

type ExecutionType string

const (
	ExecutionTypeFill ExecutionType = "FILL"
)

func (e ExecutionType) ToPointer() *ExecutionType {
	return &e
}
func (e *ExecutionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "FILL":
		*e = ExecutionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ExecutionType: %v", v)
	}
}

type OrderActivity struct {
	ActivityType           *OrderActivityActivityType `json:"activityType,omitzero"`
	ExecutionType          *ExecutionType             `json:"executionType,omitzero"`
	Quantity               *float64                   `json:"quantity,omitzero"`
	OrderRemainingQuantity *float64                   `json:"orderRemainingQuantity,omitzero"`
	ExecutionLegs          []ExecutionLeg             `json:"executionLegs,omitzero"`
}

func (o OrderActivity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrderActivity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrderActivity) GetActivityType() *OrderActivityActivityType {
	if o == nil {
		return nil
	}
	return o.ActivityType
}

func (o *OrderActivity) GetExecutionType() *ExecutionType {
	if o == nil {
		return nil
	}
	return o.ExecutionType
}

func (o *OrderActivity) GetQuantity() *float64 {
	if o == nil {
		return nil
	}
	return o.Quantity
}

func (o *OrderActivity) GetOrderRemainingQuantity() *float64 {
	if o == nil {
		return nil
	}
	return o.OrderRemainingQuantity
}

func (o *OrderActivity) GetExecutionLegs() []ExecutionLeg {
	if o == nil {
		return nil
	}
	return o.ExecutionLegs
}
