// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"time"
	"undefined/internal/utils"
)

type OrderRequest struct {
	Session  *Session  `json:"session,omitzero"`
	Duration *Duration `json:"duration,omitzero"`
	// Same as orderType, but does not have UNKNOWN since this type is not allowed as an input
	OrderType                *OrderTypeRequest         `json:"orderType,omitzero"`
	CancelTime               *time.Time                `json:"cancelTime,omitzero"`
	ComplexOrderStrategyType *ComplexOrderStrategyType `json:"complexOrderStrategyType,omitzero"`
	Quantity                 *float64                  `json:"quantity,omitzero"`
	FilledQuantity           *float64                  `json:"filledQuantity,omitzero"`
	RemainingQuantity        *float64                  `json:"remainingQuantity,omitzero"`
	DestinationLinkName      *string                   `json:"destinationLinkName,omitzero"`
	ReleaseTime              *time.Time                `json:"releaseTime,omitzero"`
	StopPrice                *float64                  `json:"stopPrice,omitzero"`
	StopPriceLinkBasis       *StopPriceLinkBasis       `json:"stopPriceLinkBasis,omitzero"`
	StopPriceLinkType        *StopPriceLinkType        `json:"stopPriceLinkType,omitzero"`
	StopPriceOffset          *float64                  `json:"stopPriceOffset,omitzero"`
	StopType                 *StopType                 `json:"stopType,omitzero"`
	PriceLinkBasis           *PriceLinkBasis           `json:"priceLinkBasis,omitzero"`
	PriceLinkType            *PriceLinkType            `json:"priceLinkType,omitzero"`
	Price                    *float64                  `json:"price,omitzero"`
	TaxLotMethod             *TaxLotMethod             `json:"taxLotMethod,omitzero"`
	OrderLegCollection       []OrderLegCollection      `json:"orderLegCollection,omitzero"`
	ActivationPrice          *float64                  `json:"activationPrice,omitzero"`
	SpecialInstruction       *SpecialInstruction       `json:"specialInstruction,omitzero"`
	OrderStrategyType        *OrderStrategyType        `json:"orderStrategyType,omitzero"`
	OrderID                  *int64                    `json:"orderId,omitzero"`
	Cancelable               *bool                     `default:"false" json:"cancelable"`
	Editable                 *bool                     `default:"false" json:"editable"`
	Status                   *Status                   `json:"status,omitzero"`
	EnteredTime              *time.Time                `json:"enteredTime,omitzero"`
	CloseTime                *time.Time                `json:"closeTime,omitzero"`
	AccountNumber            *int64                    `json:"accountNumber,omitzero"`
	OrderActivityCollection  []OrderActivity           `json:"orderActivityCollection,omitzero"`
	ReplacingOrderCollection []OrderRequest            `json:"replacingOrderCollection,omitzero"`
	ChildOrderStrategies     []OrderRequest            `json:"childOrderStrategies,omitzero"`
	StatusDescription        *string                   `json:"statusDescription,omitzero"`
}

func (o OrderRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrderRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrderRequest) GetSession() *Session {
	if o == nil {
		return nil
	}
	return o.Session
}

func (o *OrderRequest) GetDuration() *Duration {
	if o == nil {
		return nil
	}
	return o.Duration
}

func (o *OrderRequest) GetOrderType() *OrderTypeRequest {
	if o == nil {
		return nil
	}
	return o.OrderType
}

func (o *OrderRequest) GetCancelTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.CancelTime
}

func (o *OrderRequest) GetComplexOrderStrategyType() *ComplexOrderStrategyType {
	if o == nil {
		return nil
	}
	return o.ComplexOrderStrategyType
}

func (o *OrderRequest) GetQuantity() *float64 {
	if o == nil {
		return nil
	}
	return o.Quantity
}

func (o *OrderRequest) GetFilledQuantity() *float64 {
	if o == nil {
		return nil
	}
	return o.FilledQuantity
}

func (o *OrderRequest) GetRemainingQuantity() *float64 {
	if o == nil {
		return nil
	}
	return o.RemainingQuantity
}

func (o *OrderRequest) GetDestinationLinkName() *string {
	if o == nil {
		return nil
	}
	return o.DestinationLinkName
}

func (o *OrderRequest) GetReleaseTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.ReleaseTime
}

func (o *OrderRequest) GetStopPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.StopPrice
}

func (o *OrderRequest) GetStopPriceLinkBasis() *StopPriceLinkBasis {
	if o == nil {
		return nil
	}
	return o.StopPriceLinkBasis
}

func (o *OrderRequest) GetStopPriceLinkType() *StopPriceLinkType {
	if o == nil {
		return nil
	}
	return o.StopPriceLinkType
}

func (o *OrderRequest) GetStopPriceOffset() *float64 {
	if o == nil {
		return nil
	}
	return o.StopPriceOffset
}

func (o *OrderRequest) GetStopType() *StopType {
	if o == nil {
		return nil
	}
	return o.StopType
}

func (o *OrderRequest) GetPriceLinkBasis() *PriceLinkBasis {
	if o == nil {
		return nil
	}
	return o.PriceLinkBasis
}

func (o *OrderRequest) GetPriceLinkType() *PriceLinkType {
	if o == nil {
		return nil
	}
	return o.PriceLinkType
}

func (o *OrderRequest) GetPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.Price
}

func (o *OrderRequest) GetTaxLotMethod() *TaxLotMethod {
	if o == nil {
		return nil
	}
	return o.TaxLotMethod
}

func (o *OrderRequest) GetOrderLegCollection() []OrderLegCollection {
	if o == nil {
		return nil
	}
	return o.OrderLegCollection
}

func (o *OrderRequest) GetActivationPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.ActivationPrice
}

func (o *OrderRequest) GetSpecialInstruction() *SpecialInstruction {
	if o == nil {
		return nil
	}
	return o.SpecialInstruction
}

func (o *OrderRequest) GetOrderStrategyType() *OrderStrategyType {
	if o == nil {
		return nil
	}
	return o.OrderStrategyType
}

func (o *OrderRequest) GetOrderID() *int64 {
	if o == nil {
		return nil
	}
	return o.OrderID
}

func (o *OrderRequest) GetCancelable() *bool {
	if o == nil {
		return nil
	}
	return o.Cancelable
}

func (o *OrderRequest) GetEditable() *bool {
	if o == nil {
		return nil
	}
	return o.Editable
}

func (o *OrderRequest) GetStatus() *Status {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *OrderRequest) GetEnteredTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.EnteredTime
}

func (o *OrderRequest) GetCloseTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.CloseTime
}

func (o *OrderRequest) GetAccountNumber() *int64 {
	if o == nil {
		return nil
	}
	return o.AccountNumber
}

func (o *OrderRequest) GetOrderActivityCollection() []OrderActivity {
	if o == nil {
		return nil
	}
	return o.OrderActivityCollection
}

func (o *OrderRequest) GetReplacingOrderCollection() []OrderRequest {
	if o == nil {
		return nil
	}
	return o.ReplacingOrderCollection
}

func (o *OrderRequest) GetChildOrderStrategies() []OrderRequest {
	if o == nil {
		return nil
	}
	return o.ChildOrderStrategies
}

func (o *OrderRequest) GetStatusDescription() *string {
	if o == nil {
		return nil
	}
	return o.StatusDescription
}
