// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"time"
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type AdvancedOrderType string

const (
	AdvancedOrderTypeNone     AdvancedOrderType = "NONE"
	AdvancedOrderTypeOto      AdvancedOrderType = "OTO"
	AdvancedOrderTypeOco      AdvancedOrderType = "OCO"
	AdvancedOrderTypeOtoco    AdvancedOrderType = "OTOCO"
	AdvancedOrderTypeOt2Oco   AdvancedOrderType = "OT2OCO"
	AdvancedOrderTypeOt3Oco   AdvancedOrderType = "OT3OCO"
	AdvancedOrderTypeBlastAll AdvancedOrderType = "BLAST_ALL"
	AdvancedOrderTypeOta      AdvancedOrderType = "OTA"
	AdvancedOrderTypePair     AdvancedOrderType = "PAIR"
)

func (e AdvancedOrderType) ToPointer() *AdvancedOrderType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AdvancedOrderType) IsExact() bool {
	if e != nil {
		switch *e {
		case "NONE", "OTO", "OCO", "OTOCO", "OT2OCO", "OT3OCO", "BLAST_ALL", "OTA", "PAIR":
			return true
		}
	}
	return false
}

type OrderStrategy struct {
	AccountNumber          *string                   `json:"accountNumber,omitzero"`
	AdvancedOrderType      *AdvancedOrderType        `json:"advancedOrderType,omitzero"`
	CloseTime              *time.Time                `json:"closeTime,omitzero"`
	EnteredTime            *time.Time                `json:"enteredTime,omitzero"`
	OrderBalance           *OrderBalance             `json:"orderBalance,omitzero"`
	OrderStrategyType      *OrderStrategyType        `json:"orderStrategyType,omitzero"`
	OrderVersion           *float64                  `json:"orderVersion,omitzero"`
	Session                *Session                  `json:"session,omitzero"`
	Status                 *APIOrderStatus           `json:"status,omitzero"`
	AllOrNone              *bool                     `json:"allOrNone,omitzero"`
	Discretionary          *bool                     `json:"discretionary,omitzero"`
	Duration               *Duration                 `json:"duration,omitzero"`
	FilledQuantity         *float64                  `json:"filledQuantity,omitzero"`
	OrderType              *OrderType                `json:"orderType,omitzero"`
	OrderValue             *float64                  `json:"orderValue,omitzero"`
	Price                  *float64                  `json:"price,omitzero"`
	Quantity               *float64                  `json:"quantity,omitzero"`
	RemainingQuantity      *float64                  `json:"remainingQuantity,omitzero"`
	SellNonMarginableFirst *bool                     `json:"sellNonMarginableFirst,omitzero"`
	SettlementInstruction  *SettlementInstruction    `json:"settlementInstruction,omitzero"`
	Strategy               *ComplexOrderStrategyType `json:"strategy,omitzero"`
	AmountIndicator        *AmountIndicator          `json:"amountIndicator,omitzero"`
	OrderLegs              []OrderLeg                `json:"orderLegs,omitzero"`
}

func (o OrderStrategy) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrderStrategy) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrderStrategy) GetAccountNumber() *string {
	if o == nil {
		return nil
	}
	return o.AccountNumber
}

func (o *OrderStrategy) GetAdvancedOrderType() *AdvancedOrderType {
	if o == nil {
		return nil
	}
	return o.AdvancedOrderType
}

func (o *OrderStrategy) GetCloseTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.CloseTime
}

func (o *OrderStrategy) GetEnteredTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.EnteredTime
}

func (o *OrderStrategy) GetOrderBalance() *OrderBalance {
	if o == nil {
		return nil
	}
	return o.OrderBalance
}

func (o *OrderStrategy) GetOrderStrategyType() *OrderStrategyType {
	if o == nil {
		return nil
	}
	return o.OrderStrategyType
}

func (o *OrderStrategy) GetOrderVersion() *float64 {
	if o == nil {
		return nil
	}
	return o.OrderVersion
}

func (o *OrderStrategy) GetSession() *Session {
	if o == nil {
		return nil
	}
	return o.Session
}

func (o *OrderStrategy) GetStatus() *APIOrderStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *OrderStrategy) GetAllOrNone() *bool {
	if o == nil {
		return nil
	}
	return o.AllOrNone
}

func (o *OrderStrategy) GetDiscretionary() *bool {
	if o == nil {
		return nil
	}
	return o.Discretionary
}

func (o *OrderStrategy) GetDuration() *Duration {
	if o == nil {
		return nil
	}
	return o.Duration
}

func (o *OrderStrategy) GetFilledQuantity() *float64 {
	if o == nil {
		return nil
	}
	return o.FilledQuantity
}

func (o *OrderStrategy) GetOrderType() *OrderType {
	if o == nil {
		return nil
	}
	return o.OrderType
}

func (o *OrderStrategy) GetOrderValue() *float64 {
	if o == nil {
		return nil
	}
	return o.OrderValue
}

func (o *OrderStrategy) GetPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.Price
}

func (o *OrderStrategy) GetQuantity() *float64 {
	if o == nil {
		return nil
	}
	return o.Quantity
}

func (o *OrderStrategy) GetRemainingQuantity() *float64 {
	if o == nil {
		return nil
	}
	return o.RemainingQuantity
}

func (o *OrderStrategy) GetSellNonMarginableFirst() *bool {
	if o == nil {
		return nil
	}
	return o.SellNonMarginableFirst
}

func (o *OrderStrategy) GetSettlementInstruction() *SettlementInstruction {
	if o == nil {
		return nil
	}
	return o.SettlementInstruction
}

func (o *OrderStrategy) GetStrategy() *ComplexOrderStrategyType {
	if o == nil {
		return nil
	}
	return o.Strategy
}

func (o *OrderStrategy) GetAmountIndicator() *AmountIndicator {
	if o == nil {
		return nil
	}
	return o.AmountIndicator
}

func (o *OrderStrategy) GetOrderLegs() []OrderLeg {
	if o == nil {
		return nil
	}
	return o.OrderLegs
}
