// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type OrderLeg struct {
	AskPrice            *float64     `json:"askPrice,omitzero"`
	BidPrice            *float64     `json:"bidPrice,omitzero"`
	LastPrice           *float64     `json:"lastPrice,omitzero"`
	MarkPrice           *float64     `json:"markPrice,omitzero"`
	ProjectedCommission *float64     `json:"projectedCommission,omitzero"`
	Quantity            *float64     `json:"quantity,omitzero"`
	FinalSymbol         *string      `json:"finalSymbol,omitzero"`
	LegID               *float64     `json:"legId,omitzero"`
	AssetType           *AssetType   `json:"assetType,omitzero"`
	Instruction         *Instruction `json:"instruction,omitzero"`
}

func (o *OrderLeg) GetAskPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.AskPrice
}

func (o *OrderLeg) GetBidPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.BidPrice
}

func (o *OrderLeg) GetLastPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.LastPrice
}

func (o *OrderLeg) GetMarkPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.MarkPrice
}

func (o *OrderLeg) GetProjectedCommission() *float64 {
	if o == nil {
		return nil
	}
	return o.ProjectedCommission
}

func (o *OrderLeg) GetQuantity() *float64 {
	if o == nil {
		return nil
	}
	return o.Quantity
}

func (o *OrderLeg) GetFinalSymbol() *string {
	if o == nil {
		return nil
	}
	return o.FinalSymbol
}

func (o *OrderLeg) GetLegID() *float64 {
	if o == nil {
		return nil
	}
	return o.LegID
}

func (o *OrderLeg) GetAssetType() *AssetType {
	if o == nil {
		return nil
	}
	return o.AssetType
}

func (o *OrderLeg) GetInstruction() *Instruction {
	if o == nil {
		return nil
	}
	return o.Instruction
}
