// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type OrderValidationResult struct {
	Alerts  []OrderValidationDetail `json:"alerts,omitzero"`
	Accepts []OrderValidationDetail `json:"accepts,omitzero"`
	Rejects []OrderValidationDetail `json:"rejects,omitzero"`
	Reviews []OrderValidationDetail `json:"reviews,omitzero"`
	Warns   []OrderValidationDetail `json:"warns,omitzero"`
}

func (o OrderValidationResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrderValidationResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrderValidationResult) GetAlerts() []OrderValidationDetail {
	if o == nil {
		return nil
	}
	return o.Alerts
}

func (o *OrderValidationResult) GetAccepts() []OrderValidationDetail {
	if o == nil {
		return nil
	}
	return o.Accepts
}

func (o *OrderValidationResult) GetRejects() []OrderValidationDetail {
	if o == nil {
		return nil
	}
	return o.Rejects
}

func (o *OrderValidationResult) GetReviews() []OrderValidationDetail {
	if o == nil {
		return nil
	}
	return o.Reviews
}

func (o *OrderValidationResult) GetWarns() []OrderValidationDetail {
	if o == nil {
		return nil
	}
	return o.Warns
}
