// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// OrderTypeRequest - Same as orderType, but does not have UNKNOWN since this type is not allowed as an input
type OrderTypeRequest string

const (
	OrderTypeRequestMarket            OrderTypeRequest = "MARKET"
	OrderTypeRequestLimit             OrderTypeRequest = "LIMIT"
	OrderTypeRequestStop              OrderTypeRequest = "STOP"
	OrderTypeRequestStopLimit         OrderTypeRequest = "STOP_LIMIT"
	OrderTypeRequestTrailingStop      OrderTypeRequest = "TRAILING_STOP"
	OrderTypeRequestCabinet           OrderTypeRequest = "CABINET"
	OrderTypeRequestNonMarketable     OrderTypeRequest = "NON_MARKETABLE"
	OrderTypeRequestMarketOnClose     OrderTypeRequest = "MARKET_ON_CLOSE"
	OrderTypeRequestExercise          OrderTypeRequest = "EXERCISE"
	OrderTypeRequestTrailingStopLimit OrderTypeRequest = "TRAILING_STOP_LIMIT"
	OrderTypeRequestNetDebit          OrderTypeRequest = "NET_DEBIT"
	OrderTypeRequestNetCredit         OrderTypeRequest = "NET_CREDIT"
	OrderTypeRequestNetZero           OrderTypeRequest = "NET_ZERO"
	OrderTypeRequestLimitOnClose      OrderTypeRequest = "LIMIT_ON_CLOSE"
)

func (e OrderTypeRequest) ToPointer() *OrderTypeRequest {
	return &e
}
func (e *OrderTypeRequest) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "MARKET":
		fallthrough
	case "LIMIT":
		fallthrough
	case "STOP":
		fallthrough
	case "STOP_LIMIT":
		fallthrough
	case "TRAILING_STOP":
		fallthrough
	case "CABINET":
		fallthrough
	case "NON_MARKETABLE":
		fallthrough
	case "MARKET_ON_CLOSE":
		fallthrough
	case "EXERCISE":
		fallthrough
	case "TRAILING_STOP_LIMIT":
		fallthrough
	case "NET_DEBIT":
		fallthrough
	case "NET_CREDIT":
		fallthrough
	case "NET_ZERO":
		fallthrough
	case "LIMIT_ON_CLOSE":
		*e = OrderTypeRequest(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OrderTypeRequest: %v", v)
	}
}
