// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type OrderLegType string

const (
	OrderLegTypeEquity               OrderLegType = "EQUITY"
	OrderLegTypeOption               OrderLegType = "OPTION"
	OrderLegTypeIndex                OrderLegType = "INDEX"
	OrderLegTypeMutualFund           OrderLegType = "MUTUAL_FUND"
	OrderLegTypeCashEquivalent       OrderLegType = "CASH_EQUIVALENT"
	OrderLegTypeFixedIncome          OrderLegType = "FIXED_INCOME"
	OrderLegTypeCurrency             OrderLegType = "CURRENCY"
	OrderLegTypeCollectiveInvestment OrderLegType = "COLLECTIVE_INVESTMENT"
)

func (e OrderLegType) ToPointer() *OrderLegType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *OrderLegType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EQUITY", "OPTION", "INDEX", "MUTUAL_FUND", "CASH_EQUIVALENT", "FIXED_INCOME", "CURRENCY", "COLLECTIVE_INVESTMENT":
			return true
		}
	}
	return false
}

type OrderLegCollectionPositionEffect string

const (
	OrderLegCollectionPositionEffectOpening   OrderLegCollectionPositionEffect = "OPENING"
	OrderLegCollectionPositionEffectClosing   OrderLegCollectionPositionEffect = "CLOSING"
	OrderLegCollectionPositionEffectAutomatic OrderLegCollectionPositionEffect = "AUTOMATIC"
)

func (e OrderLegCollectionPositionEffect) ToPointer() *OrderLegCollectionPositionEffect {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *OrderLegCollectionPositionEffect) IsExact() bool {
	if e != nil {
		switch *e {
		case "OPENING", "CLOSING", "AUTOMATIC":
			return true
		}
	}
	return false
}

type QuantityType string

const (
	QuantityTypeAllShares QuantityType = "ALL_SHARES"
	QuantityTypeDollars   QuantityType = "DOLLARS"
	QuantityTypeShares    QuantityType = "SHARES"
)

func (e QuantityType) ToPointer() *QuantityType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *QuantityType) IsExact() bool {
	if e != nil {
		switch *e {
		case "ALL_SHARES", "DOLLARS", "SHARES":
			return true
		}
	}
	return false
}

type DivCapGains string

const (
	DivCapGainsReinvest DivCapGains = "REINVEST"
	DivCapGainsPayout   DivCapGains = "PAYOUT"
)

func (e DivCapGains) ToPointer() *DivCapGains {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DivCapGains) IsExact() bool {
	if e != nil {
		switch *e {
		case "REINVEST", "PAYOUT":
			return true
		}
	}
	return false
}

type OrderLegCollection struct {
	OrderLegType   *OrderLegType                     `json:"orderLegType,omitzero"`
	LegID          *int64                            `json:"legId,omitzero"`
	Instrument     *AccountsInstrument               `json:"instrument,omitzero"`
	Instruction    *Instruction                      `json:"instruction,omitzero"`
	PositionEffect *OrderLegCollectionPositionEffect `json:"positionEffect,omitzero"`
	Quantity       *float64                          `json:"quantity,omitzero"`
	QuantityType   *QuantityType                     `json:"quantityType,omitzero"`
	DivCapGains    *DivCapGains                      `json:"divCapGains,omitzero"`
	ToSymbol       *string                           `json:"toSymbol,omitzero"`
}

func (o *OrderLegCollection) GetOrderLegType() *OrderLegType {
	if o == nil {
		return nil
	}
	return o.OrderLegType
}

func (o *OrderLegCollection) GetLegID() *int64 {
	if o == nil {
		return nil
	}
	return o.LegID
}

func (o *OrderLegCollection) GetInstrument() *AccountsInstrument {
	if o == nil {
		return nil
	}
	return o.Instrument
}

func (o *OrderLegCollection) GetInstrumentCashEquivalent() *AccountCashEquivalent {
	if v := o.GetInstrument(); v != nil {
		return v.AccountCashEquivalent
	}
	return nil
}

func (o *OrderLegCollection) GetInstrumentEquity() *AccountEquity {
	if v := o.GetInstrument(); v != nil {
		return v.AccountEquity
	}
	return nil
}

func (o *OrderLegCollection) GetInstrumentFixedIncome() *AccountFixedIncome {
	if v := o.GetInstrument(); v != nil {
		return v.AccountFixedIncome
	}
	return nil
}

func (o *OrderLegCollection) GetInstrumentMutualFund() *AccountMutualFund {
	if v := o.GetInstrument(); v != nil {
		return v.AccountMutualFund
	}
	return nil
}

func (o *OrderLegCollection) GetInstrumentOption() *AccountOption {
	if v := o.GetInstrument(); v != nil {
		return v.AccountOption
	}
	return nil
}

func (o *OrderLegCollection) GetInstruction() *Instruction {
	if o == nil {
		return nil
	}
	return o.Instruction
}

func (o *OrderLegCollection) GetPositionEffect() *OrderLegCollectionPositionEffect {
	if o == nil {
		return nil
	}
	return o.PositionEffect
}

func (o *OrderLegCollection) GetQuantity() *float64 {
	if o == nil {
		return nil
	}
	return o.Quantity
}

func (o *OrderLegCollection) GetQuantityType() *QuantityType {
	if o == nil {
		return nil
	}
	return o.QuantityType
}

func (o *OrderLegCollection) GetDivCapGains() *DivCapGains {
	if o == nil {
		return nil
	}
	return o.DivCapGains
}

func (o *OrderLegCollection) GetToSymbol() *string {
	if o == nil {
		return nil
	}
	return o.ToSymbol
}
