// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type OrderBalance struct {
	OrderValue             *float64 `json:"orderValue,omitzero"`
	ProjectedAvailableFund *float64 `json:"projectedAvailableFund,omitzero"`
	ProjectedBuyingPower   *float64 `json:"projectedBuyingPower,omitzero"`
	ProjectedCommission    *float64 `json:"projectedCommission,omitzero"`
}

func (o *OrderBalance) GetOrderValue() *float64 {
	if o == nil {
		return nil
	}
	return o.OrderValue
}

func (o *OrderBalance) GetProjectedAvailableFund() *float64 {
	if o == nil {
		return nil
	}
	return o.ProjectedAvailableFund
}

func (o *OrderBalance) GetProjectedBuyingPower() *float64 {
	if o == nil {
		return nil
	}
	return o.ProjectedBuyingPower
}

func (o *OrderBalance) GetProjectedCommission() *float64 {
	if o == nil {
		return nil
	}
	return o.ProjectedCommission
}
