// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type OrderType string

const (
	OrderTypeMarket            OrderType = "MARKET"
	OrderTypeLimit             OrderType = "LIMIT"
	OrderTypeStop              OrderType = "STOP"
	OrderTypeStopLimit         OrderType = "STOP_LIMIT"
	OrderTypeTrailingStop      OrderType = "TRAILING_STOP"
	OrderTypeCabinet           OrderType = "CABINET"
	OrderTypeNonMarketable     OrderType = "NON_MARKETABLE"
	OrderTypeMarketOnClose     OrderType = "MARKET_ON_CLOSE"
	OrderTypeExercise          OrderType = "EXERCISE"
	OrderTypeTrailingStopLimit OrderType = "TRAILING_STOP_LIMIT"
	OrderTypeNetDebit          OrderType = "NET_DEBIT"
	OrderTypeNetCredit         OrderType = "NET_CREDIT"
	OrderTypeNetZero           OrderType = "NET_ZERO"
	OrderTypeLimitOnClose      OrderType = "LIMIT_ON_CLOSE"
	OrderTypeUnknown           OrderType = "UNKNOWN"
)

func (e OrderType) ToPointer() *OrderType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *OrderType) IsExact() bool {
	if e != nil {
		switch *e {
		case "MARKET", "LIMIT", "STOP", "STOP_LIMIT", "TRAILING_STOP", "CABINET", "NON_MARKETABLE", "MARKET_ON_CLOSE", "EXERCISE", "TRAILING_STOP_LIMIT", "NET_DEBIT", "NET_CREDIT", "NET_ZERO", "LIMIT_ON_CLOSE", "UNKNOWN":
			return true
		}
	}
	return false
}
