// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"time"
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type Order struct {
	Session                  *Session                  `json:"session,omitzero"`
	Duration                 *Duration                 `json:"duration,omitzero"`
	OrderType                *OrderType                `json:"orderType,omitzero"`
	CancelTime               *time.Time                `json:"cancelTime,omitzero"`
	ComplexOrderStrategyType *ComplexOrderStrategyType `json:"complexOrderStrategyType,omitzero"`
	Quantity                 *float64                  `json:"quantity,omitzero"`
	FilledQuantity           *float64                  `json:"filledQuantity,omitzero"`
	RemainingQuantity        *float64                  `json:"remainingQuantity,omitzero"`
	RequestedDestination     *RequestedDestination     `json:"requestedDestination,omitzero"`
	DestinationLinkName      *string                   `json:"destinationLinkName,omitzero"`
	ReleaseTime              *time.Time                `json:"releaseTime,omitzero"`
	StopPrice                *float64                  `json:"stopPrice,omitzero"`
	StopPriceLinkBasis       *StopPriceLinkBasis       `json:"stopPriceLinkBasis,omitzero"`
	StopPriceLinkType        *StopPriceLinkType        `json:"stopPriceLinkType,omitzero"`
	StopPriceOffset          *float64                  `json:"stopPriceOffset,omitzero"`
	StopType                 *StopType                 `json:"stopType,omitzero"`
	PriceLinkBasis           *PriceLinkBasis           `json:"priceLinkBasis,omitzero"`
	PriceLinkType            *PriceLinkType            `json:"priceLinkType,omitzero"`
	Price                    *float64                  `json:"price,omitzero"`
	TaxLotMethod             *TaxLotMethod             `json:"taxLotMethod,omitzero"`
	OrderLegCollection       []OrderLegCollection      `json:"orderLegCollection,omitzero"`
	ActivationPrice          *float64                  `json:"activationPrice,omitzero"`
	SpecialInstruction       *SpecialInstruction       `json:"specialInstruction,omitzero"`
	OrderStrategyType        *OrderStrategyType        `json:"orderStrategyType,omitzero"`
	OrderID                  *int64                    `json:"orderId,omitzero"`
	Cancelable               *bool                     `default:"false" json:"cancelable"`
	Editable                 *bool                     `default:"false" json:"editable"`
	Status                   *Status                   `json:"status,omitzero"`
	EnteredTime              *time.Time                `json:"enteredTime,omitzero"`
	CloseTime                *time.Time                `json:"closeTime,omitzero"`
	Tag                      *string                   `json:"tag,omitzero"`
	AccountNumber            *int64                    `json:"accountNumber,omitzero"`
	OrderActivityCollection  []OrderActivity           `json:"orderActivityCollection,omitzero"`
	ReplacingOrderCollection []Order                   `json:"replacingOrderCollection,omitzero"`
	ChildOrderStrategies     []Order                   `json:"childOrderStrategies,omitzero"`
	StatusDescription        *string                   `json:"statusDescription,omitzero"`
}

func (o Order) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *Order) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *Order) GetSession() *Session {
	if o == nil {
		return nil
	}
	return o.Session
}

func (o *Order) GetDuration() *Duration {
	if o == nil {
		return nil
	}
	return o.Duration
}

func (o *Order) GetOrderType() *OrderType {
	if o == nil {
		return nil
	}
	return o.OrderType
}

func (o *Order) GetCancelTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.CancelTime
}

func (o *Order) GetComplexOrderStrategyType() *ComplexOrderStrategyType {
	if o == nil {
		return nil
	}
	return o.ComplexOrderStrategyType
}

func (o *Order) GetQuantity() *float64 {
	if o == nil {
		return nil
	}
	return o.Quantity
}

func (o *Order) GetFilledQuantity() *float64 {
	if o == nil {
		return nil
	}
	return o.FilledQuantity
}

func (o *Order) GetRemainingQuantity() *float64 {
	if o == nil {
		return nil
	}
	return o.RemainingQuantity
}

func (o *Order) GetRequestedDestination() *RequestedDestination {
	if o == nil {
		return nil
	}
	return o.RequestedDestination
}

func (o *Order) GetDestinationLinkName() *string {
	if o == nil {
		return nil
	}
	return o.DestinationLinkName
}

func (o *Order) GetReleaseTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.ReleaseTime
}

func (o *Order) GetStopPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.StopPrice
}

func (o *Order) GetStopPriceLinkBasis() *StopPriceLinkBasis {
	if o == nil {
		return nil
	}
	return o.StopPriceLinkBasis
}

func (o *Order) GetStopPriceLinkType() *StopPriceLinkType {
	if o == nil {
		return nil
	}
	return o.StopPriceLinkType
}

func (o *Order) GetStopPriceOffset() *float64 {
	if o == nil {
		return nil
	}
	return o.StopPriceOffset
}

func (o *Order) GetStopType() *StopType {
	if o == nil {
		return nil
	}
	return o.StopType
}

func (o *Order) GetPriceLinkBasis() *PriceLinkBasis {
	if o == nil {
		return nil
	}
	return o.PriceLinkBasis
}

func (o *Order) GetPriceLinkType() *PriceLinkType {
	if o == nil {
		return nil
	}
	return o.PriceLinkType
}

func (o *Order) GetPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.Price
}

func (o *Order) GetTaxLotMethod() *TaxLotMethod {
	if o == nil {
		return nil
	}
	return o.TaxLotMethod
}

func (o *Order) GetOrderLegCollection() []OrderLegCollection {
	if o == nil {
		return nil
	}
	return o.OrderLegCollection
}

func (o *Order) GetActivationPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.ActivationPrice
}

func (o *Order) GetSpecialInstruction() *SpecialInstruction {
	if o == nil {
		return nil
	}
	return o.SpecialInstruction
}

func (o *Order) GetOrderStrategyType() *OrderStrategyType {
	if o == nil {
		return nil
	}
	return o.OrderStrategyType
}

func (o *Order) GetOrderID() *int64 {
	if o == nil {
		return nil
	}
	return o.OrderID
}

func (o *Order) GetCancelable() *bool {
	if o == nil {
		return nil
	}
	return o.Cancelable
}

func (o *Order) GetEditable() *bool {
	if o == nil {
		return nil
	}
	return o.Editable
}

func (o *Order) GetStatus() *Status {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *Order) GetEnteredTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.EnteredTime
}

func (o *Order) GetCloseTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.CloseTime
}

func (o *Order) GetTag() *string {
	if o == nil {
		return nil
	}
	return o.Tag
}

func (o *Order) GetAccountNumber() *int64 {
	if o == nil {
		return nil
	}
	return o.AccountNumber
}

func (o *Order) GetOrderActivityCollection() []OrderActivity {
	if o == nil {
		return nil
	}
	return o.OrderActivityCollection
}

func (o *Order) GetReplacingOrderCollection() []Order {
	if o == nil {
		return nil
	}
	return o.ReplacingOrderCollection
}

func (o *Order) GetChildOrderStrategies() []Order {
	if o == nil {
		return nil
	}
	return o.ChildOrderStrategies
}

func (o *Order) GetStatusDescription() *string {
	if o == nil {
		return nil
	}
	return o.StatusDescription
}
