// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type PathParamMarket string

const (
	PathParamMarketEquity PathParamMarket = "equity"
	PathParamMarketOption PathParamMarket = "option"
	PathParamMarketBond   PathParamMarket = "bond"
	PathParamMarketFuture PathParamMarket = "future"
	PathParamMarketForex  PathParamMarket = "forex"
)

func (e PathParamMarket) ToPointer() *PathParamMarket {
	return &e
}
func (e *PathParamMarket) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "equity":
		fallthrough
	case "option":
		fallthrough
	case "bond":
		fallthrough
	case "future":
		fallthrough
	case "forex":
		*e = PathParamMarket(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PathParamMarket: %v", v)
	}
}
