// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type PathParamSymbol string

const (
	PathParamSymbolDollarDji   PathParamSymbol = "$DJI"
	PathParamSymbolDollarCompx PathParamSymbol = "$COMPX"
	PathParamSymbolDollarSpx   PathParamSymbol = "$SPX"
	PathParamSymbolNyse        PathParamSymbol = "NYSE"
	PathParamSymbolNasdaq      PathParamSymbol = "NASDAQ"
	PathParamSymbolOtcbb       PathParamSymbol = "OTCBB"
	PathParamSymbolIndexAll    PathParamSymbol = "INDEX_ALL"
	PathParamSymbolEquityAll   PathParamSymbol = "EQUITY_ALL"
	PathParamSymbolOptionAll   PathParamSymbol = "OPTION_ALL"
	PathParamSymbolOptionPut   PathParamSymbol = "OPTION_PUT"
	PathParamSymbolOptionCall  PathParamSymbol = "OPTION_CALL"
)

func (e PathParamSymbol) ToPointer() *PathParamSymbol {
	return &e
}
func (e *PathParamSymbol) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "$DJI":
		fallthrough
	case "$COMPX":
		fallthrough
	case "$SPX":
		fallthrough
	case "NYSE":
		fallthrough
	case "NASDAQ":
		fallthrough
	case "OTCBB":
		fallthrough
	case "INDEX_ALL":
		fallthrough
	case "EQUITY_ALL":
		fallthrough
	case "OPTION_ALL":
		fallthrough
	case "OPTION_PUT":
		fallthrough
	case "OPTION_CALL":
		*e = PathParamSymbol(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PathParamSymbol: %v", v)
	}
}
