// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

type Position struct {
	ShortQuantity                  *float64            `json:"shortQuantity,omitzero"`
	AveragePrice                   *float64            `json:"averagePrice,omitzero"`
	CurrentDayProfitLoss           *float64            `json:"currentDayProfitLoss,omitzero"`
	CurrentDayProfitLossPercentage *float64            `json:"currentDayProfitLossPercentage,omitzero"`
	LongQuantity                   *float64            `json:"longQuantity,omitzero"`
	SettledLongQuantity            *float64            `json:"settledLongQuantity,omitzero"`
	SettledShortQuantity           *float64            `json:"settledShortQuantity,omitzero"`
	AgedQuantity                   *float64            `json:"agedQuantity,omitzero"`
	Instrument                     *AccountsInstrument `json:"instrument,omitzero"`
	MarketValue                    *float64            `json:"marketValue,omitzero"`
	MaintenanceRequirement         *float64            `json:"maintenanceRequirement,omitzero"`
	AverageLongPrice               *float64            `json:"averageLongPrice,omitzero"`
	AverageShortPrice              *float64            `json:"averageShortPrice,omitzero"`
	TaxLotAverageLongPrice         *float64            `json:"taxLotAverageLongPrice,omitzero"`
	TaxLotAverageShortPrice        *float64            `json:"taxLotAverageShortPrice,omitzero"`
	LongOpenProfitLoss             *float64            `json:"longOpenProfitLoss,omitzero"`
	ShortOpenProfitLoss            *float64            `json:"shortOpenProfitLoss,omitzero"`
	PreviousSessionLongQuantity    *float64            `json:"previousSessionLongQuantity,omitzero"`
	PreviousSessionShortQuantity   *float64            `json:"previousSessionShortQuantity,omitzero"`
	CurrentDayCost                 *float64            `json:"currentDayCost,omitzero"`
}

func (p Position) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Position) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Position) GetShortQuantity() *float64 {
	if p == nil {
		return nil
	}
	return p.ShortQuantity
}

func (p *Position) GetAveragePrice() *float64 {
	if p == nil {
		return nil
	}
	return p.AveragePrice
}

func (p *Position) GetCurrentDayProfitLoss() *float64 {
	if p == nil {
		return nil
	}
	return p.CurrentDayProfitLoss
}

func (p *Position) GetCurrentDayProfitLossPercentage() *float64 {
	if p == nil {
		return nil
	}
	return p.CurrentDayProfitLossPercentage
}

func (p *Position) GetLongQuantity() *float64 {
	if p == nil {
		return nil
	}
	return p.LongQuantity
}

func (p *Position) GetSettledLongQuantity() *float64 {
	if p == nil {
		return nil
	}
	return p.SettledLongQuantity
}

func (p *Position) GetSettledShortQuantity() *float64 {
	if p == nil {
		return nil
	}
	return p.SettledShortQuantity
}

func (p *Position) GetAgedQuantity() *float64 {
	if p == nil {
		return nil
	}
	return p.AgedQuantity
}

func (p *Position) GetInstrument() *AccountsInstrument {
	if p == nil {
		return nil
	}
	return p.Instrument
}

func (p *Position) GetInstrumentCashEquivalent() *AccountCashEquivalent {
	if v := p.GetInstrument(); v != nil {
		return v.AccountCashEquivalent
	}
	return nil
}

func (p *Position) GetInstrumentEquity() *AccountsBaseInstrument {
	if v := p.GetInstrument(); v != nil {
		return v.AccountsBaseInstrument
	}
	return nil
}

func (p *Position) GetInstrumentFixedIncome() *AccountFixedIncome {
	if v := p.GetInstrument(); v != nil {
		return v.AccountFixedIncome
	}
	return nil
}

func (p *Position) GetInstrumentMutualFund() *AccountsBaseInstrument {
	if v := p.GetInstrument(); v != nil {
		return v.AccountsBaseInstrument
	}
	return nil
}

func (p *Position) GetInstrumentOption() *AccountOption {
	if v := p.GetInstrument(); v != nil {
		return v.AccountOption
	}
	return nil
}

func (p *Position) GetMarketValue() *float64 {
	if p == nil {
		return nil
	}
	return p.MarketValue
}

func (p *Position) GetMaintenanceRequirement() *float64 {
	if p == nil {
		return nil
	}
	return p.MaintenanceRequirement
}

func (p *Position) GetAverageLongPrice() *float64 {
	if p == nil {
		return nil
	}
	return p.AverageLongPrice
}

func (p *Position) GetAverageShortPrice() *float64 {
	if p == nil {
		return nil
	}
	return p.AverageShortPrice
}

func (p *Position) GetTaxLotAverageLongPrice() *float64 {
	if p == nil {
		return nil
	}
	return p.TaxLotAverageLongPrice
}

func (p *Position) GetTaxLotAverageShortPrice() *float64 {
	if p == nil {
		return nil
	}
	return p.TaxLotAverageShortPrice
}

func (p *Position) GetLongOpenProfitLoss() *float64 {
	if p == nil {
		return nil
	}
	return p.LongOpenProfitLoss
}

func (p *Position) GetShortOpenProfitLoss() *float64 {
	if p == nil {
		return nil
	}
	return p.ShortOpenProfitLoss
}

func (p *Position) GetPreviousSessionLongQuantity() *float64 {
	if p == nil {
		return nil
	}
	return p.PreviousSessionLongQuantity
}

func (p *Position) GetPreviousSessionShortQuantity() *float64 {
	if p == nil {
		return nil
	}
	return p.PreviousSessionShortQuantity
}

func (p *Position) GetCurrentDayCost() *float64 {
	if p == nil {
		return nil
	}
	return p.CurrentDayCost
}
