// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PriceLinkType string

const (
	PriceLinkTypeValue   PriceLinkType = "VALUE"
	PriceLinkTypePercent PriceLinkType = "PERCENT"
	PriceLinkTypeTick    PriceLinkType = "TICK"
)

func (e PriceLinkType) ToPointer() *PriceLinkType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PriceLinkType) IsExact() bool {
	if e != nil {
		switch *e {
		case "VALUE", "PERCENT", "TICK":
			return true
		}
	}
	return false
}
