// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PriceLinkBasis string

const (
	PriceLinkBasisManual  PriceLinkBasis = "MANUAL"
	PriceLinkBasisBase    PriceLinkBasis = "BASE"
	PriceLinkBasisTrigger PriceLinkBasis = "TRIGGER"
	PriceLinkBasisLast    PriceLinkBasis = "LAST"
	PriceLinkBasisBid     PriceLinkBasis = "BID"
	PriceLinkBasisAsk     PriceLinkBasis = "ASK"
	PriceLinkBasisAskBid  PriceLinkBasis = "ASK_BID"
	PriceLinkBasisMark    PriceLinkBasis = "MARK"
	PriceLinkBasisAverage PriceLinkBasis = "AVERAGE"
)

func (e PriceLinkBasis) ToPointer() *PriceLinkBasis {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PriceLinkBasis) IsExact() bool {
	if e != nil {
		switch *e {
		case "MANUAL", "BASE", "TRIGGER", "LAST", "BID", "ASK", "ASK_BID", "MARK", "AVERAGE":
			return true
		}
	}
	return false
}
