// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type ProductAssetType string

const (
	ProductAssetTypeEquity               ProductAssetType = "EQUITY"
	ProductAssetTypeOption               ProductAssetType = "OPTION"
	ProductAssetTypeIndex                ProductAssetType = "INDEX"
	ProductAssetTypeMutualFund           ProductAssetType = "MUTUAL_FUND"
	ProductAssetTypeCashEquivalent       ProductAssetType = "CASH_EQUIVALENT"
	ProductAssetTypeFixedIncome          ProductAssetType = "FIXED_INCOME"
	ProductAssetTypeCurrency             ProductAssetType = "CURRENCY"
	ProductAssetTypeCollectiveInvestment ProductAssetType = "COLLECTIVE_INVESTMENT"
)

func (e ProductAssetType) ToPointer() *ProductAssetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ProductAssetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EQUITY", "OPTION", "INDEX", "MUTUAL_FUND", "CASH_EQUIVALENT", "FIXED_INCOME", "CURRENCY", "COLLECTIVE_INVESTMENT":
			return true
		}
	}
	return false
}

type ProductType string

const (
	ProductTypeTbd     ProductType = "TBD"
	ProductTypeUnknown ProductType = "UNKNOWN"
)

func (e ProductType) ToPointer() *ProductType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ProductType) IsExact() bool {
	if e != nil {
		switch *e {
		case "TBD", "UNKNOWN":
			return true
		}
	}
	return false
}

type Product struct {
	AssetType    ProductAssetType `json:"assetType"`
	Cusip        *string          `json:"cusip,omitzero"`
	Symbol       *string          `json:"symbol,omitzero"`
	Description  *string          `json:"description,omitzero"`
	InstrumentID *int64           `json:"instrumentId,omitzero"`
	NetChange    *float64         `json:"netChange,omitzero"`
	Type         *ProductType     `json:"type,omitzero"`
}

func (p Product) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Product) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Product) GetAssetType() ProductAssetType {
	if p == nil {
		return ProductAssetType("")
	}
	return p.AssetType
}

func (p *Product) GetCusip() *string {
	if p == nil {
		return nil
	}
	return p.Cusip
}

func (p *Product) GetSymbol() *string {
	if p == nil {
		return nil
	}
	return p.Symbol
}

func (p *Product) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *Product) GetInstrumentID() *int64 {
	if p == nil {
		return nil
	}
	return p.InstrumentID
}

func (p *Product) GetNetChange() *float64 {
	if p == nil {
		return nil
	}
	return p.NetChange
}

func (p *Product) GetType() *ProductType {
	if p == nil {
		return nil
	}
	return p.Type
}
