// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type QueryParamperiodtype string

const (
	QueryParamperiodtypeDay   QueryParamperiodtype = "day"
	QueryParamperiodtypeMonth QueryParamperiodtype = "month"
	QueryParamperiodtypeYear  QueryParamperiodtype = "year"
	QueryParamperiodtypeYtd   QueryParamperiodtype = "ytd"
)

func (e QueryParamperiodtype) ToPointer() *QueryParamperiodtype {
	return &e
}
func (e *QueryParamperiodtype) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "day":
		fallthrough
	case "month":
		fallthrough
	case "year":
		fallthrough
	case "ytd":
		*e = QueryParamperiodtype(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamperiodtype: %v", v)
	}
}
