// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type QueryParamContractType string

const (
	QueryParamContractTypeCall QueryParamContractType = "CALL"
	QueryParamContractTypePut  QueryParamContractType = "PUT"
	QueryParamContractTypeAll  QueryParamContractType = "ALL"
)

func (e QueryParamContractType) ToPointer() *QueryParamContractType {
	return &e
}
func (e *QueryParamContractType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CALL":
		fallthrough
	case "PUT":
		fallthrough
	case "ALL":
		*e = QueryParamContractType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamContractType: %v", v)
	}
}
