// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type QueryParamStrategy string

const (
	QueryParamStrategySingle     QueryParamStrategy = "SINGLE"
	QueryParamStrategyAnalytical QueryParamStrategy = "ANALYTICAL"
	QueryParamStrategyCovered    QueryParamStrategy = "COVERED"
	QueryParamStrategyVertical   QueryParamStrategy = "VERTICAL"
	QueryParamStrategyCalendar   QueryParamStrategy = "CALENDAR"
	QueryParamStrategyStrangle   QueryParamStrategy = "STRANGLE"
	QueryParamStrategyStraddle   QueryParamStrategy = "STRADDLE"
	QueryParamStrategyButterfly  QueryParamStrategy = "BUTTERFLY"
	QueryParamStrategyCondor     QueryParamStrategy = "CONDOR"
	QueryParamStrategyDiagonal   QueryParamStrategy = "DIAGONAL"
	QueryParamStrategyCollar     QueryParamStrategy = "COLLAR"
	QueryParamStrategyRoll       QueryParamStrategy = "ROLL"
)

func (e QueryParamStrategy) ToPointer() *QueryParamStrategy {
	return &e
}
func (e *QueryParamStrategy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "SINGLE":
		fallthrough
	case "ANALYTICAL":
		fallthrough
	case "COVERED":
		fallthrough
	case "VERTICAL":
		fallthrough
	case "CALENDAR":
		fallthrough
	case "STRANGLE":
		fallthrough
	case "STRADDLE":
		fallthrough
	case "BUTTERFLY":
		fallthrough
	case "CONDOR":
		fallthrough
	case "DIAGONAL":
		fallthrough
	case "COLLAR":
		fallthrough
	case "ROLL":
		*e = QueryParamStrategy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamStrategy: %v", v)
	}
}
