// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type QueryParamfrequencytype string

const (
	QueryParamfrequencytypeMinute  QueryParamfrequencytype = "minute"
	QueryParamfrequencytypeDaily   QueryParamfrequencytype = "daily"
	QueryParamfrequencytypeWeekly  QueryParamfrequencytype = "weekly"
	QueryParamfrequencytypeMonthly QueryParamfrequencytype = "monthly"
)

func (e QueryParamfrequencytype) ToPointer() *QueryParamfrequencytype {
	return &e
}
func (e *QueryParamfrequencytype) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "minute":
		fallthrough
	case "daily":
		fallthrough
	case "weekly":
		fallthrough
	case "monthly":
		*e = QueryParamfrequencytype(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamfrequencytype: %v", v)
	}
}
