// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type QueryParamprojection string

const (
	QueryParamprojectionSymbolSearch QueryParamprojection = "symbol-search"
	QueryParamprojectionSymbolRegex  QueryParamprojection = "symbol-regex"
	QueryParamprojectionDescSearch   QueryParamprojection = "desc-search"
	QueryParamprojectionDescRegex    QueryParamprojection = "desc-regex"
	QueryParamprojectionSearch       QueryParamprojection = "search"
	QueryParamprojectionFundamental  QueryParamprojection = "fundamental"
)

func (e QueryParamprojection) ToPointer() *QueryParamprojection {
	return &e
}
func (e *QueryParamprojection) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "symbol-search":
		fallthrough
	case "symbol-regex":
		fallthrough
	case "desc-search":
		fallthrough
	case "desc-regex":
		fallthrough
	case "search":
		fallthrough
	case "fundamental":
		*e = QueryParamprojection(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamprojection: %v", v)
	}
}
