// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type QueryParamFrequency int

const (
	QueryParamFrequencyZero   QueryParamFrequency = 0
	QueryParamFrequencyOne    QueryParamFrequency = 1
	QueryParamFrequencyFive   QueryParamFrequency = 5
	QueryParamFrequencyTen    QueryParamFrequency = 10
	QueryParamFrequencyThirty QueryParamFrequency = 30
	QueryParamFrequencySixty  QueryParamFrequency = 60
)

func (e QueryParamFrequency) ToPointer() *QueryParamFrequency {
	return &e
}
func (e *QueryParamFrequency) UnmarshalJSON(data []byte) error {
	var v int
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 0:
		fallthrough
	case 1:
		fallthrough
	case 5:
		fallthrough
	case 10:
		fallthrough
	case 30:
		fallthrough
	case 60:
		*e = QueryParamFrequency(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamFrequency: %v", v)
	}
}
