// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type QueryParamMarkets string

const (
	QueryParamMarketsEquity QueryParamMarkets = "equity"
	QueryParamMarketsOption QueryParamMarkets = "option"
	QueryParamMarketsBond   QueryParamMarkets = "bond"
	QueryParamMarketsFuture QueryParamMarkets = "future"
	QueryParamMarketsForex  QueryParamMarkets = "forex"
)

func (e QueryParamMarkets) ToPointer() *QueryParamMarkets {
	return &e
}
func (e *QueryParamMarkets) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "equity":
		fallthrough
	case "option":
		fallthrough
	case "bond":
		fallthrough
	case "future":
		fallthrough
	case "forex":
		*e = QueryParamMarkets(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamMarkets: %v", v)
	}
}
