// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type QueryParamSort string

const (
	QueryParamSortVolume            QueryParamSort = "VOLUME"
	QueryParamSortTrades            QueryParamSort = "TRADES"
	QueryParamSortPercentChangeUp   QueryParamSort = "PERCENT_CHANGE_UP"
	QueryParamSortPercentChangeDown QueryParamSort = "PERCENT_CHANGE_DOWN"
)

func (e QueryParamSort) ToPointer() *QueryParamSort {
	return &e
}
func (e *QueryParamSort) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "VOLUME":
		fallthrough
	case "TRADES":
		fallthrough
	case "PERCENT_CHANGE_UP":
		fallthrough
	case "PERCENT_CHANGE_DOWN":
		*e = QueryParamSort(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamSort: %v", v)
	}
}
