// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type QueryParamExpMonth string

const (
	QueryParamExpMonthJan QueryParamExpMonth = "JAN"
	QueryParamExpMonthFeb QueryParamExpMonth = "FEB"
	QueryParamExpMonthMar QueryParamExpMonth = "MAR"
	QueryParamExpMonthApr QueryParamExpMonth = "APR"
	QueryParamExpMonthMay QueryParamExpMonth = "MAY"
	QueryParamExpMonthJun QueryParamExpMonth = "JUN"
	QueryParamExpMonthJul QueryParamExpMonth = "JUL"
	QueryParamExpMonthAug QueryParamExpMonth = "AUG"
	QueryParamExpMonthSep QueryParamExpMonth = "SEP"
	QueryParamExpMonthOct QueryParamExpMonth = "OCT"
	QueryParamExpMonthNov QueryParamExpMonth = "NOV"
	QueryParamExpMonthDec QueryParamExpMonth = "DEC"
	QueryParamExpMonthAll QueryParamExpMonth = "ALL"
)

func (e QueryParamExpMonth) ToPointer() *QueryParamExpMonth {
	return &e
}
func (e *QueryParamExpMonth) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "JAN":
		fallthrough
	case "FEB":
		fallthrough
	case "MAR":
		fallthrough
	case "APR":
		fallthrough
	case "MAY":
		fallthrough
	case "JUN":
		fallthrough
	case "JUL":
		fallthrough
	case "AUG":
		fallthrough
	case "SEP":
		fallthrough
	case "OCT":
		fallthrough
	case "NOV":
		fallthrough
	case "DEC":
		fallthrough
	case "ALL":
		*e = QueryParamExpMonth(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamExpMonth: %v", v)
	}
}
