// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

// QuoteError - Partial or Custom errors per request
type QuoteError struct {
	// list of invalid cusips from request
	InvalidCusips []string `json:"invalidCusips,omitzero"`
	// list of invalid SSIDs from request
	InvalidSSIDs []int64 `json:"invalidSSIDs,omitzero"`
	// list of invalid symbols from request
	InvalidSymbols []string `json:"invalidSymbols,omitzero"`
}

func (q QuoteError) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QuoteError) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QuoteError) GetInvalidCusips() []string {
	if q == nil {
		return nil
	}
	return q.InvalidCusips
}

func (q *QuoteError) GetInvalidSSIDs() []int64 {
	if q == nil {
		return nil
	}
	return q.InvalidSSIDs
}

func (q *QuoteError) GetInvalidSymbols() []string {
	if q == nil {
		return nil
	}
	return q.InvalidSymbols
}
