// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

// QuoteFuture - Quote data of Future security
type QuoteFuture struct {
	// ask MIC code
	AskMICID *string `json:"askMICId,omitzero"`
	// Current Best Ask Price
	AskPrice *float64 `json:"askPrice,omitzero"`
	// Number of shares for ask
	AskSize *int `json:"askSize,omitzero"`
	// Last ask time in milliseconds since Epoch
	AskTime *int64 `json:"askTime,omitzero"`
	// bid MIC code
	BidMICID *string `json:"bidMICId,omitzero"`
	// Current Best Bid Price
	BidPrice *float64 `json:"bidPrice,omitzero"`
	// Number of shares for bid
	BidSize *int `json:"bidSize,omitzero"`
	// Last bid time in milliseconds since Epoch
	BidTime *int64 `json:"bidTime,omitzero"`
	// Previous day's closing price
	ClosePrice *float64 `json:"closePrice,omitzero"`
	// Net Percentage Change
	FuturePercentChange *float64 `json:"futurePercentChange,omitzero"`
	// Day's high trade price
	HighPrice *float64 `json:"highPrice,omitzero"`
	// Last MIC Code
	LastMICID *string  `json:"lastMICId,omitzero"`
	LastPrice *float64 `json:"lastPrice,omitzero"`
	// Number of shares traded with last trade
	LastSize *int `json:"lastSize,omitzero"`
	// Day's low trade price
	LowPrice *float64 `json:"lowPrice,omitzero"`
	// Mark price
	Mark *float64 `json:"mark,omitzero"`
	// Current Last-Prev Close
	NetChange *float64 `json:"netChange,omitzero"`
	// Open interest
	OpenInterest *int `json:"openInterest,omitzero"`
	// Price at market open
	OpenPrice *float64 `json:"openPrice,omitzero"`
	// Last quote time in milliseconds since Epoch
	QuoteTime *int64 `json:"quoteTime,omitzero"`
	// quoted during trading session
	QuotedInSession *bool `json:"quotedInSession,omitzero"`
	// Status of security
	SecurityStatus *string `json:"securityStatus,omitzero"`
	// settlement time in milliseconds since Epoch
	SettleTime *int64 `json:"settleTime,omitzero"`
	// Tick Price
	Tick *float64 `json:"tick,omitzero"`
	// Tick Amount
	TickAmount *float64 `json:"tickAmount,omitzero"`
	// Aggregated shares traded throughout the day, including pre/post market hours.
	TotalVolume *int64 `json:"totalVolume,omitzero"`
	// Last trade time in milliseconds since Epoch
	TradeTime *int64 `json:"tradeTime,omitzero"`
}

func (q QuoteFuture) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QuoteFuture) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QuoteFuture) GetAskMICID() *string {
	if q == nil {
		return nil
	}
	return q.AskMICID
}

func (q *QuoteFuture) GetAskPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.AskPrice
}

func (q *QuoteFuture) GetAskSize() *int {
	if q == nil {
		return nil
	}
	return q.AskSize
}

func (q *QuoteFuture) GetAskTime() *int64 {
	if q == nil {
		return nil
	}
	return q.AskTime
}

func (q *QuoteFuture) GetBidMICID() *string {
	if q == nil {
		return nil
	}
	return q.BidMICID
}

func (q *QuoteFuture) GetBidPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.BidPrice
}

func (q *QuoteFuture) GetBidSize() *int {
	if q == nil {
		return nil
	}
	return q.BidSize
}

func (q *QuoteFuture) GetBidTime() *int64 {
	if q == nil {
		return nil
	}
	return q.BidTime
}

func (q *QuoteFuture) GetClosePrice() *float64 {
	if q == nil {
		return nil
	}
	return q.ClosePrice
}

func (q *QuoteFuture) GetFuturePercentChange() *float64 {
	if q == nil {
		return nil
	}
	return q.FuturePercentChange
}

func (q *QuoteFuture) GetHighPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.HighPrice
}

func (q *QuoteFuture) GetLastMICID() *string {
	if q == nil {
		return nil
	}
	return q.LastMICID
}

func (q *QuoteFuture) GetLastPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.LastPrice
}

func (q *QuoteFuture) GetLastSize() *int {
	if q == nil {
		return nil
	}
	return q.LastSize
}

func (q *QuoteFuture) GetLowPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.LowPrice
}

func (q *QuoteFuture) GetMark() *float64 {
	if q == nil {
		return nil
	}
	return q.Mark
}

func (q *QuoteFuture) GetNetChange() *float64 {
	if q == nil {
		return nil
	}
	return q.NetChange
}

func (q *QuoteFuture) GetOpenInterest() *int {
	if q == nil {
		return nil
	}
	return q.OpenInterest
}

func (q *QuoteFuture) GetOpenPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.OpenPrice
}

func (q *QuoteFuture) GetQuoteTime() *int64 {
	if q == nil {
		return nil
	}
	return q.QuoteTime
}

func (q *QuoteFuture) GetQuotedInSession() *bool {
	if q == nil {
		return nil
	}
	return q.QuotedInSession
}

func (q *QuoteFuture) GetSecurityStatus() *string {
	if q == nil {
		return nil
	}
	return q.SecurityStatus
}

func (q *QuoteFuture) GetSettleTime() *int64 {
	if q == nil {
		return nil
	}
	return q.SettleTime
}

func (q *QuoteFuture) GetTick() *float64 {
	if q == nil {
		return nil
	}
	return q.Tick
}

func (q *QuoteFuture) GetTickAmount() *float64 {
	if q == nil {
		return nil
	}
	return q.TickAmount
}

func (q *QuoteFuture) GetTotalVolume() *int64 {
	if q == nil {
		return nil
	}
	return q.TotalVolume
}

func (q *QuoteFuture) GetTradeTime() *int64 {
	if q == nil {
		return nil
	}
	return q.TradeTime
}
