// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

// QuoteMutualFund - Quote data of Mutual Fund security
type QuoteMutualFund struct {
	// Higest price traded in the past 12 months, or 52 weeks
	FiftyTwoWeekHigh *float64 `json:"52WeekHigh,omitzero"`
	// Lowest price traded in the past 12 months, or 52 weeks
	FiftyTwoWeekLow *float64 `json:"52WeekLow,omitzero"`
	// Previous day's closing price
	ClosePrice *float64 `json:"closePrice,omitzero"`
	// Net Asset Value
	NAV *float64 `json:"nAV,omitzero"`
	// Current Last-Prev Close
	NetChange *float64 `json:"netChange,omitzero"`
	// Net Percentage Change
	NetPercentChange *float64 `json:"netPercentChange,omitzero"`
	// Status of security
	SecurityStatus *string `json:"securityStatus,omitzero"`
	// Aggregated shares traded throughout the day, including pre/post market hours.
	TotalVolume *int64 `json:"totalVolume,omitzero"`
	// Last trade time in milliseconds since Epoch
	TradeTime *int64 `json:"tradeTime,omitzero"`
}

func (q QuoteMutualFund) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QuoteMutualFund) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QuoteMutualFund) GetFiftyTwoWeekHigh() *float64 {
	if q == nil {
		return nil
	}
	return q.FiftyTwoWeekHigh
}

func (q *QuoteMutualFund) GetFiftyTwoWeekLow() *float64 {
	if q == nil {
		return nil
	}
	return q.FiftyTwoWeekLow
}

func (q *QuoteMutualFund) GetClosePrice() *float64 {
	if q == nil {
		return nil
	}
	return q.ClosePrice
}

func (q *QuoteMutualFund) GetNAV() *float64 {
	if q == nil {
		return nil
	}
	return q.NAV
}

func (q *QuoteMutualFund) GetNetChange() *float64 {
	if q == nil {
		return nil
	}
	return q.NetChange
}

func (q *QuoteMutualFund) GetNetPercentChange() *float64 {
	if q == nil {
		return nil
	}
	return q.NetPercentChange
}

func (q *QuoteMutualFund) GetSecurityStatus() *string {
	if q == nil {
		return nil
	}
	return q.SecurityStatus
}

func (q *QuoteMutualFund) GetTotalVolume() *int64 {
	if q == nil {
		return nil
	}
	return q.TotalVolume
}

func (q *QuoteMutualFund) GetTradeTime() *int64 {
	if q == nil {
		return nil
	}
	return q.TradeTime
}
