// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"undefined/internal/utils"
)

type QuoteResponseObjectType string

const (
	QuoteResponseObjectTypeEquityResponse       QuoteResponseObjectType = "EquityResponse"
	QuoteResponseObjectTypeOptionResponse       QuoteResponseObjectType = "OptionResponse"
	QuoteResponseObjectTypeForexResponse        QuoteResponseObjectType = "ForexResponse"
	QuoteResponseObjectTypeFutureResponse       QuoteResponseObjectType = "FutureResponse"
	QuoteResponseObjectTypeFutureOptionResponse QuoteResponseObjectType = "FutureOptionResponse"
	QuoteResponseObjectTypeIndexResponse        QuoteResponseObjectType = "IndexResponse"
	QuoteResponseObjectTypeMutualFundResponse   QuoteResponseObjectType = "MutualFundResponse"
	QuoteResponseObjectTypeQuoteError           QuoteResponseObjectType = "QuoteError"
)

type QuoteResponseObject struct {
	EquityResponse       *EquityResponse       `queryParam:"inline" union:"member"`
	OptionResponse       *OptionResponse       `queryParam:"inline" union:"member"`
	ForexResponse        *ForexResponse        `queryParam:"inline" union:"member"`
	FutureResponse       *FutureResponse       `queryParam:"inline" union:"member"`
	FutureOptionResponse *FutureOptionResponse `queryParam:"inline" union:"member"`
	IndexResponse        *IndexResponse        `queryParam:"inline" union:"member"`
	MutualFundResponse   *MutualFundResponse   `queryParam:"inline" union:"member"`
	QuoteError           *QuoteError           `queryParam:"inline" union:"member"`

	Type QuoteResponseObjectType
}

func CreateQuoteResponseObjectEquityResponse(equityResponse EquityResponse) QuoteResponseObject {
	typ := QuoteResponseObjectTypeEquityResponse

	return QuoteResponseObject{
		EquityResponse: &equityResponse,
		Type:           typ,
	}
}

func CreateQuoteResponseObjectOptionResponse(optionResponse OptionResponse) QuoteResponseObject {
	typ := QuoteResponseObjectTypeOptionResponse

	return QuoteResponseObject{
		OptionResponse: &optionResponse,
		Type:           typ,
	}
}

func CreateQuoteResponseObjectForexResponse(forexResponse ForexResponse) QuoteResponseObject {
	typ := QuoteResponseObjectTypeForexResponse

	return QuoteResponseObject{
		ForexResponse: &forexResponse,
		Type:          typ,
	}
}

func CreateQuoteResponseObjectFutureResponse(futureResponse FutureResponse) QuoteResponseObject {
	typ := QuoteResponseObjectTypeFutureResponse

	return QuoteResponseObject{
		FutureResponse: &futureResponse,
		Type:           typ,
	}
}

func CreateQuoteResponseObjectFutureOptionResponse(futureOptionResponse FutureOptionResponse) QuoteResponseObject {
	typ := QuoteResponseObjectTypeFutureOptionResponse

	return QuoteResponseObject{
		FutureOptionResponse: &futureOptionResponse,
		Type:                 typ,
	}
}

func CreateQuoteResponseObjectIndexResponse(indexResponse IndexResponse) QuoteResponseObject {
	typ := QuoteResponseObjectTypeIndexResponse

	return QuoteResponseObject{
		IndexResponse: &indexResponse,
		Type:          typ,
	}
}

func CreateQuoteResponseObjectMutualFundResponse(mutualFundResponse MutualFundResponse) QuoteResponseObject {
	typ := QuoteResponseObjectTypeMutualFundResponse

	return QuoteResponseObject{
		MutualFundResponse: &mutualFundResponse,
		Type:               typ,
	}
}

func CreateQuoteResponseObjectQuoteError(quoteError QuoteError) QuoteResponseObject {
	typ := QuoteResponseObjectTypeQuoteError

	return QuoteResponseObject{
		QuoteError: &quoteError,
		Type:       typ,
	}
}

func (u *QuoteResponseObject) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var equityResponse EquityResponse = EquityResponse{}
	if err := utils.UnmarshalJSON(data, &equityResponse, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  QuoteResponseObjectTypeEquityResponse,
			Value: &equityResponse,
		})
	}

	var optionResponse OptionResponse = OptionResponse{}
	if err := utils.UnmarshalJSON(data, &optionResponse, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  QuoteResponseObjectTypeOptionResponse,
			Value: &optionResponse,
		})
	}

	var forexResponse ForexResponse = ForexResponse{}
	if err := utils.UnmarshalJSON(data, &forexResponse, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  QuoteResponseObjectTypeForexResponse,
			Value: &forexResponse,
		})
	}

	var futureResponse FutureResponse = FutureResponse{}
	if err := utils.UnmarshalJSON(data, &futureResponse, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  QuoteResponseObjectTypeFutureResponse,
			Value: &futureResponse,
		})
	}

	var futureOptionResponse FutureOptionResponse = FutureOptionResponse{}
	if err := utils.UnmarshalJSON(data, &futureOptionResponse, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  QuoteResponseObjectTypeFutureOptionResponse,
			Value: &futureOptionResponse,
		})
	}

	var indexResponse IndexResponse = IndexResponse{}
	if err := utils.UnmarshalJSON(data, &indexResponse, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  QuoteResponseObjectTypeIndexResponse,
			Value: &indexResponse,
		})
	}

	var mutualFundResponse MutualFundResponse = MutualFundResponse{}
	if err := utils.UnmarshalJSON(data, &mutualFundResponse, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  QuoteResponseObjectTypeMutualFundResponse,
			Value: &mutualFundResponse,
		})
	}

	var quoteError QuoteError = QuoteError{}
	if err := utils.UnmarshalJSON(data, &quoteError, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  QuoteResponseObjectTypeQuoteError,
			Value: &quoteError,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for QuoteResponseObject", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for QuoteResponseObject", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(QuoteResponseObjectType)
	switch best.Type {
	case QuoteResponseObjectTypeEquityResponse:
		u.EquityResponse = best.Value.(*EquityResponse)
		return nil
	case QuoteResponseObjectTypeOptionResponse:
		u.OptionResponse = best.Value.(*OptionResponse)
		return nil
	case QuoteResponseObjectTypeForexResponse:
		u.ForexResponse = best.Value.(*ForexResponse)
		return nil
	case QuoteResponseObjectTypeFutureResponse:
		u.FutureResponse = best.Value.(*FutureResponse)
		return nil
	case QuoteResponseObjectTypeFutureOptionResponse:
		u.FutureOptionResponse = best.Value.(*FutureOptionResponse)
		return nil
	case QuoteResponseObjectTypeIndexResponse:
		u.IndexResponse = best.Value.(*IndexResponse)
		return nil
	case QuoteResponseObjectTypeMutualFundResponse:
		u.MutualFundResponse = best.Value.(*MutualFundResponse)
		return nil
	case QuoteResponseObjectTypeQuoteError:
		u.QuoteError = best.Value.(*QuoteError)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for QuoteResponseObject", string(data))
}

func (u QuoteResponseObject) MarshalJSON() ([]byte, error) {
	if u.EquityResponse != nil {
		return utils.MarshalJSON(u.EquityResponse, "", true)
	}

	if u.OptionResponse != nil {
		return utils.MarshalJSON(u.OptionResponse, "", true)
	}

	if u.ForexResponse != nil {
		return utils.MarshalJSON(u.ForexResponse, "", true)
	}

	if u.FutureResponse != nil {
		return utils.MarshalJSON(u.FutureResponse, "", true)
	}

	if u.FutureOptionResponse != nil {
		return utils.MarshalJSON(u.FutureOptionResponse, "", true)
	}

	if u.IndexResponse != nil {
		return utils.MarshalJSON(u.IndexResponse, "", true)
	}

	if u.MutualFundResponse != nil {
		return utils.MarshalJSON(u.MutualFundResponse, "", true)
	}

	if u.QuoteError != nil {
		return utils.MarshalJSON(u.QuoteError, "", true)
	}

	return nil, errors.New("could not marshal union type QuoteResponseObject: all fields are null")
}
