// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

// QuoteFutureOption - Quote data of Option security
type QuoteFutureOption struct {
	// ask MIC code
	AskMICID *string `json:"askMICId,omitzero"`
	// Current Best Ask Price
	AskPrice *float64 `json:"askPrice,omitzero"`
	// Number of shares for ask
	AskSize *int `json:"askSize,omitzero"`
	// bid MIC code
	BidMICID *string `json:"bidMICId,omitzero"`
	// Current Best Bid Price
	BidPrice *float64 `json:"bidPrice,omitzero"`
	// Number of shares for bid
	BidSize *int `json:"bidSize,omitzero"`
	// Previous day's closing price
	ClosePrice *float64 `json:"closePrice,omitzero"`
	// Day's high trade price
	HighPrice *float64 `json:"highPrice,omitzero"`
	// Last MIC Code
	LastMICID *string  `json:"lastMICId,omitzero"`
	LastPrice *float64 `json:"lastPrice,omitzero"`
	// Number of shares traded with last trade
	LastSize *int `json:"lastSize,omitzero"`
	// Day's low trade price
	LowPrice *float64 `json:"lowPrice,omitzero"`
	// Mark price
	Mark *float64 `json:"mark,omitzero"`
	// Mark Price change
	MarkChange *float64 `json:"markChange,omitzero"`
	// Current Last-Prev Close
	NetChange *float64 `json:"netChange,omitzero"`
	// Net Percentage Change
	NetPercentChange *float64 `json:"netPercentChange,omitzero"`
	// Open Interest
	OpenInterest *int `json:"openInterest,omitzero"`
	// Price at market open
	OpenPrice *float64 `json:"openPrice,omitzero"`
	// Last quote time in milliseconds since Epoch
	QuoteTime *int64 `json:"quoteTime,omitzero"`
	// Status of security
	SecurityStatus *string `json:"securityStatus,omitzero"`
	// Price at market open
	SettlemetPrice *float64 `json:"settlemetPrice,omitzero"`
	// Tick Price
	Tick *float64 `json:"tick,omitzero"`
	// Tick Amount
	TickAmount *float64 `json:"tickAmount,omitzero"`
	// Aggregated shares traded throughout the day, including pre/post market hours.
	TotalVolume *int64 `json:"totalVolume,omitzero"`
	// Last trade time in milliseconds since Epoch
	TradeTime *int64 `json:"tradeTime,omitzero"`
}

func (q QuoteFutureOption) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QuoteFutureOption) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QuoteFutureOption) GetAskMICID() *string {
	if q == nil {
		return nil
	}
	return q.AskMICID
}

func (q *QuoteFutureOption) GetAskPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.AskPrice
}

func (q *QuoteFutureOption) GetAskSize() *int {
	if q == nil {
		return nil
	}
	return q.AskSize
}

func (q *QuoteFutureOption) GetBidMICID() *string {
	if q == nil {
		return nil
	}
	return q.BidMICID
}

func (q *QuoteFutureOption) GetBidPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.BidPrice
}

func (q *QuoteFutureOption) GetBidSize() *int {
	if q == nil {
		return nil
	}
	return q.BidSize
}

func (q *QuoteFutureOption) GetClosePrice() *float64 {
	if q == nil {
		return nil
	}
	return q.ClosePrice
}

func (q *QuoteFutureOption) GetHighPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.HighPrice
}

func (q *QuoteFutureOption) GetLastMICID() *string {
	if q == nil {
		return nil
	}
	return q.LastMICID
}

func (q *QuoteFutureOption) GetLastPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.LastPrice
}

func (q *QuoteFutureOption) GetLastSize() *int {
	if q == nil {
		return nil
	}
	return q.LastSize
}

func (q *QuoteFutureOption) GetLowPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.LowPrice
}

func (q *QuoteFutureOption) GetMark() *float64 {
	if q == nil {
		return nil
	}
	return q.Mark
}

func (q *QuoteFutureOption) GetMarkChange() *float64 {
	if q == nil {
		return nil
	}
	return q.MarkChange
}

func (q *QuoteFutureOption) GetNetChange() *float64 {
	if q == nil {
		return nil
	}
	return q.NetChange
}

func (q *QuoteFutureOption) GetNetPercentChange() *float64 {
	if q == nil {
		return nil
	}
	return q.NetPercentChange
}

func (q *QuoteFutureOption) GetOpenInterest() *int {
	if q == nil {
		return nil
	}
	return q.OpenInterest
}

func (q *QuoteFutureOption) GetOpenPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.OpenPrice
}

func (q *QuoteFutureOption) GetQuoteTime() *int64 {
	if q == nil {
		return nil
	}
	return q.QuoteTime
}

func (q *QuoteFutureOption) GetSecurityStatus() *string {
	if q == nil {
		return nil
	}
	return q.SecurityStatus
}

func (q *QuoteFutureOption) GetSettlemetPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.SettlemetPrice
}

func (q *QuoteFutureOption) GetTick() *float64 {
	if q == nil {
		return nil
	}
	return q.Tick
}

func (q *QuoteFutureOption) GetTickAmount() *float64 {
	if q == nil {
		return nil
	}
	return q.TickAmount
}

func (q *QuoteFutureOption) GetTotalVolume() *int64 {
	if q == nil {
		return nil
	}
	return q.TotalVolume
}

func (q *QuoteFutureOption) GetTradeTime() *int64 {
	if q == nil {
		return nil
	}
	return q.TradeTime
}
