// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

// QuoteIndex - Quote data of Index security
type QuoteIndex struct {
	// Higest price traded in the past 12 months, or 52 weeks
	FiftyTwoWeekHigh *float64 `json:"52WeekHigh,omitzero"`
	// Lowest price traded in the past 12 months, or 52 weeks
	FiftyTwoWeekLow *float64 `json:"52WeekLow,omitzero"`
	// Previous day's closing price
	ClosePrice *float64 `json:"closePrice,omitzero"`
	// Day's high trade price
	HighPrice *float64 `json:"highPrice,omitzero"`
	LastPrice *float64 `json:"lastPrice,omitzero"`
	// Day's low trade price
	LowPrice *float64 `json:"lowPrice,omitzero"`
	// Current Last-Prev Close
	NetChange *float64 `json:"netChange,omitzero"`
	// Net Percentage Change
	NetPercentChange *float64 `json:"netPercentChange,omitzero"`
	// Price at market open
	OpenPrice *float64 `json:"openPrice,omitzero"`
	// Status of security
	SecurityStatus *string `json:"securityStatus,omitzero"`
	// Aggregated shares traded throughout the day, including pre/post market hours.
	TotalVolume *int64 `json:"totalVolume,omitzero"`
	// Last trade time in milliseconds since Epoch
	TradeTime *int64 `json:"tradeTime,omitzero"`
}

func (q QuoteIndex) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QuoteIndex) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QuoteIndex) GetFiftyTwoWeekHigh() *float64 {
	if q == nil {
		return nil
	}
	return q.FiftyTwoWeekHigh
}

func (q *QuoteIndex) GetFiftyTwoWeekLow() *float64 {
	if q == nil {
		return nil
	}
	return q.FiftyTwoWeekLow
}

func (q *QuoteIndex) GetClosePrice() *float64 {
	if q == nil {
		return nil
	}
	return q.ClosePrice
}

func (q *QuoteIndex) GetHighPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.HighPrice
}

func (q *QuoteIndex) GetLastPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.LastPrice
}

func (q *QuoteIndex) GetLowPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.LowPrice
}

func (q *QuoteIndex) GetNetChange() *float64 {
	if q == nil {
		return nil
	}
	return q.NetChange
}

func (q *QuoteIndex) GetNetPercentChange() *float64 {
	if q == nil {
		return nil
	}
	return q.NetPercentChange
}

func (q *QuoteIndex) GetOpenPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.OpenPrice
}

func (q *QuoteIndex) GetSecurityStatus() *string {
	if q == nil {
		return nil
	}
	return q.SecurityStatus
}

func (q *QuoteIndex) GetTotalVolume() *int64 {
	if q == nil {
		return nil
	}
	return q.TotalVolume
}

func (q *QuoteIndex) GetTradeTime() *int64 {
	if q == nil {
		return nil
	}
	return q.TradeTime
}
