// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

// QuoteOption - Quote data of Option security
type QuoteOption struct {
	// Higest price traded in the past 12 months, or 52 weeks
	FiftyTwoWeekHigh *float64 `json:"52WeekHigh,omitzero"`
	// Lowest price traded in the past 12 months, or 52 weeks
	FiftyTwoWeekLow *float64 `json:"52WeekLow,omitzero"`
	// Current Best Ask Price
	AskPrice *float64 `json:"askPrice,omitzero"`
	// Number of shares for ask
	AskSize *int `json:"askSize,omitzero"`
	// Current Best Bid Price
	BidPrice *float64 `json:"bidPrice,omitzero"`
	// Number of shares for bid
	BidSize *int `json:"bidSize,omitzero"`
	// Previous day's closing price
	ClosePrice *float64 `json:"closePrice,omitzero"`
	// Delta Value
	Delta *float64 `json:"delta,omitzero"`
	// Gamma Value
	Gamma *float64 `json:"gamma,omitzero"`
	// Day's high trade price
	HighPrice *float64 `json:"highPrice,omitzero"`
	// Indicative Ask Price applicable only for Indicative Option Symbols
	IndAskPrice *float64 `json:"indAskPrice,omitzero"`
	// Indicative Bid Price applicable only for Indicative Option Symbols
	IndBidPrice *float64 `json:"indBidPrice,omitzero"`
	// Indicative Quote Time in milliseconds since Epoch applicable only for Indicative Option Symbols
	IndQuoteTime *int64 `json:"indQuoteTime,omitzero"`
	// Implied Yield
	ImpliedYield *float64 `json:"impliedYield,omitzero"`
	LastPrice    *float64 `json:"lastPrice,omitzero"`
	// Number of shares traded with last trade
	LastSize *int `json:"lastSize,omitzero"`
	// Day's low trade price
	LowPrice *float64 `json:"lowPrice,omitzero"`
	// Mark price
	Mark *float64 `json:"mark,omitzero"`
	// Mark Price change
	MarkChange *float64 `json:"markChange,omitzero"`
	// Mark Price percent change
	MarkPercentChange *float64 `json:"markPercentChange,omitzero"`
	// Money Intrinsic Value
	MoneyIntrinsicValue *float64 `json:"moneyIntrinsicValue,omitzero"`
	// Current Last-Prev Close
	NetChange *float64 `json:"netChange,omitzero"`
	// Net Percentage Change
	NetPercentChange *float64 `json:"netPercentChange,omitzero"`
	// Open Interest
	OpenInterest *float64 `json:"openInterest,omitzero"`
	// Price at market open
	OpenPrice *float64 `json:"openPrice,omitzero"`
	// Last quote time in milliseconds since Epoch
	QuoteTime *int64 `json:"quoteTime,omitzero"`
	// Rho Value
	Rho *float64 `json:"rho,omitzero"`
	// Status of security
	SecurityStatus *string `json:"securityStatus,omitzero"`
	// Theoretical option Value
	TheoreticalOptionValue *float64 `json:"theoreticalOptionValue,omitzero"`
	// Theta Value
	Theta *float64 `json:"theta,omitzero"`
	// Time Value
	TimeValue *float64 `json:"timeValue,omitzero"`
	// Aggregated shares traded throughout the day, including pre/post market hours.
	TotalVolume *int64 `json:"totalVolume,omitzero"`
	// Last trade time in milliseconds since Epoch
	TradeTime *int64 `json:"tradeTime,omitzero"`
	// Underlying Price
	UnderlyingPrice *float64 `json:"underlyingPrice,omitzero"`
	// Vega Value
	Vega *float64 `json:"vega,omitzero"`
	// Option Risk/Volatility Measurement
	Volatility *float64 `json:"volatility,omitzero"`
}

func (q QuoteOption) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QuoteOption) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QuoteOption) GetFiftyTwoWeekHigh() *float64 {
	if q == nil {
		return nil
	}
	return q.FiftyTwoWeekHigh
}

func (q *QuoteOption) GetFiftyTwoWeekLow() *float64 {
	if q == nil {
		return nil
	}
	return q.FiftyTwoWeekLow
}

func (q *QuoteOption) GetAskPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.AskPrice
}

func (q *QuoteOption) GetAskSize() *int {
	if q == nil {
		return nil
	}
	return q.AskSize
}

func (q *QuoteOption) GetBidPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.BidPrice
}

func (q *QuoteOption) GetBidSize() *int {
	if q == nil {
		return nil
	}
	return q.BidSize
}

func (q *QuoteOption) GetClosePrice() *float64 {
	if q == nil {
		return nil
	}
	return q.ClosePrice
}

func (q *QuoteOption) GetDelta() *float64 {
	if q == nil {
		return nil
	}
	return q.Delta
}

func (q *QuoteOption) GetGamma() *float64 {
	if q == nil {
		return nil
	}
	return q.Gamma
}

func (q *QuoteOption) GetHighPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.HighPrice
}

func (q *QuoteOption) GetIndAskPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.IndAskPrice
}

func (q *QuoteOption) GetIndBidPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.IndBidPrice
}

func (q *QuoteOption) GetIndQuoteTime() *int64 {
	if q == nil {
		return nil
	}
	return q.IndQuoteTime
}

func (q *QuoteOption) GetImpliedYield() *float64 {
	if q == nil {
		return nil
	}
	return q.ImpliedYield
}

func (q *QuoteOption) GetLastPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.LastPrice
}

func (q *QuoteOption) GetLastSize() *int {
	if q == nil {
		return nil
	}
	return q.LastSize
}

func (q *QuoteOption) GetLowPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.LowPrice
}

func (q *QuoteOption) GetMark() *float64 {
	if q == nil {
		return nil
	}
	return q.Mark
}

func (q *QuoteOption) GetMarkChange() *float64 {
	if q == nil {
		return nil
	}
	return q.MarkChange
}

func (q *QuoteOption) GetMarkPercentChange() *float64 {
	if q == nil {
		return nil
	}
	return q.MarkPercentChange
}

func (q *QuoteOption) GetMoneyIntrinsicValue() *float64 {
	if q == nil {
		return nil
	}
	return q.MoneyIntrinsicValue
}

func (q *QuoteOption) GetNetChange() *float64 {
	if q == nil {
		return nil
	}
	return q.NetChange
}

func (q *QuoteOption) GetNetPercentChange() *float64 {
	if q == nil {
		return nil
	}
	return q.NetPercentChange
}

func (q *QuoteOption) GetOpenInterest() *float64 {
	if q == nil {
		return nil
	}
	return q.OpenInterest
}

func (q *QuoteOption) GetOpenPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.OpenPrice
}

func (q *QuoteOption) GetQuoteTime() *int64 {
	if q == nil {
		return nil
	}
	return q.QuoteTime
}

func (q *QuoteOption) GetRho() *float64 {
	if q == nil {
		return nil
	}
	return q.Rho
}

func (q *QuoteOption) GetSecurityStatus() *string {
	if q == nil {
		return nil
	}
	return q.SecurityStatus
}

func (q *QuoteOption) GetTheoreticalOptionValue() *float64 {
	if q == nil {
		return nil
	}
	return q.TheoreticalOptionValue
}

func (q *QuoteOption) GetTheta() *float64 {
	if q == nil {
		return nil
	}
	return q.Theta
}

func (q *QuoteOption) GetTimeValue() *float64 {
	if q == nil {
		return nil
	}
	return q.TimeValue
}

func (q *QuoteOption) GetTotalVolume() *int64 {
	if q == nil {
		return nil
	}
	return q.TotalVolume
}

func (q *QuoteOption) GetTradeTime() *int64 {
	if q == nil {
		return nil
	}
	return q.TradeTime
}

func (q *QuoteOption) GetUnderlyingPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.UnderlyingPrice
}

func (q *QuoteOption) GetVega() *float64 {
	if q == nil {
		return nil
	}
	return q.Vega
}

func (q *QuoteOption) GetVolatility() *float64 {
	if q == nil {
		return nil
	}
	return q.Volatility
}
