// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// QuoteType - NBBO - realtime, NFL - Non-fee liable quote.
type QuoteType string

const (
	QuoteTypeNbbo QuoteType = "NBBO"
	QuoteTypeNfl  QuoteType = "NFL"
)

func (e QuoteType) ToPointer() *QuoteType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *QuoteType) IsExact() bool {
	if e != nil {
		switch *e {
		case "NBBO", "NFL":
			return true
		}
	}
	return false
}
