// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

// QuoteForex - Quote data of Forex security
type QuoteForex struct {
	// Higest price traded in the past 12 months, or 52 weeks
	FiftyTwoWeekHigh *float64 `json:"52WeekHigh,omitzero"`
	// Lowest price traded in the past 12 months, or 52 weeks
	FiftyTwoWeekLow *float64 `json:"52WeekLow,omitzero"`
	// Current Best Ask Price
	AskPrice *float64 `json:"askPrice,omitzero"`
	// Number of shares for ask
	AskSize *int `json:"askSize,omitzero"`
	// Current Best Bid Price
	BidPrice *float64 `json:"bidPrice,omitzero"`
	// Number of shares for bid
	BidSize *int `json:"bidSize,omitzero"`
	// Previous day's closing price
	ClosePrice *float64 `json:"closePrice,omitzero"`
	// Day's high trade price
	HighPrice *float64 `json:"highPrice,omitzero"`
	LastPrice *float64 `json:"lastPrice,omitzero"`
	// Number of shares traded with last trade
	LastSize *int `json:"lastSize,omitzero"`
	// Day's low trade price
	LowPrice *float64 `json:"lowPrice,omitzero"`
	// Mark price
	Mark *float64 `json:"mark,omitzero"`
	// Current Last-Prev Close
	NetChange *float64 `json:"netChange,omitzero"`
	// Net Percentage Change
	NetPercentChange *float64 `json:"netPercentChange,omitzero"`
	// Price at market open
	OpenPrice *float64 `json:"openPrice,omitzero"`
	// Last quote time in milliseconds since Epoch
	QuoteTime *int64 `json:"quoteTime,omitzero"`
	// Status of security
	SecurityStatus *string `json:"securityStatus,omitzero"`
	// Tick Price
	Tick *float64 `json:"tick,omitzero"`
	// Tick Amount
	TickAmount *float64 `json:"tickAmount,omitzero"`
	// Aggregated shares traded throughout the day, including pre/post market hours.
	TotalVolume *int64 `json:"totalVolume,omitzero"`
	// Last trade time in milliseconds since Epoch
	TradeTime *int64 `json:"tradeTime,omitzero"`
}

func (q QuoteForex) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QuoteForex) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QuoteForex) GetFiftyTwoWeekHigh() *float64 {
	if q == nil {
		return nil
	}
	return q.FiftyTwoWeekHigh
}

func (q *QuoteForex) GetFiftyTwoWeekLow() *float64 {
	if q == nil {
		return nil
	}
	return q.FiftyTwoWeekLow
}

func (q *QuoteForex) GetAskPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.AskPrice
}

func (q *QuoteForex) GetAskSize() *int {
	if q == nil {
		return nil
	}
	return q.AskSize
}

func (q *QuoteForex) GetBidPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.BidPrice
}

func (q *QuoteForex) GetBidSize() *int {
	if q == nil {
		return nil
	}
	return q.BidSize
}

func (q *QuoteForex) GetClosePrice() *float64 {
	if q == nil {
		return nil
	}
	return q.ClosePrice
}

func (q *QuoteForex) GetHighPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.HighPrice
}

func (q *QuoteForex) GetLastPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.LastPrice
}

func (q *QuoteForex) GetLastSize() *int {
	if q == nil {
		return nil
	}
	return q.LastSize
}

func (q *QuoteForex) GetLowPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.LowPrice
}

func (q *QuoteForex) GetMark() *float64 {
	if q == nil {
		return nil
	}
	return q.Mark
}

func (q *QuoteForex) GetNetChange() *float64 {
	if q == nil {
		return nil
	}
	return q.NetChange
}

func (q *QuoteForex) GetNetPercentChange() *float64 {
	if q == nil {
		return nil
	}
	return q.NetPercentChange
}

func (q *QuoteForex) GetOpenPrice() *float64 {
	if q == nil {
		return nil
	}
	return q.OpenPrice
}

func (q *QuoteForex) GetQuoteTime() *int64 {
	if q == nil {
		return nil
	}
	return q.QuoteTime
}

func (q *QuoteForex) GetSecurityStatus() *string {
	if q == nil {
		return nil
	}
	return q.SecurityStatus
}

func (q *QuoteForex) GetTick() *float64 {
	if q == nil {
		return nil
	}
	return q.Tick
}

func (q *QuoteForex) GetTickAmount() *float64 {
	if q == nil {
		return nil
	}
	return q.TickAmount
}

func (q *QuoteForex) GetTotalVolume() *int64 {
	if q == nil {
		return nil
	}
	return q.TotalVolume
}

func (q *QuoteForex) GetTradeTime() *int64 {
	if q == nil {
		return nil
	}
	return q.TradeTime
}
