// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

// ReferenceMutualFund - Reference data of MutualFund security
type ReferenceMutualFund struct {
	// CUSIP of Instrument
	Cusip *string `json:"cusip,omitzero"`
	// Description of Instrument
	Description *string `json:"description,omitzero"`
	// Exchange Code
	Exchange *string `default:"m" json:"exchange"`
	// Exchange Name
	ExchangeName *string `default:"MUTUAL_FUND" json:"exchangeName"`
}

func (r ReferenceMutualFund) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReferenceMutualFund) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReferenceMutualFund) GetCusip() *string {
	if r == nil {
		return nil
	}
	return r.Cusip
}

func (r *ReferenceMutualFund) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}

func (r *ReferenceMutualFund) GetExchange() *string {
	if r == nil {
		return nil
	}
	return r.Exchange
}

func (r *ReferenceMutualFund) GetExchangeName() *string {
	if r == nil {
		return nil
	}
	return r.ExchangeName
}
