// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

// ReferenceFutureOption - Reference data of Future Option security
type ReferenceFutureOption struct {
	// Indicates call or put
	ContractType *ContractType `json:"contractType,omitzero"`
	// Description of Instrument
	Description *string `json:"description,omitzero"`
	// Exchange Code
	Exchange *string `json:"exchange,omitzero"`
	// Exchange Name
	ExchangeName *string `json:"exchangeName,omitzero"`
	// Option multiplier
	Multiplier *float64 `json:"multiplier,omitzero"`
	// date of expiration in long
	ExpirationDate *int64 `json:"expirationDate,omitzero"`
	// Style of expiration
	ExpirationStyle *string `json:"expirationStyle,omitzero"`
	// Strike Price
	StrikePrice *float64 `json:"strikePrice,omitzero"`
	// A company, index or fund name
	Underlying *string `json:"underlying,omitzero"`
}

func (r ReferenceFutureOption) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReferenceFutureOption) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReferenceFutureOption) GetContractType() *ContractType {
	if r == nil {
		return nil
	}
	return r.ContractType
}

func (r *ReferenceFutureOption) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}

func (r *ReferenceFutureOption) GetExchange() *string {
	if r == nil {
		return nil
	}
	return r.Exchange
}

func (r *ReferenceFutureOption) GetExchangeName() *string {
	if r == nil {
		return nil
	}
	return r.ExchangeName
}

func (r *ReferenceFutureOption) GetMultiplier() *float64 {
	if r == nil {
		return nil
	}
	return r.Multiplier
}

func (r *ReferenceFutureOption) GetExpirationDate() *int64 {
	if r == nil {
		return nil
	}
	return r.ExpirationDate
}

func (r *ReferenceFutureOption) GetExpirationStyle() *string {
	if r == nil {
		return nil
	}
	return r.ExpirationStyle
}

func (r *ReferenceFutureOption) GetStrikePrice() *float64 {
	if r == nil {
		return nil
	}
	return r.StrikePrice
}

func (r *ReferenceFutureOption) GetUnderlying() *string {
	if r == nil {
		return nil
	}
	return r.Underlying
}
