// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

// ReferenceFuture - Reference data of Future security
type ReferenceFuture struct {
	// Description of Instrument
	Description *string `json:"description,omitzero"`
	// Exchange Code
	Exchange *string `json:"exchange,omitzero"`
	// Exchange Name
	ExchangeName *string `json:"exchangeName,omitzero"`
	// Active symbol
	FutureActiveSymbol *string `json:"futureActiveSymbol,omitzero"`
	// Future expiration date in milliseconds since epoch
	FutureExpirationDate *float64 `json:"futureExpirationDate,omitzero"`
	// Future is active
	FutureIsActive *bool `json:"futureIsActive,omitzero"`
	// Future multiplier
	FutureMultiplier *float64 `json:"futureMultiplier,omitzero"`
	// Price format
	FuturePriceFormat *string `json:"futurePriceFormat,omitzero"`
	// Future Settlement Price
	FutureSettlementPrice *float64 `json:"futureSettlementPrice,omitzero"`
	// Trading Hours
	FutureTradingHours *string `json:"futureTradingHours,omitzero"`
	// Futures product symbol
	Product *string `json:"product,omitzero"`
}

func (r ReferenceFuture) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReferenceFuture) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReferenceFuture) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}

func (r *ReferenceFuture) GetExchange() *string {
	if r == nil {
		return nil
	}
	return r.Exchange
}

func (r *ReferenceFuture) GetExchangeName() *string {
	if r == nil {
		return nil
	}
	return r.ExchangeName
}

func (r *ReferenceFuture) GetFutureActiveSymbol() *string {
	if r == nil {
		return nil
	}
	return r.FutureActiveSymbol
}

func (r *ReferenceFuture) GetFutureExpirationDate() *float64 {
	if r == nil {
		return nil
	}
	return r.FutureExpirationDate
}

func (r *ReferenceFuture) GetFutureIsActive() *bool {
	if r == nil {
		return nil
	}
	return r.FutureIsActive
}

func (r *ReferenceFuture) GetFutureMultiplier() *float64 {
	if r == nil {
		return nil
	}
	return r.FutureMultiplier
}

func (r *ReferenceFuture) GetFuturePriceFormat() *string {
	if r == nil {
		return nil
	}
	return r.FuturePriceFormat
}

func (r *ReferenceFuture) GetFutureSettlementPrice() *float64 {
	if r == nil {
		return nil
	}
	return r.FutureSettlementPrice
}

func (r *ReferenceFuture) GetFutureTradingHours() *string {
	if r == nil {
		return nil
	}
	return r.FutureTradingHours
}

func (r *ReferenceFuture) GetProduct() *string {
	if r == nil {
		return nil
	}
	return r.Product
}
