// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

// ReferenceOption - Reference data of Option security
type ReferenceOption struct {
	// Indicates call or put
	ContractType *ContractType `json:"contractType,omitzero"`
	// CUSIP of Instrument
	Cusip *string `json:"cusip,omitzero"`
	// Days to Expiration
	DaysToExpiration *int `json:"daysToExpiration,omitzero"`
	// Unit of trade
	Deliverables *string `json:"deliverables,omitzero"`
	// Description of Instrument
	Description *string `json:"description,omitzero"`
	// Exchange Code
	Exchange *string `default:"o" json:"exchange"`
	// Exchange Name
	ExchangeName *string `json:"exchangeName,omitzero"`
	// option contract exercise type America or European
	ExerciseType *ExerciseType `json:"exerciseType,omitzero"`
	// Expiration Day
	ExpirationDay *int `json:"expirationDay,omitzero"`
	// Expiration Month
	ExpirationMonth *int `json:"expirationMonth,omitzero"`
	// M for End Of Month Expiration Calendar Cycle. (To match the last business day of the month), Q for Quarterly expirations (last business day of the quarter month MAR/JUN/SEP/DEC), W for Weekly expiration (also called Friday Short Term Expirations) and S for Expires 3rd Friday of the month (also known as regular options).
	ExpirationType *ExpirationType `json:"expirationType,omitzero"`
	// Expiration Year
	ExpirationYear *int `json:"expirationYear,omitzero"`
	// Is this contract part of the Penny Pilot program
	IsPennyPilot *bool `json:"isPennyPilot,omitzero"`
	// milliseconds since epoch
	LastTradingDay *int64 `json:"lastTradingDay,omitzero"`
	// Option multiplier
	Multiplier *float64 `json:"multiplier,omitzero"`
	// option contract settlement type AM or PM
	SettlementType *SettlementType `json:"settlementType,omitzero"`
	// Strike Price
	StrikePrice *float64 `json:"strikePrice,omitzero"`
	// A company, index or fund name
	Underlying *string `json:"underlying,omitzero"`
}

func (r ReferenceOption) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReferenceOption) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReferenceOption) GetContractType() *ContractType {
	if r == nil {
		return nil
	}
	return r.ContractType
}

func (r *ReferenceOption) GetCusip() *string {
	if r == nil {
		return nil
	}
	return r.Cusip
}

func (r *ReferenceOption) GetDaysToExpiration() *int {
	if r == nil {
		return nil
	}
	return r.DaysToExpiration
}

func (r *ReferenceOption) GetDeliverables() *string {
	if r == nil {
		return nil
	}
	return r.Deliverables
}

func (r *ReferenceOption) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}

func (r *ReferenceOption) GetExchange() *string {
	if r == nil {
		return nil
	}
	return r.Exchange
}

func (r *ReferenceOption) GetExchangeName() *string {
	if r == nil {
		return nil
	}
	return r.ExchangeName
}

func (r *ReferenceOption) GetExerciseType() *ExerciseType {
	if r == nil {
		return nil
	}
	return r.ExerciseType
}

func (r *ReferenceOption) GetExpirationDay() *int {
	if r == nil {
		return nil
	}
	return r.ExpirationDay
}

func (r *ReferenceOption) GetExpirationMonth() *int {
	if r == nil {
		return nil
	}
	return r.ExpirationMonth
}

func (r *ReferenceOption) GetExpirationType() *ExpirationType {
	if r == nil {
		return nil
	}
	return r.ExpirationType
}

func (r *ReferenceOption) GetExpirationYear() *int {
	if r == nil {
		return nil
	}
	return r.ExpirationYear
}

func (r *ReferenceOption) GetIsPennyPilot() *bool {
	if r == nil {
		return nil
	}
	return r.IsPennyPilot
}

func (r *ReferenceOption) GetLastTradingDay() *int64 {
	if r == nil {
		return nil
	}
	return r.LastTradingDay
}

func (r *ReferenceOption) GetMultiplier() *float64 {
	if r == nil {
		return nil
	}
	return r.Multiplier
}

func (r *ReferenceOption) GetSettlementType() *SettlementType {
	if r == nil {
		return nil
	}
	return r.SettlementType
}

func (r *ReferenceOption) GetStrikePrice() *float64 {
	if r == nil {
		return nil
	}
	return r.StrikePrice
}

func (r *ReferenceOption) GetUnderlying() *string {
	if r == nil {
		return nil
	}
	return r.Underlying
}
