// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

// ReferenceForex - Reference data of Forex security
type ReferenceForex struct {
	// Description of Instrument
	Description *string `json:"description,omitzero"`
	// Exchange Code
	Exchange *string `json:"exchange,omitzero"`
	// Exchange Name
	ExchangeName *string `json:"exchangeName,omitzero"`
	// is FOREX tradable
	IsTradable *bool `json:"isTradable,omitzero"`
	// Market marker
	MarketMaker *string `json:"marketMaker,omitzero"`
	// Product name
	Product *string `json:"product,omitzero"`
	// Trading hours
	TradingHours *string `json:"tradingHours,omitzero"`
}

func (r ReferenceForex) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReferenceForex) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReferenceForex) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}

func (r *ReferenceForex) GetExchange() *string {
	if r == nil {
		return nil
	}
	return r.Exchange
}

func (r *ReferenceForex) GetExchangeName() *string {
	if r == nil {
		return nil
	}
	return r.ExchangeName
}

func (r *ReferenceForex) GetIsTradable() *bool {
	if r == nil {
		return nil
	}
	return r.IsTradable
}

func (r *ReferenceForex) GetMarketMaker() *string {
	if r == nil {
		return nil
	}
	return r.MarketMaker
}

func (r *ReferenceForex) GetProduct() *string {
	if r == nil {
		return nil
	}
	return r.Product
}

func (r *ReferenceForex) GetTradingHours() *string {
	if r == nil {
		return nil
	}
	return r.TradingHours
}
