// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

// ReferenceEquity - Reference data of Equity security
type ReferenceEquity struct {
	// CUSIP of Instrument
	Cusip *string `json:"cusip,omitzero"`
	// Description of Instrument
	Description *string `json:"description,omitzero"`
	// Exchange Code
	Exchange *string `json:"exchange,omitzero"`
	// Exchange Name
	ExchangeName *string `json:"exchangeName,omitzero"`
	// FSI Desc
	FsiDesc *string `json:"fsiDesc,omitzero"`
	// Hard to borrow quantity.
	HtbQuantity *int `json:"htbQuantity,omitzero"`
	// Hard to borrow rate.
	HtbRate *float64 `json:"htbRate,omitzero"`
	// is Hard to borrow security.
	IsHardToBorrow *bool `json:"isHardToBorrow,omitzero"`
	// is shortable security.
	IsShortable *bool `json:"isShortable,omitzero"`
	// OTC Market Tier
	OtcMarketTier *string `json:"otcMarketTier,omitzero"`
}

func (r ReferenceEquity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReferenceEquity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReferenceEquity) GetCusip() *string {
	if r == nil {
		return nil
	}
	return r.Cusip
}

func (r *ReferenceEquity) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}

func (r *ReferenceEquity) GetExchange() *string {
	if r == nil {
		return nil
	}
	return r.Exchange
}

func (r *ReferenceEquity) GetExchangeName() *string {
	if r == nil {
		return nil
	}
	return r.ExchangeName
}

func (r *ReferenceEquity) GetFsiDesc() *string {
	if r == nil {
		return nil
	}
	return r.FsiDesc
}

func (r *ReferenceEquity) GetHtbQuantity() *int {
	if r == nil {
		return nil
	}
	return r.HtbQuantity
}

func (r *ReferenceEquity) GetHtbRate() *float64 {
	if r == nil {
		return nil
	}
	return r.HtbRate
}

func (r *ReferenceEquity) GetIsHardToBorrow() *bool {
	if r == nil {
		return nil
	}
	return r.IsHardToBorrow
}

func (r *ReferenceEquity) GetIsShortable() *bool {
	if r == nil {
		return nil
	}
	return r.IsShortable
}

func (r *ReferenceEquity) GetOtcMarketTier() *string {
	if r == nil {
		return nil
	}
	return r.OtcMarketTier
}
