// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

// ReferenceIndex - Reference data of Index security
type ReferenceIndex struct {
	// Description of Instrument
	Description *string `json:"description,omitzero"`
	// Exchange Code
	Exchange *string `json:"exchange,omitzero"`
	// Exchange Name
	ExchangeName *string `json:"exchangeName,omitzero"`
}

func (r ReferenceIndex) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReferenceIndex) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReferenceIndex) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}

func (r *ReferenceIndex) GetExchange() *string {
	if r == nil {
		return nil
	}
	return r.Exchange
}

func (r *ReferenceIndex) GetExchangeName() *string {
	if r == nil {
		return nil
	}
	return r.ExchangeName
}
