// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

// RegularMarket - Market info of security
type RegularMarket struct {
	// Regular market last price
	RegularMarketLastPrice *float64 `json:"regularMarketLastPrice,omitzero"`
	// Regular market last size
	RegularMarketLastSize *int `json:"regularMarketLastSize,omitzero"`
	// Regular market net change
	RegularMarketNetChange *float64 `json:"regularMarketNetChange,omitzero"`
	// Regular market percent change
	RegularMarketPercentChange *float64 `json:"regularMarketPercentChange,omitzero"`
	// Regular market trade time in milliseconds since Epoch
	RegularMarketTradeTime *int64 `json:"regularMarketTradeTime,omitzero"`
}

func (r RegularMarket) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RegularMarket) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RegularMarket) GetRegularMarketLastPrice() *float64 {
	if r == nil {
		return nil
	}
	return r.RegularMarketLastPrice
}

func (r *RegularMarket) GetRegularMarketLastSize() *int {
	if r == nil {
		return nil
	}
	return r.RegularMarketLastSize
}

func (r *RegularMarket) GetRegularMarketNetChange() *float64 {
	if r == nil {
		return nil
	}
	return r.RegularMarketNetChange
}

func (r *RegularMarket) GetRegularMarketPercentChange() *float64 {
	if r == nil {
		return nil
	}
	return r.RegularMarketPercentChange
}

func (r *RegularMarket) GetRegularMarketTradeTime() *int64 {
	if r == nil {
		return nil
	}
	return r.RegularMarketTradeTime
}
