// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RequestedDestination string

const (
	RequestedDestinationInet    RequestedDestination = "INET"
	RequestedDestinationEcnArca RequestedDestination = "ECN_ARCA"
	RequestedDestinationCboe    RequestedDestination = "CBOE"
	RequestedDestinationAmex    RequestedDestination = "AMEX"
	RequestedDestinationPhlx    RequestedDestination = "PHLX"
	RequestedDestinationIse     RequestedDestination = "ISE"
	RequestedDestinationBox     RequestedDestination = "BOX"
	RequestedDestinationNyse    RequestedDestination = "NYSE"
	RequestedDestinationNasdaq  RequestedDestination = "NASDAQ"
	RequestedDestinationBats    RequestedDestination = "BATS"
	RequestedDestinationC2      RequestedDestination = "C2"
	RequestedDestinationAuto    RequestedDestination = "AUTO"
)

func (e RequestedDestination) ToPointer() *RequestedDestination {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *RequestedDestination) IsExact() bool {
	if e != nil {
		switch *e {
		case "INET", "ECN_ARCA", "CBOE", "AMEX", "PHLX", "ISE", "BOX", "NYSE", "NASDAQ", "BATS", "C2", "AUTO":
			return true
		}
	}
	return false
}
