// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Direction string

const (
	DirectionUp   Direction = "up"
	DirectionDown Direction = "down"
)

func (e Direction) ToPointer() *Direction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Direction) IsExact() bool {
	if e != nil {
		switch *e {
		case "up", "down":
			return true
		}
	}
	return false
}

// Screener - Security info of most moved with in an index
type Screener struct {
	// percent or value changed, by default its percent changed
	Change *float64 `json:"change,omitzero"`
	// Name of security
	Description *string    `json:"description,omitzero"`
	Direction   *Direction `json:"direction,omitzero"`
	// what was last quoted price
	Last *float64 `json:"last,omitzero"`
	// schwab security symbol
	Symbol      *string `json:"symbol,omitzero"`
	TotalVolume *int64  `json:"totalVolume,omitzero"`
}

func (s *Screener) GetChange() *float64 {
	if s == nil {
		return nil
	}
	return s.Change
}

func (s *Screener) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *Screener) GetDirection() *Direction {
	if s == nil {
		return nil
	}
	return s.Direction
}

func (s *Screener) GetLast() *float64 {
	if s == nil {
		return nil
	}
	return s.Last
}

func (s *Screener) GetSymbol() *string {
	if s == nil {
		return nil
	}
	return s.Symbol
}

func (s *Screener) GetTotalVolume() *int64 {
	if s == nil {
		return nil
	}
	return s.TotalVolume
}
