// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"undefined/internal/utils"
)

type SecuritiesAccountType string

const (
	SecuritiesAccountTypeMargin SecuritiesAccountType = "MARGIN"
	SecuritiesAccountTypeCash   SecuritiesAccountType = "CASH"
)

type SecuritiesAccount struct {
	MarginAccount *MarginAccount `queryParam:"inline" union:"member"`
	CashAccount   *CashAccount   `queryParam:"inline" union:"member"`

	Type SecuritiesAccountType
}

func CreateSecuritiesAccountMargin(margin MarginAccount) SecuritiesAccount {
	typ := SecuritiesAccountTypeMargin

	typStr := MarginAccountType(typ)
	margin.Type = &typStr

	return SecuritiesAccount{
		MarginAccount: &margin,
		Type:          typ,
	}
}

func CreateSecuritiesAccountCash(cash CashAccount) SecuritiesAccount {
	typ := SecuritiesAccountTypeCash

	typStr := CashAccountType(typ)
	cash.Type = &typStr

	return SecuritiesAccount{
		CashAccount: &cash,
		Type:        typ,
	}
}

func (u *SecuritiesAccount) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "MARGIN":
		marginAccount := new(MarginAccount)
		if err := utils.UnmarshalJSON(data, &marginAccount, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == MARGIN) type MarginAccount within SecuritiesAccount: %w", string(data), err)
		}

		u.MarginAccount = marginAccount
		u.Type = SecuritiesAccountTypeMargin
		return nil
	case "CASH":
		cashAccount := new(CashAccount)
		if err := utils.UnmarshalJSON(data, &cashAccount, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == CASH) type CashAccount within SecuritiesAccount: %w", string(data), err)
		}

		u.CashAccount = cashAccount
		u.Type = SecuritiesAccountTypeCash
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for SecuritiesAccount", string(data))
}

func (u SecuritiesAccount) MarshalJSON() ([]byte, error) {
	if u.MarginAccount != nil {
		return utils.MarshalJSON(u.MarginAccount, "", true)
	}

	if u.CashAccount != nil {
		return utils.MarshalJSON(u.CashAccount, "", true)
	}

	return nil, errors.New("could not marshal union type SecuritiesAccount: all fields are null")
}
