// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Session string

const (
	SessionNormal   Session = "NORMAL"
	SessionAm       Session = "AM"
	SessionPm       Session = "PM"
	SessionSeamless Session = "SEAMLESS"
)

func (e Session) ToPointer() *Session {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Session) IsExact() bool {
	if e != nil {
		switch *e {
		case "NORMAL", "AM", "PM", "SEAMLESS":
			return true
		}
	}
	return false
}
