// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SettlementType - option contract settlement type AM or PM
type SettlementType string

const (
	SettlementTypeA SettlementType = "A"
	SettlementTypeP SettlementType = "P"
)

func (e SettlementType) ToPointer() *SettlementType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SettlementType) IsExact() bool {
	if e != nil {
		switch *e {
		case "A", "P":
			return true
		}
	}
	return false
}
