// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SpecialInstruction string

const (
	SpecialInstructionAllOrNone            SpecialInstruction = "ALL_OR_NONE"
	SpecialInstructionDoNotReduce          SpecialInstruction = "DO_NOT_REDUCE"
	SpecialInstructionAllOrNoneDoNotReduce SpecialInstruction = "ALL_OR_NONE_DO_NOT_REDUCE"
)

func (e SpecialInstruction) ToPointer() *SpecialInstruction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SpecialInstruction) IsExact() bool {
	if e != nil {
		switch *e {
		case "ALL_OR_NONE", "DO_NOT_REDUCE", "ALL_OR_NONE_DO_NOT_REDUCE":
			return true
		}
	}
	return false
}
