// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Status string

const (
	StatusAwaitingParentOrder    Status = "AWAITING_PARENT_ORDER"
	StatusAwaitingCondition      Status = "AWAITING_CONDITION"
	StatusAwaitingStopCondition  Status = "AWAITING_STOP_CONDITION"
	StatusAwaitingManualReview   Status = "AWAITING_MANUAL_REVIEW"
	StatusAccepted               Status = "ACCEPTED"
	StatusAwaitingUrOut          Status = "AWAITING_UR_OUT"
	StatusPendingActivation      Status = "PENDING_ACTIVATION"
	StatusQueued                 Status = "QUEUED"
	StatusWorking                Status = "WORKING"
	StatusRejected               Status = "REJECTED"
	StatusPendingCancel          Status = "PENDING_CANCEL"
	StatusCanceled               Status = "CANCELED"
	StatusPendingReplace         Status = "PENDING_REPLACE"
	StatusReplaced               Status = "REPLACED"
	StatusFilled                 Status = "FILLED"
	StatusExpired                Status = "EXPIRED"
	StatusNew                    Status = "NEW"
	StatusAwaitingReleaseTime    Status = "AWAITING_RELEASE_TIME"
	StatusPendingAcknowledgement Status = "PENDING_ACKNOWLEDGEMENT"
	StatusPendingRecall          Status = "PENDING_RECALL"
	StatusUnknown                Status = "UNKNOWN"
)

func (e Status) ToPointer() *Status {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Status) IsExact() bool {
	if e != nil {
		switch *e {
		case "AWAITING_PARENT_ORDER", "AWAITING_CONDITION", "AWAITING_STOP_CONDITION", "AWAITING_MANUAL_REVIEW", "ACCEPTED", "AWAITING_UR_OUT", "PENDING_ACTIVATION", "QUEUED", "WORKING", "REJECTED", "PENDING_CANCEL", "CANCELED", "PENDING_REPLACE", "REPLACED", "FILLED", "EXPIRED", "NEW", "AWAITING_RELEASE_TIME", "PENDING_ACKNOWLEDGEMENT", "PENDING_RECALL", "UNKNOWN":
			return true
		}
	}
	return false
}
