// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StopType string

const (
	StopTypeStandard StopType = "STANDARD"
	StopTypeBid      StopType = "BID"
	StopTypeAsk      StopType = "ASK"
	StopTypeLast     StopType = "LAST"
	StopTypeMark     StopType = "MARK"
)

func (e StopType) ToPointer() *StopType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *StopType) IsExact() bool {
	if e != nil {
		switch *e {
		case "STANDARD", "BID", "ASK", "LAST", "MARK":
			return true
		}
	}
	return false
}
