// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StopPriceLinkBasis string

const (
	StopPriceLinkBasisManual  StopPriceLinkBasis = "MANUAL"
	StopPriceLinkBasisBase    StopPriceLinkBasis = "BASE"
	StopPriceLinkBasisTrigger StopPriceLinkBasis = "TRIGGER"
	StopPriceLinkBasisLast    StopPriceLinkBasis = "LAST"
	StopPriceLinkBasisBid     StopPriceLinkBasis = "BID"
	StopPriceLinkBasisAsk     StopPriceLinkBasis = "ASK"
	StopPriceLinkBasisAskBid  StopPriceLinkBasis = "ASK_BID"
	StopPriceLinkBasisMark    StopPriceLinkBasis = "MARK"
	StopPriceLinkBasisAverage StopPriceLinkBasis = "AVERAGE"
)

func (e StopPriceLinkBasis) ToPointer() *StopPriceLinkBasis {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *StopPriceLinkBasis) IsExact() bool {
	if e != nil {
		switch *e {
		case "MANUAL", "BASE", "TRIGGER", "LAST", "BID", "ASK", "ASK_BID", "MARK", "AVERAGE":
			return true
		}
	}
	return false
}
