// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StopPriceLinkType string

const (
	StopPriceLinkTypeValue   StopPriceLinkType = "VALUE"
	StopPriceLinkTypePercent StopPriceLinkType = "PERCENT"
	StopPriceLinkTypeTick    StopPriceLinkType = "TICK"
)

func (e StopPriceLinkType) ToPointer() *StopPriceLinkType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *StopPriceLinkType) IsExact() bool {
	if e != nil {
		switch *e {
		case "VALUE", "PERCENT", "TICK":
			return true
		}
	}
	return false
}
