// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StreamerInfo struct {
	StreamerSocketURL      *string `json:"streamerSocketUrl,omitzero"`
	SchwabClientCustomerID *string `json:"schwabClientCustomerId,omitzero"`
	SchwabClientCorrelID   *string `json:"schwabClientCorrelId,omitzero"`
	SchwabClientChannel    *string `json:"schwabClientChannel,omitzero"`
	SchwabClientFunctionID *string `json:"schwabClientFunctionId,omitzero"`
}

func (s *StreamerInfo) GetStreamerSocketURL() *string {
	if s == nil {
		return nil
	}
	return s.StreamerSocketURL
}

func (s *StreamerInfo) GetSchwabClientCustomerID() *string {
	if s == nil {
		return nil
	}
	return s.SchwabClientCustomerID
}

func (s *StreamerInfo) GetSchwabClientCorrelID() *string {
	if s == nil {
		return nil
	}
	return s.SchwabClientCorrelID
}

func (s *StreamerInfo) GetSchwabClientChannel() *string {
	if s == nil {
		return nil
	}
	return s.SchwabClientChannel
}

func (s *StreamerInfo) GetSchwabClientFunctionID() *string {
	if s == nil {
		return nil
	}
	return s.SchwabClientFunctionID
}
