// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TaxLotMethod string

const (
	TaxLotMethodFifo          TaxLotMethod = "FIFO"
	TaxLotMethodLifo          TaxLotMethod = "LIFO"
	TaxLotMethodHighCost      TaxLotMethod = "HIGH_COST"
	TaxLotMethodLowCost       TaxLotMethod = "LOW_COST"
	TaxLotMethodAverageCost   TaxLotMethod = "AVERAGE_COST"
	TaxLotMethodSpecificLot   TaxLotMethod = "SPECIFIC_LOT"
	TaxLotMethodLossHarvester TaxLotMethod = "LOSS_HARVESTER"
)

func (e TaxLotMethod) ToPointer() *TaxLotMethod {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TaxLotMethod) IsExact() bool {
	if e != nil {
		switch *e {
		case "FIFO", "LIFO", "HIGH_COST", "LOW_COST", "AVERAGE_COST", "SPECIFIC_LOT", "LOSS_HARVESTER":
			return true
		}
	}
	return false
}
