// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TransferItemFeeType string

const (
	TransferItemFeeTypeCommission            TransferItemFeeType = "COMMISSION"
	TransferItemFeeTypeSecFee                TransferItemFeeType = "SEC_FEE"
	TransferItemFeeTypeStrFee                TransferItemFeeType = "STR_FEE"
	TransferItemFeeTypeRFee                  TransferItemFeeType = "R_FEE"
	TransferItemFeeTypeCdscFee               TransferItemFeeType = "CDSC_FEE"
	TransferItemFeeTypeOptRegFee             TransferItemFeeType = "OPT_REG_FEE"
	TransferItemFeeTypeAdditionalFee         TransferItemFeeType = "ADDITIONAL_FEE"
	TransferItemFeeTypeMiscellaneousFee      TransferItemFeeType = "MISCELLANEOUS_FEE"
	TransferItemFeeTypeFuturesExchangeFee    TransferItemFeeType = "FUTURES_EXCHANGE_FEE"
	TransferItemFeeTypeLowProceedsCommission TransferItemFeeType = "LOW_PROCEEDS_COMMISSION"
	TransferItemFeeTypeBaseCharge            TransferItemFeeType = "BASE_CHARGE"
	TransferItemFeeTypeGeneralCharge         TransferItemFeeType = "GENERAL_CHARGE"
	TransferItemFeeTypeGstFee                TransferItemFeeType = "GST_FEE"
	TransferItemFeeTypeTafFee                TransferItemFeeType = "TAF_FEE"
	TransferItemFeeTypeIndexOptionFee        TransferItemFeeType = "INDEX_OPTION_FEE"
	TransferItemFeeTypeUnknown               TransferItemFeeType = "UNKNOWN"
)

func (e TransferItemFeeType) ToPointer() *TransferItemFeeType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TransferItemFeeType) IsExact() bool {
	if e != nil {
		switch *e {
		case "COMMISSION", "SEC_FEE", "STR_FEE", "R_FEE", "CDSC_FEE", "OPT_REG_FEE", "ADDITIONAL_FEE", "MISCELLANEOUS_FEE", "FUTURES_EXCHANGE_FEE", "LOW_PROCEEDS_COMMISSION", "BASE_CHARGE", "GENERAL_CHARGE", "GST_FEE", "TAF_FEE", "INDEX_OPTION_FEE", "UNKNOWN":
			return true
		}
	}
	return false
}

type TransferItemPositionEffect string

const (
	TransferItemPositionEffectOpening   TransferItemPositionEffect = "OPENING"
	TransferItemPositionEffectClosing   TransferItemPositionEffect = "CLOSING"
	TransferItemPositionEffectAutomatic TransferItemPositionEffect = "AUTOMATIC"
	TransferItemPositionEffectUnknown   TransferItemPositionEffect = "UNKNOWN"
)

func (e TransferItemPositionEffect) ToPointer() *TransferItemPositionEffect {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TransferItemPositionEffect) IsExact() bool {
	if e != nil {
		switch *e {
		case "OPENING", "CLOSING", "AUTOMATIC", "UNKNOWN":
			return true
		}
	}
	return false
}

type TransferItem struct {
	Instrument     *TransactionInstrument      `json:"instrument,omitzero"`
	Amount         *float64                    `json:"amount,omitzero"`
	Cost           *float64                    `json:"cost,omitzero"`
	Price          *float64                    `json:"price,omitzero"`
	FeeType        *TransferItemFeeType        `json:"feeType,omitzero"`
	PositionEffect *TransferItemPositionEffect `json:"positionEffect,omitzero"`
}

func (t *TransferItem) GetInstrument() *TransactionInstrument {
	if t == nil {
		return nil
	}
	return t.Instrument
}

func (t *TransferItem) GetAmount() *float64 {
	if t == nil {
		return nil
	}
	return t.Amount
}

func (t *TransferItem) GetCost() *float64 {
	if t == nil {
		return nil
	}
	return t.Cost
}

func (t *TransferItem) GetPrice() *float64 {
	if t == nil {
		return nil
	}
	return t.Price
}

func (t *TransferItem) GetFeeType() *TransferItemFeeType {
	if t == nil {
		return nil
	}
	return t.FeeType
}

func (t *TransferItem) GetPositionEffect() *TransferItemPositionEffect {
	if t == nil {
		return nil
	}
	return t.PositionEffect
}
