// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type TransactionEquityAssetType string

const (
	TransactionEquityAssetTypeEquity               TransactionEquityAssetType = "EQUITY"
	TransactionEquityAssetTypeOption               TransactionEquityAssetType = "OPTION"
	TransactionEquityAssetTypeIndex                TransactionEquityAssetType = "INDEX"
	TransactionEquityAssetTypeMutualFund           TransactionEquityAssetType = "MUTUAL_FUND"
	TransactionEquityAssetTypeCashEquivalent       TransactionEquityAssetType = "CASH_EQUIVALENT"
	TransactionEquityAssetTypeFixedIncome          TransactionEquityAssetType = "FIXED_INCOME"
	TransactionEquityAssetTypeCurrency             TransactionEquityAssetType = "CURRENCY"
	TransactionEquityAssetTypeCollectiveInvestment TransactionEquityAssetType = "COLLECTIVE_INVESTMENT"
)

func (e TransactionEquityAssetType) ToPointer() *TransactionEquityAssetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TransactionEquityAssetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EQUITY", "OPTION", "INDEX", "MUTUAL_FUND", "CASH_EQUIVALENT", "FIXED_INCOME", "CURRENCY", "COLLECTIVE_INVESTMENT":
			return true
		}
	}
	return false
}

type TransactionEquityType string

const (
	TransactionEquityTypeCommonStock                TransactionEquityType = "COMMON_STOCK"
	TransactionEquityTypePreferredStock             TransactionEquityType = "PREFERRED_STOCK"
	TransactionEquityTypeDepositoryReceipt          TransactionEquityType = "DEPOSITORY_RECEIPT"
	TransactionEquityTypePreferredDepositoryReceipt TransactionEquityType = "PREFERRED_DEPOSITORY_RECEIPT"
	TransactionEquityTypeRestrictedStock            TransactionEquityType = "RESTRICTED_STOCK"
	TransactionEquityTypeComponentUnit              TransactionEquityType = "COMPONENT_UNIT"
	TransactionEquityTypeRight                      TransactionEquityType = "RIGHT"
	TransactionEquityTypeWarrant                    TransactionEquityType = "WARRANT"
	TransactionEquityTypeConvertiblePreferredStock  TransactionEquityType = "CONVERTIBLE_PREFERRED_STOCK"
	TransactionEquityTypeConvertibleStock           TransactionEquityType = "CONVERTIBLE_STOCK"
	TransactionEquityTypeLimitedPartnership         TransactionEquityType = "LIMITED_PARTNERSHIP"
	TransactionEquityTypeWhenIssued                 TransactionEquityType = "WHEN_ISSUED"
	TransactionEquityTypeUnknown                    TransactionEquityType = "UNKNOWN"
)

func (e TransactionEquityType) ToPointer() *TransactionEquityType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TransactionEquityType) IsExact() bool {
	if e != nil {
		switch *e {
		case "COMMON_STOCK", "PREFERRED_STOCK", "DEPOSITORY_RECEIPT", "PREFERRED_DEPOSITORY_RECEIPT", "RESTRICTED_STOCK", "COMPONENT_UNIT", "RIGHT", "WARRANT", "CONVERTIBLE_PREFERRED_STOCK", "CONVERTIBLE_STOCK", "LIMITED_PARTNERSHIP", "WHEN_ISSUED", "UNKNOWN":
			return true
		}
	}
	return false
}

type TransactionEquity struct {
	AssetType    TransactionEquityAssetType `json:"assetType"`
	Cusip        *string                    `json:"cusip,omitzero"`
	Symbol       *string                    `json:"symbol,omitzero"`
	Description  *string                    `json:"description,omitzero"`
	InstrumentID *int64                     `json:"instrumentId,omitzero"`
	NetChange    *float64                   `json:"netChange,omitzero"`
	Type         *TransactionEquityType     `json:"type,omitzero"`
}

func (t TransactionEquity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TransactionEquity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TransactionEquity) GetAssetType() TransactionEquityAssetType {
	if t == nil {
		return TransactionEquityAssetType("")
	}
	return t.AssetType
}

func (t *TransactionEquity) GetCusip() *string {
	if t == nil {
		return nil
	}
	return t.Cusip
}

func (t *TransactionEquity) GetSymbol() *string {
	if t == nil {
		return nil
	}
	return t.Symbol
}

func (t *TransactionEquity) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TransactionEquity) GetInstrumentID() *int64 {
	if t == nil {
		return nil
	}
	return t.InstrumentID
}

func (t *TransactionEquity) GetNetChange() *float64 {
	if t == nil {
		return nil
	}
	return t.NetChange
}

func (t *TransactionEquity) GetType() *TransactionEquityType {
	if t == nil {
		return nil
	}
	return t.Type
}
