// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type TransactionBaseInstrumentAssetType string

const (
	TransactionBaseInstrumentAssetTypeEquity               TransactionBaseInstrumentAssetType = "EQUITY"
	TransactionBaseInstrumentAssetTypeOption               TransactionBaseInstrumentAssetType = "OPTION"
	TransactionBaseInstrumentAssetTypeIndex                TransactionBaseInstrumentAssetType = "INDEX"
	TransactionBaseInstrumentAssetTypeMutualFund           TransactionBaseInstrumentAssetType = "MUTUAL_FUND"
	TransactionBaseInstrumentAssetTypeCashEquivalent       TransactionBaseInstrumentAssetType = "CASH_EQUIVALENT"
	TransactionBaseInstrumentAssetTypeFixedIncome          TransactionBaseInstrumentAssetType = "FIXED_INCOME"
	TransactionBaseInstrumentAssetTypeCurrency             TransactionBaseInstrumentAssetType = "CURRENCY"
	TransactionBaseInstrumentAssetTypeCollectiveInvestment TransactionBaseInstrumentAssetType = "COLLECTIVE_INVESTMENT"
)

func (e TransactionBaseInstrumentAssetType) ToPointer() *TransactionBaseInstrumentAssetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TransactionBaseInstrumentAssetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EQUITY", "OPTION", "INDEX", "MUTUAL_FUND", "CASH_EQUIVALENT", "FIXED_INCOME", "CURRENCY", "COLLECTIVE_INVESTMENT":
			return true
		}
	}
	return false
}

type TransactionBaseInstrument struct {
	AssetType    TransactionBaseInstrumentAssetType `json:"assetType"`
	Cusip        *string                            `json:"cusip,omitzero"`
	Symbol       *string                            `json:"symbol,omitzero"`
	Description  *string                            `json:"description,omitzero"`
	InstrumentID *int64                             `json:"instrumentId,omitzero"`
	NetChange    *float64                           `json:"netChange,omitzero"`
}

func (t TransactionBaseInstrument) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TransactionBaseInstrument) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TransactionBaseInstrument) GetAssetType() TransactionBaseInstrumentAssetType {
	if t == nil {
		return TransactionBaseInstrumentAssetType("")
	}
	return t.AssetType
}

func (t *TransactionBaseInstrument) GetCusip() *string {
	if t == nil {
		return nil
	}
	return t.Cusip
}

func (t *TransactionBaseInstrument) GetSymbol() *string {
	if t == nil {
		return nil
	}
	return t.Symbol
}

func (t *TransactionBaseInstrument) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TransactionBaseInstrument) GetInstrumentID() *int64 {
	if t == nil {
		return nil
	}
	return t.InstrumentID
}

func (t *TransactionBaseInstrument) GetNetChange() *float64 {
	if t == nil {
		return nil
	}
	return t.NetChange
}
