// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"time"
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type TransactionMutualFundAssetType string

const (
	TransactionMutualFundAssetTypeEquity               TransactionMutualFundAssetType = "EQUITY"
	TransactionMutualFundAssetTypeOption               TransactionMutualFundAssetType = "OPTION"
	TransactionMutualFundAssetTypeIndex                TransactionMutualFundAssetType = "INDEX"
	TransactionMutualFundAssetTypeMutualFund           TransactionMutualFundAssetType = "MUTUAL_FUND"
	TransactionMutualFundAssetTypeCashEquivalent       TransactionMutualFundAssetType = "CASH_EQUIVALENT"
	TransactionMutualFundAssetTypeFixedIncome          TransactionMutualFundAssetType = "FIXED_INCOME"
	TransactionMutualFundAssetTypeCurrency             TransactionMutualFundAssetType = "CURRENCY"
	TransactionMutualFundAssetTypeCollectiveInvestment TransactionMutualFundAssetType = "COLLECTIVE_INVESTMENT"
)

func (e TransactionMutualFundAssetType) ToPointer() *TransactionMutualFundAssetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TransactionMutualFundAssetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EQUITY", "OPTION", "INDEX", "MUTUAL_FUND", "CASH_EQUIVALENT", "FIXED_INCOME", "CURRENCY", "COLLECTIVE_INVESTMENT":
			return true
		}
	}
	return false
}

type TransactionMutualFundType string

const (
	TransactionMutualFundTypeNotApplicable     TransactionMutualFundType = "NOT_APPLICABLE"
	TransactionMutualFundTypeOpenEndNonTaxable TransactionMutualFundType = "OPEN_END_NON_TAXABLE"
	TransactionMutualFundTypeOpenEndTaxable    TransactionMutualFundType = "OPEN_END_TAXABLE"
	TransactionMutualFundTypeNoLoadNonTaxable  TransactionMutualFundType = "NO_LOAD_NON_TAXABLE"
	TransactionMutualFundTypeNoLoadTaxable     TransactionMutualFundType = "NO_LOAD_TAXABLE"
	TransactionMutualFundTypeUnknown           TransactionMutualFundType = "UNKNOWN"
)

func (e TransactionMutualFundType) ToPointer() *TransactionMutualFundType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TransactionMutualFundType) IsExact() bool {
	if e != nil {
		switch *e {
		case "NOT_APPLICABLE", "OPEN_END_NON_TAXABLE", "OPEN_END_TAXABLE", "NO_LOAD_NON_TAXABLE", "NO_LOAD_TAXABLE", "UNKNOWN":
			return true
		}
	}
	return false
}

type TransactionMutualFund struct {
	AssetType            TransactionMutualFundAssetType `json:"assetType"`
	Cusip                *string                        `json:"cusip,omitzero"`
	Symbol               *string                        `json:"symbol,omitzero"`
	Description          *string                        `json:"description,omitzero"`
	InstrumentID         *int64                         `json:"instrumentId,omitzero"`
	NetChange            *float64                       `json:"netChange,omitzero"`
	FundFamilyName       *string                        `json:"fundFamilyName,omitzero"`
	FundFamilySymbol     *string                        `json:"fundFamilySymbol,omitzero"`
	FundGroup            *string                        `json:"fundGroup,omitzero"`
	Type                 *TransactionMutualFundType     `json:"type,omitzero"`
	ExchangeCutoffTime   *time.Time                     `json:"exchangeCutoffTime,omitzero"`
	PurchaseCutoffTime   *time.Time                     `json:"purchaseCutoffTime,omitzero"`
	RedemptionCutoffTime *time.Time                     `json:"redemptionCutoffTime,omitzero"`
}

func (t TransactionMutualFund) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TransactionMutualFund) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TransactionMutualFund) GetAssetType() TransactionMutualFundAssetType {
	if t == nil {
		return TransactionMutualFundAssetType("")
	}
	return t.AssetType
}

func (t *TransactionMutualFund) GetCusip() *string {
	if t == nil {
		return nil
	}
	return t.Cusip
}

func (t *TransactionMutualFund) GetSymbol() *string {
	if t == nil {
		return nil
	}
	return t.Symbol
}

func (t *TransactionMutualFund) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TransactionMutualFund) GetInstrumentID() *int64 {
	if t == nil {
		return nil
	}
	return t.InstrumentID
}

func (t *TransactionMutualFund) GetNetChange() *float64 {
	if t == nil {
		return nil
	}
	return t.NetChange
}

func (t *TransactionMutualFund) GetFundFamilyName() *string {
	if t == nil {
		return nil
	}
	return t.FundFamilyName
}

func (t *TransactionMutualFund) GetFundFamilySymbol() *string {
	if t == nil {
		return nil
	}
	return t.FundFamilySymbol
}

func (t *TransactionMutualFund) GetFundGroup() *string {
	if t == nil {
		return nil
	}
	return t.FundGroup
}

func (t *TransactionMutualFund) GetType() *TransactionMutualFundType {
	if t == nil {
		return nil
	}
	return t.Type
}

func (t *TransactionMutualFund) GetExchangeCutoffTime() *time.Time {
	if t == nil {
		return nil
	}
	return t.ExchangeCutoffTime
}

func (t *TransactionMutualFund) GetPurchaseCutoffTime() *time.Time {
	if t == nil {
		return nil
	}
	return t.PurchaseCutoffTime
}

func (t *TransactionMutualFund) GetRedemptionCutoffTime() *time.Time {
	if t == nil {
		return nil
	}
	return t.RedemptionCutoffTime
}
