// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type TransactionInstrumentType string

const (
	TransactionInstrumentTypeTransactionCashEquivalent TransactionInstrumentType = "TransactionCashEquivalent"
	TransactionInstrumentTypeCollectiveInvestment      TransactionInstrumentType = "CollectiveInvestment"
	TransactionInstrumentTypeTransactionBaseInstrument TransactionInstrumentType = "TransactionBaseInstrument"
	TransactionInstrumentTypeTransactionEquity         TransactionInstrumentType = "TransactionEquity"
	TransactionInstrumentTypeTransactionFixedIncome    TransactionInstrumentType = "TransactionFixedIncome"
	TransactionInstrumentTypeForex                     TransactionInstrumentType = "Forex"
	TransactionInstrumentTypeFuture                    TransactionInstrumentType = "Future"
	TransactionInstrumentTypeIndex                     TransactionInstrumentType = "Index"
	TransactionInstrumentTypeTransactionMutualFund     TransactionInstrumentType = "TransactionMutualFund"
	TransactionInstrumentTypeTransactionOption1        TransactionInstrumentType = "TransactionOption_1"
	TransactionInstrumentTypeProduct                   TransactionInstrumentType = "Product"
)

type TransactionInstrument struct {
	TransactionCashEquivalent *TransactionCashEquivalent `queryParam:"inline" union:"member"`
	CollectiveInvestment      *CollectiveInvestment      `queryParam:"inline" union:"member"`
	TransactionBaseInstrument *TransactionBaseInstrument `queryParam:"inline" union:"member"`
	TransactionEquity         *TransactionEquity         `queryParam:"inline" union:"member"`
	TransactionFixedIncome    *TransactionFixedIncome    `queryParam:"inline" union:"member"`
	Forex                     *Forex                     `queryParam:"inline" union:"member"`
	Future                    *Future                    `queryParam:"inline" union:"member"`
	Index                     *Index                     `queryParam:"inline" union:"member"`
	TransactionMutualFund     *TransactionMutualFund     `queryParam:"inline" union:"member"`
	TransactionOption1        *TransactionOption1        `queryParam:"inline" union:"member"`
	Product                   *Product                   `queryParam:"inline" union:"member"`

	Type TransactionInstrumentType
}

func CreateTransactionInstrumentTransactionCashEquivalent(transactionCashEquivalent TransactionCashEquivalent) TransactionInstrument {
	typ := TransactionInstrumentTypeTransactionCashEquivalent

	return TransactionInstrument{
		TransactionCashEquivalent: &transactionCashEquivalent,
		Type:                      typ,
	}
}

func CreateTransactionInstrumentCollectiveInvestment(collectiveInvestment CollectiveInvestment) TransactionInstrument {
	typ := TransactionInstrumentTypeCollectiveInvestment

	return TransactionInstrument{
		CollectiveInvestment: &collectiveInvestment,
		Type:                 typ,
	}
}

func CreateTransactionInstrumentTransactionBaseInstrument(transactionBaseInstrument TransactionBaseInstrument) TransactionInstrument {
	typ := TransactionInstrumentTypeTransactionBaseInstrument

	return TransactionInstrument{
		TransactionBaseInstrument: &transactionBaseInstrument,
		Type:                      typ,
	}
}

func CreateTransactionInstrumentTransactionEquity(transactionEquity TransactionEquity) TransactionInstrument {
	typ := TransactionInstrumentTypeTransactionEquity

	return TransactionInstrument{
		TransactionEquity: &transactionEquity,
		Type:              typ,
	}
}

func CreateTransactionInstrumentTransactionFixedIncome(transactionFixedIncome TransactionFixedIncome) TransactionInstrument {
	typ := TransactionInstrumentTypeTransactionFixedIncome

	return TransactionInstrument{
		TransactionFixedIncome: &transactionFixedIncome,
		Type:                   typ,
	}
}

func CreateTransactionInstrumentForex(forex Forex) TransactionInstrument {
	typ := TransactionInstrumentTypeForex

	return TransactionInstrument{
		Forex: &forex,
		Type:  typ,
	}
}

func CreateTransactionInstrumentFuture(future Future) TransactionInstrument {
	typ := TransactionInstrumentTypeFuture

	return TransactionInstrument{
		Future: &future,
		Type:   typ,
	}
}

func CreateTransactionInstrumentIndex(index Index) TransactionInstrument {
	typ := TransactionInstrumentTypeIndex

	return TransactionInstrument{
		Index: &index,
		Type:  typ,
	}
}

func CreateTransactionInstrumentTransactionMutualFund(transactionMutualFund TransactionMutualFund) TransactionInstrument {
	typ := TransactionInstrumentTypeTransactionMutualFund

	return TransactionInstrument{
		TransactionMutualFund: &transactionMutualFund,
		Type:                  typ,
	}
}

func CreateTransactionInstrumentTransactionOption1(transactionOption1 TransactionOption1) TransactionInstrument {
	typ := TransactionInstrumentTypeTransactionOption1

	return TransactionInstrument{
		TransactionOption1: &transactionOption1,
		Type:               typ,
	}
}

func CreateTransactionInstrumentProduct(product Product) TransactionInstrument {
	typ := TransactionInstrumentTypeProduct

	return TransactionInstrument{
		Product: &product,
		Type:    typ,
	}
}

func (u *TransactionInstrument) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var transactionCashEquivalent TransactionCashEquivalent = TransactionCashEquivalent{}
	if err := utils.UnmarshalJSON(data, &transactionCashEquivalent, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  TransactionInstrumentTypeTransactionCashEquivalent,
			Value: &transactionCashEquivalent,
		})
	}

	var collectiveInvestment CollectiveInvestment = CollectiveInvestment{}
	if err := utils.UnmarshalJSON(data, &collectiveInvestment, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  TransactionInstrumentTypeCollectiveInvestment,
			Value: &collectiveInvestment,
		})
	}

	var transactionBaseInstrument TransactionBaseInstrument = TransactionBaseInstrument{}
	if err := utils.UnmarshalJSON(data, &transactionBaseInstrument, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  TransactionInstrumentTypeTransactionBaseInstrument,
			Value: &transactionBaseInstrument,
		})
	}

	var transactionEquity TransactionEquity = TransactionEquity{}
	if err := utils.UnmarshalJSON(data, &transactionEquity, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  TransactionInstrumentTypeTransactionEquity,
			Value: &transactionEquity,
		})
	}

	var transactionFixedIncome TransactionFixedIncome = TransactionFixedIncome{}
	if err := utils.UnmarshalJSON(data, &transactionFixedIncome, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  TransactionInstrumentTypeTransactionFixedIncome,
			Value: &transactionFixedIncome,
		})
	}

	var forex Forex = Forex{}
	if err := utils.UnmarshalJSON(data, &forex, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  TransactionInstrumentTypeForex,
			Value: &forex,
		})
	}

	var future Future = Future{}
	if err := utils.UnmarshalJSON(data, &future, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  TransactionInstrumentTypeFuture,
			Value: &future,
		})
	}

	var index Index = Index{}
	if err := utils.UnmarshalJSON(data, &index, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  TransactionInstrumentTypeIndex,
			Value: &index,
		})
	}

	var transactionMutualFund TransactionMutualFund = TransactionMutualFund{}
	if err := utils.UnmarshalJSON(data, &transactionMutualFund, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  TransactionInstrumentTypeTransactionMutualFund,
			Value: &transactionMutualFund,
		})
	}

	var transactionOption1 TransactionOption1 = TransactionOption1{}
	if err := utils.UnmarshalJSON(data, &transactionOption1, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  TransactionInstrumentTypeTransactionOption1,
			Value: &transactionOption1,
		})
	}

	var product Product = Product{}
	if err := utils.UnmarshalJSON(data, &product, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  TransactionInstrumentTypeProduct,
			Value: &product,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for TransactionInstrument", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for TransactionInstrument", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(TransactionInstrumentType)
	switch best.Type {
	case TransactionInstrumentTypeTransactionCashEquivalent:
		u.TransactionCashEquivalent = best.Value.(*TransactionCashEquivalent)
		return nil
	case TransactionInstrumentTypeCollectiveInvestment:
		u.CollectiveInvestment = best.Value.(*CollectiveInvestment)
		return nil
	case TransactionInstrumentTypeTransactionBaseInstrument:
		u.TransactionBaseInstrument = best.Value.(*TransactionBaseInstrument)
		return nil
	case TransactionInstrumentTypeTransactionEquity:
		u.TransactionEquity = best.Value.(*TransactionEquity)
		return nil
	case TransactionInstrumentTypeTransactionFixedIncome:
		u.TransactionFixedIncome = best.Value.(*TransactionFixedIncome)
		return nil
	case TransactionInstrumentTypeForex:
		u.Forex = best.Value.(*Forex)
		return nil
	case TransactionInstrumentTypeFuture:
		u.Future = best.Value.(*Future)
		return nil
	case TransactionInstrumentTypeIndex:
		u.Index = best.Value.(*Index)
		return nil
	case TransactionInstrumentTypeTransactionMutualFund:
		u.TransactionMutualFund = best.Value.(*TransactionMutualFund)
		return nil
	case TransactionInstrumentTypeTransactionOption1:
		u.TransactionOption1 = best.Value.(*TransactionOption1)
		return nil
	case TransactionInstrumentTypeProduct:
		u.Product = best.Value.(*Product)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for TransactionInstrument", string(data))
}

func (u TransactionInstrument) MarshalJSON() ([]byte, error) {
	if u.TransactionCashEquivalent != nil {
		return utils.MarshalJSON(u.TransactionCashEquivalent, "", true)
	}

	if u.CollectiveInvestment != nil {
		return utils.MarshalJSON(u.CollectiveInvestment, "", true)
	}

	if u.TransactionBaseInstrument != nil {
		return utils.MarshalJSON(u.TransactionBaseInstrument, "", true)
	}

	if u.TransactionEquity != nil {
		return utils.MarshalJSON(u.TransactionEquity, "", true)
	}

	if u.TransactionFixedIncome != nil {
		return utils.MarshalJSON(u.TransactionFixedIncome, "", true)
	}

	if u.Forex != nil {
		return utils.MarshalJSON(u.Forex, "", true)
	}

	if u.Future != nil {
		return utils.MarshalJSON(u.Future, "", true)
	}

	if u.Index != nil {
		return utils.MarshalJSON(u.Index, "", true)
	}

	if u.TransactionMutualFund != nil {
		return utils.MarshalJSON(u.TransactionMutualFund, "", true)
	}

	if u.TransactionOption1 != nil {
		return utils.MarshalJSON(u.TransactionOption1, "", true)
	}

	if u.Product != nil {
		return utils.MarshalJSON(u.Product, "", true)
	}

	return nil, errors.New("could not marshal union type TransactionInstrument: all fields are null")
}
