// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"time"
	"undefined/internal/utils"
)

type TransactionOptionAssetType string

const (
	TransactionOptionAssetTypeEquity               TransactionOptionAssetType = "EQUITY"
	TransactionOptionAssetTypeOption               TransactionOptionAssetType = "OPTION"
	TransactionOptionAssetTypeIndex                TransactionOptionAssetType = "INDEX"
	TransactionOptionAssetTypeMutualFund           TransactionOptionAssetType = "MUTUAL_FUND"
	TransactionOptionAssetTypeCashEquivalent       TransactionOptionAssetType = "CASH_EQUIVALENT"
	TransactionOptionAssetTypeFixedIncome          TransactionOptionAssetType = "FIXED_INCOME"
	TransactionOptionAssetTypeCurrency             TransactionOptionAssetType = "CURRENCY"
	TransactionOptionAssetTypeCollectiveInvestment TransactionOptionAssetType = "COLLECTIVE_INVESTMENT"
)

func (e TransactionOptionAssetType) ToPointer() *TransactionOptionAssetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TransactionOptionAssetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EQUITY", "OPTION", "INDEX", "MUTUAL_FUND", "CASH_EQUIVALENT", "FIXED_INCOME", "CURRENCY", "COLLECTIVE_INVESTMENT":
			return true
		}
	}
	return false
}

type TransactionOptionPutCall string

const (
	TransactionOptionPutCallPut     TransactionOptionPutCall = "PUT"
	TransactionOptionPutCallCall    TransactionOptionPutCall = "CALL"
	TransactionOptionPutCallUnknown TransactionOptionPutCall = "UNKNOWN"
)

func (e TransactionOptionPutCall) ToPointer() *TransactionOptionPutCall {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TransactionOptionPutCall) IsExact() bool {
	if e != nil {
		switch *e {
		case "PUT", "CALL", "UNKNOWN":
			return true
		}
	}
	return false
}

type TransactionOptionType string

const (
	TransactionOptionTypeVanilla TransactionOptionType = "VANILLA"
	TransactionOptionTypeBinary  TransactionOptionType = "BINARY"
	TransactionOptionTypeBarrier TransactionOptionType = "BARRIER"
	TransactionOptionTypeUnknown TransactionOptionType = "UNKNOWN"
)

func (e TransactionOptionType) ToPointer() *TransactionOptionType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TransactionOptionType) IsExact() bool {
	if e != nil {
		switch *e {
		case "VANILLA", "BINARY", "BARRIER", "UNKNOWN":
			return true
		}
	}
	return false
}

type TransactionOption1 struct {
	AssetType               TransactionOptionAssetType         `json:"assetType"`
	Cusip                   *string                            `json:"cusip,omitzero"`
	Symbol                  *string                            `json:"symbol,omitzero"`
	Description             *string                            `json:"description,omitzero"`
	InstrumentID            *int64                             `json:"instrumentId,omitzero"`
	NetChange               *float64                           `json:"netChange,omitzero"`
	ExpirationDate          *time.Time                         `json:"expirationDate,omitzero"`
	OptionDeliverables      []TransactionAPIOptionDeliverable1 `json:"optionDeliverables,omitzero"`
	OptionPremiumMultiplier *int64                             `json:"optionPremiumMultiplier,omitzero"`
	PutCall                 *TransactionOptionPutCall          `json:"putCall,omitzero"`
	StrikePrice             *float64                           `json:"strikePrice,omitzero"`
	Type                    *TransactionOptionType             `json:"type,omitzero"`
	UnderlyingSymbol        *string                            `json:"underlyingSymbol,omitzero"`
	UnderlyingCusip         *string                            `json:"underlyingCusip,omitzero"`
	Deliverable             *TransactionInstrument             `json:"deliverable,omitzero"`
}

func (t TransactionOption1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TransactionOption1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TransactionOption1) GetAssetType() TransactionOptionAssetType {
	if t == nil {
		return TransactionOptionAssetType("")
	}
	return t.AssetType
}

func (t *TransactionOption1) GetCusip() *string {
	if t == nil {
		return nil
	}
	return t.Cusip
}

func (t *TransactionOption1) GetSymbol() *string {
	if t == nil {
		return nil
	}
	return t.Symbol
}

func (t *TransactionOption1) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TransactionOption1) GetInstrumentID() *int64 {
	if t == nil {
		return nil
	}
	return t.InstrumentID
}

func (t *TransactionOption1) GetNetChange() *float64 {
	if t == nil {
		return nil
	}
	return t.NetChange
}

func (t *TransactionOption1) GetExpirationDate() *time.Time {
	if t == nil {
		return nil
	}
	return t.ExpirationDate
}

func (t *TransactionOption1) GetOptionDeliverables() []TransactionAPIOptionDeliverable1 {
	if t == nil {
		return nil
	}
	return t.OptionDeliverables
}

func (t *TransactionOption1) GetOptionPremiumMultiplier() *int64 {
	if t == nil {
		return nil
	}
	return t.OptionPremiumMultiplier
}

func (t *TransactionOption1) GetPutCall() *TransactionOptionPutCall {
	if t == nil {
		return nil
	}
	return t.PutCall
}

func (t *TransactionOption1) GetStrikePrice() *float64 {
	if t == nil {
		return nil
	}
	return t.StrikePrice
}

func (t *TransactionOption1) GetType() *TransactionOptionType {
	if t == nil {
		return nil
	}
	return t.Type
}

func (t *TransactionOption1) GetUnderlyingSymbol() *string {
	if t == nil {
		return nil
	}
	return t.UnderlyingSymbol
}

func (t *TransactionOption1) GetUnderlyingCusip() *string {
	if t == nil {
		return nil
	}
	return t.UnderlyingCusip
}

func (t *TransactionOption1) GetDeliverable() *TransactionInstrument {
	if t == nil {
		return nil
	}
	return t.Deliverable
}
