// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type TransactionCashEquivalentAssetType string

const (
	TransactionCashEquivalentAssetTypeEquity               TransactionCashEquivalentAssetType = "EQUITY"
	TransactionCashEquivalentAssetTypeOption               TransactionCashEquivalentAssetType = "OPTION"
	TransactionCashEquivalentAssetTypeIndex                TransactionCashEquivalentAssetType = "INDEX"
	TransactionCashEquivalentAssetTypeMutualFund           TransactionCashEquivalentAssetType = "MUTUAL_FUND"
	TransactionCashEquivalentAssetTypeCashEquivalent       TransactionCashEquivalentAssetType = "CASH_EQUIVALENT"
	TransactionCashEquivalentAssetTypeFixedIncome          TransactionCashEquivalentAssetType = "FIXED_INCOME"
	TransactionCashEquivalentAssetTypeCurrency             TransactionCashEquivalentAssetType = "CURRENCY"
	TransactionCashEquivalentAssetTypeCollectiveInvestment TransactionCashEquivalentAssetType = "COLLECTIVE_INVESTMENT"
)

func (e TransactionCashEquivalentAssetType) ToPointer() *TransactionCashEquivalentAssetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TransactionCashEquivalentAssetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EQUITY", "OPTION", "INDEX", "MUTUAL_FUND", "CASH_EQUIVALENT", "FIXED_INCOME", "CURRENCY", "COLLECTIVE_INVESTMENT":
			return true
		}
	}
	return false
}

type TransactionCashEquivalentType string

const (
	TransactionCashEquivalentTypeSweepVehicle    TransactionCashEquivalentType = "SWEEP_VEHICLE"
	TransactionCashEquivalentTypeSavings         TransactionCashEquivalentType = "SAVINGS"
	TransactionCashEquivalentTypeMoneyMarketFund TransactionCashEquivalentType = "MONEY_MARKET_FUND"
	TransactionCashEquivalentTypeUnknown         TransactionCashEquivalentType = "UNKNOWN"
)

func (e TransactionCashEquivalentType) ToPointer() *TransactionCashEquivalentType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TransactionCashEquivalentType) IsExact() bool {
	if e != nil {
		switch *e {
		case "SWEEP_VEHICLE", "SAVINGS", "MONEY_MARKET_FUND", "UNKNOWN":
			return true
		}
	}
	return false
}

type TransactionCashEquivalent struct {
	AssetType    TransactionCashEquivalentAssetType `json:"assetType"`
	Cusip        *string                            `json:"cusip,omitzero"`
	Symbol       *string                            `json:"symbol,omitzero"`
	Description  *string                            `json:"description,omitzero"`
	InstrumentID *int64                             `json:"instrumentId,omitzero"`
	NetChange    *float64                           `json:"netChange,omitzero"`
	Type         *TransactionCashEquivalentType     `json:"type,omitzero"`
}

func (t TransactionCashEquivalent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TransactionCashEquivalent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TransactionCashEquivalent) GetAssetType() TransactionCashEquivalentAssetType {
	if t == nil {
		return TransactionCashEquivalentAssetType("")
	}
	return t.AssetType
}

func (t *TransactionCashEquivalent) GetCusip() *string {
	if t == nil {
		return nil
	}
	return t.Cusip
}

func (t *TransactionCashEquivalent) GetSymbol() *string {
	if t == nil {
		return nil
	}
	return t.Symbol
}

func (t *TransactionCashEquivalent) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TransactionCashEquivalent) GetInstrumentID() *int64 {
	if t == nil {
		return nil
	}
	return t.InstrumentID
}

func (t *TransactionCashEquivalent) GetNetChange() *float64 {
	if t == nil {
		return nil
	}
	return t.NetChange
}

func (t *TransactionCashEquivalent) GetType() *TransactionCashEquivalentType {
	if t == nil {
		return nil
	}
	return t.Type
}
