// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

type TransactionAPIOptionDeliverable1 struct {
	RootSymbol        *string                `json:"rootSymbol,omitzero"`
	StrikePercent     *int64                 `json:"strikePercent,omitzero"`
	DeliverableNumber *int64                 `json:"deliverableNumber,omitzero"`
	DeliverableUnits  *float64               `json:"deliverableUnits,omitzero"`
	Deliverable       *TransactionInstrument `json:"deliverable,omitzero"`
	AssetType         *AssetType             `json:"assetType,omitzero"`
}

func (t TransactionAPIOptionDeliverable1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TransactionAPIOptionDeliverable1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TransactionAPIOptionDeliverable1) GetRootSymbol() *string {
	if t == nil {
		return nil
	}
	return t.RootSymbol
}

func (t *TransactionAPIOptionDeliverable1) GetStrikePercent() *int64 {
	if t == nil {
		return nil
	}
	return t.StrikePercent
}

func (t *TransactionAPIOptionDeliverable1) GetDeliverableNumber() *int64 {
	if t == nil {
		return nil
	}
	return t.DeliverableNumber
}

func (t *TransactionAPIOptionDeliverable1) GetDeliverableUnits() *float64 {
	if t == nil {
		return nil
	}
	return t.DeliverableUnits
}

func (t *TransactionAPIOptionDeliverable1) GetDeliverable() *TransactionInstrument {
	if t == nil {
		return nil
	}
	return t.Deliverable
}

func (t *TransactionAPIOptionDeliverable1) GetAssetType() *AssetType {
	if t == nil {
		return nil
	}
	return t.AssetType
}
