// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TransactionType string

const (
	TransactionTypeTrade              TransactionType = "TRADE"
	TransactionTypeReceiveAndDeliver  TransactionType = "RECEIVE_AND_DELIVER"
	TransactionTypeDividendOrInterest TransactionType = "DIVIDEND_OR_INTEREST"
	TransactionTypeAchReceipt         TransactionType = "ACH_RECEIPT"
	TransactionTypeAchDisbursement    TransactionType = "ACH_DISBURSEMENT"
	TransactionTypeCashReceipt        TransactionType = "CASH_RECEIPT"
	TransactionTypeCashDisbursement   TransactionType = "CASH_DISBURSEMENT"
	TransactionTypeElectronicFund     TransactionType = "ELECTRONIC_FUND"
	TransactionTypeWireOut            TransactionType = "WIRE_OUT"
	TransactionTypeWireIn             TransactionType = "WIRE_IN"
	TransactionTypeJournal            TransactionType = "JOURNAL"
	TransactionTypeMemorandum         TransactionType = "MEMORANDUM"
	TransactionTypeMarginCall         TransactionType = "MARGIN_CALL"
	TransactionTypeMoneyMarket        TransactionType = "MONEY_MARKET"
	TransactionTypeSmaAdjustment      TransactionType = "SMA_ADJUSTMENT"
)

func (e TransactionType) ToPointer() *TransactionType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TransactionType) IsExact() bool {
	if e != nil {
		switch *e {
		case "TRADE", "RECEIVE_AND_DELIVER", "DIVIDEND_OR_INTEREST", "ACH_RECEIPT", "ACH_DISBURSEMENT", "CASH_RECEIPT", "CASH_DISBURSEMENT", "ELECTRONIC_FUND", "WIRE_OUT", "WIRE_IN", "JOURNAL", "MEMORANDUM", "MARGIN_CALL", "MONEY_MARKET", "SMA_ADJUSTMENT":
			return true
		}
	}
	return false
}
