// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
	"time"
)

type TransactionFixedIncomeAssetType string

const (
	TransactionFixedIncomeAssetTypeEquity               TransactionFixedIncomeAssetType = "EQUITY"
	TransactionFixedIncomeAssetTypeOption               TransactionFixedIncomeAssetType = "OPTION"
	TransactionFixedIncomeAssetTypeIndex                TransactionFixedIncomeAssetType = "INDEX"
	TransactionFixedIncomeAssetTypeMutualFund           TransactionFixedIncomeAssetType = "MUTUAL_FUND"
	TransactionFixedIncomeAssetTypeCashEquivalent       TransactionFixedIncomeAssetType = "CASH_EQUIVALENT"
	TransactionFixedIncomeAssetTypeFixedIncome          TransactionFixedIncomeAssetType = "FIXED_INCOME"
	TransactionFixedIncomeAssetTypeCurrency             TransactionFixedIncomeAssetType = "CURRENCY"
	TransactionFixedIncomeAssetTypeCollectiveInvestment TransactionFixedIncomeAssetType = "COLLECTIVE_INVESTMENT"
)

func (e TransactionFixedIncomeAssetType) ToPointer() *TransactionFixedIncomeAssetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TransactionFixedIncomeAssetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EQUITY", "OPTION", "INDEX", "MUTUAL_FUND", "CASH_EQUIVALENT", "FIXED_INCOME", "CURRENCY", "COLLECTIVE_INVESTMENT":
			return true
		}
	}
	return false
}

type TransactionFixedIncomeType string

const (
	TransactionFixedIncomeTypeBondUnit                         TransactionFixedIncomeType = "BOND_UNIT"
	TransactionFixedIncomeTypeCertificateOfDeposit             TransactionFixedIncomeType = "CERTIFICATE_OF_DEPOSIT"
	TransactionFixedIncomeTypeConvertibleBond                  TransactionFixedIncomeType = "CONVERTIBLE_BOND"
	TransactionFixedIncomeTypeCollateralizedMortgageObligation TransactionFixedIncomeType = "COLLATERALIZED_MORTGAGE_OBLIGATION"
	TransactionFixedIncomeTypeCorporateBond                    TransactionFixedIncomeType = "CORPORATE_BOND"
	TransactionFixedIncomeTypeGovernmentMortgage               TransactionFixedIncomeType = "GOVERNMENT_MORTGAGE"
	TransactionFixedIncomeTypeGnmaBonds                        TransactionFixedIncomeType = "GNMA_BONDS"
	TransactionFixedIncomeTypeMunicipalAssessmentDistrict      TransactionFixedIncomeType = "MUNICIPAL_ASSESSMENT_DISTRICT"
	TransactionFixedIncomeTypeMunicipalBond                    TransactionFixedIncomeType = "MUNICIPAL_BOND"
	TransactionFixedIncomeTypeOtherGovernment                  TransactionFixedIncomeType = "OTHER_GOVERNMENT"
	TransactionFixedIncomeTypeShortTermPaper                   TransactionFixedIncomeType = "SHORT_TERM_PAPER"
	TransactionFixedIncomeTypeUsTreasuryBond                   TransactionFixedIncomeType = "US_TREASURY_BOND"
	TransactionFixedIncomeTypeUsTreasuryBill                   TransactionFixedIncomeType = "US_TREASURY_BILL"
	TransactionFixedIncomeTypeUsTreasuryNote                   TransactionFixedIncomeType = "US_TREASURY_NOTE"
	TransactionFixedIncomeTypeUsTreasuryZeroCoupon             TransactionFixedIncomeType = "US_TREASURY_ZERO_COUPON"
	TransactionFixedIncomeTypeAgencyBond                       TransactionFixedIncomeType = "AGENCY_BOND"
	TransactionFixedIncomeTypeWhenAsAndIfIssuedBond            TransactionFixedIncomeType = "WHEN_AS_AND_IF_ISSUED_BOND"
	TransactionFixedIncomeTypeAssetBackedSecurity              TransactionFixedIncomeType = "ASSET_BACKED_SECURITY"
	TransactionFixedIncomeTypeUnknown                          TransactionFixedIncomeType = "UNKNOWN"
)

func (e TransactionFixedIncomeType) ToPointer() *TransactionFixedIncomeType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TransactionFixedIncomeType) IsExact() bool {
	if e != nil {
		switch *e {
		case "BOND_UNIT", "CERTIFICATE_OF_DEPOSIT", "CONVERTIBLE_BOND", "COLLATERALIZED_MORTGAGE_OBLIGATION", "CORPORATE_BOND", "GOVERNMENT_MORTGAGE", "GNMA_BONDS", "MUNICIPAL_ASSESSMENT_DISTRICT", "MUNICIPAL_BOND", "OTHER_GOVERNMENT", "SHORT_TERM_PAPER", "US_TREASURY_BOND", "US_TREASURY_BILL", "US_TREASURY_NOTE", "US_TREASURY_ZERO_COUPON", "AGENCY_BOND", "WHEN_AS_AND_IF_ISSUED_BOND", "ASSET_BACKED_SECURITY", "UNKNOWN":
			return true
		}
	}
	return false
}

type TransactionFixedIncome struct {
	AssetType    TransactionFixedIncomeAssetType `json:"assetType"`
	Cusip        *string                         `json:"cusip,omitzero"`
	Symbol       *string                         `json:"symbol,omitzero"`
	Description  *string                         `json:"description,omitzero"`
	InstrumentID *int64                          `json:"instrumentId,omitzero"`
	NetChange    *float64                        `json:"netChange,omitzero"`
	Type         *TransactionFixedIncomeType     `json:"type,omitzero"`
	MaturityDate *time.Time                      `json:"maturityDate,omitzero"`
	Factor       *float64                        `json:"factor,omitzero"`
	Multiplier   *float64                        `json:"multiplier,omitzero"`
	VariableRate *float64                        `json:"variableRate,omitzero"`
}

func (t TransactionFixedIncome) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TransactionFixedIncome) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TransactionFixedIncome) GetAssetType() TransactionFixedIncomeAssetType {
	if t == nil {
		return TransactionFixedIncomeAssetType("")
	}
	return t.AssetType
}

func (t *TransactionFixedIncome) GetCusip() *string {
	if t == nil {
		return nil
	}
	return t.Cusip
}

func (t *TransactionFixedIncome) GetSymbol() *string {
	if t == nil {
		return nil
	}
	return t.Symbol
}

func (t *TransactionFixedIncome) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TransactionFixedIncome) GetInstrumentID() *int64 {
	if t == nil {
		return nil
	}
	return t.InstrumentID
}

func (t *TransactionFixedIncome) GetNetChange() *float64 {
	if t == nil {
		return nil
	}
	return t.NetChange
}

func (t *TransactionFixedIncome) GetType() *TransactionFixedIncomeType {
	if t == nil {
		return nil
	}
	return t.Type
}

func (t *TransactionFixedIncome) GetMaturityDate() *time.Time {
	if t == nil {
		return nil
	}
	return t.MaturityDate
}

func (t *TransactionFixedIncome) GetFactor() *float64 {
	if t == nil {
		return nil
	}
	return t.Factor
}

func (t *TransactionFixedIncome) GetMultiplier() *float64 {
	if t == nil {
		return nil
	}
	return t.Multiplier
}

func (t *TransactionFixedIncome) GetVariableRate() *float64 {
	if t == nil {
		return nil
	}
	return t.VariableRate
}
