// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ExchangeName string

const (
	ExchangeNameInd  ExchangeName = "IND"
	ExchangeNameAse  ExchangeName = "ASE"
	ExchangeNameNys  ExchangeName = "NYS"
	ExchangeNameNas  ExchangeName = "NAS"
	ExchangeNameNap  ExchangeName = "NAP"
	ExchangeNamePac  ExchangeName = "PAC"
	ExchangeNameOpr  ExchangeName = "OPR"
	ExchangeNameBats ExchangeName = "BATS"
)

func (e ExchangeName) ToPointer() *ExchangeName {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ExchangeName) IsExact() bool {
	if e != nil {
		switch *e {
		case "IND", "ASE", "NYS", "NAS", "NAP", "PAC", "OPR", "BATS":
			return true
		}
	}
	return false
}

type Underlying struct {
	Ask               *float64      `json:"ask,omitzero"`
	AskSize           *int          `json:"askSize,omitzero"`
	Bid               *float64      `json:"bid,omitzero"`
	BidSize           *int          `json:"bidSize,omitzero"`
	Change            *float64      `json:"change,omitzero"`
	Close             *float64      `json:"close,omitzero"`
	Delayed           *bool         `json:"delayed,omitzero"`
	Description       *string       `json:"description,omitzero"`
	ExchangeName      *ExchangeName `json:"exchangeName,omitzero"`
	FiftyTwoWeekHigh  *float64      `json:"fiftyTwoWeekHigh,omitzero"`
	FiftyTwoWeekLow   *float64      `json:"fiftyTwoWeekLow,omitzero"`
	HighPrice         *float64      `json:"highPrice,omitzero"`
	Last              *float64      `json:"last,omitzero"`
	LowPrice          *float64      `json:"lowPrice,omitzero"`
	Mark              *float64      `json:"mark,omitzero"`
	MarkChange        *float64      `json:"markChange,omitzero"`
	MarkPercentChange *float64      `json:"markPercentChange,omitzero"`
	OpenPrice         *float64      `json:"openPrice,omitzero"`
	PercentChange     *float64      `json:"percentChange,omitzero"`
	QuoteTime         *int64        `json:"quoteTime,omitzero"`
	Symbol            *string       `json:"symbol,omitzero"`
	TotalVolume       *int64        `json:"totalVolume,omitzero"`
	TradeTime         *int64        `json:"tradeTime,omitzero"`
}

func (u *Underlying) GetAsk() *float64 {
	if u == nil {
		return nil
	}
	return u.Ask
}

func (u *Underlying) GetAskSize() *int {
	if u == nil {
		return nil
	}
	return u.AskSize
}

func (u *Underlying) GetBid() *float64 {
	if u == nil {
		return nil
	}
	return u.Bid
}

func (u *Underlying) GetBidSize() *int {
	if u == nil {
		return nil
	}
	return u.BidSize
}

func (u *Underlying) GetChange() *float64 {
	if u == nil {
		return nil
	}
	return u.Change
}

func (u *Underlying) GetClose() *float64 {
	if u == nil {
		return nil
	}
	return u.Close
}

func (u *Underlying) GetDelayed() *bool {
	if u == nil {
		return nil
	}
	return u.Delayed
}

func (u *Underlying) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *Underlying) GetExchangeName() *ExchangeName {
	if u == nil {
		return nil
	}
	return u.ExchangeName
}

func (u *Underlying) GetFiftyTwoWeekHigh() *float64 {
	if u == nil {
		return nil
	}
	return u.FiftyTwoWeekHigh
}

func (u *Underlying) GetFiftyTwoWeekLow() *float64 {
	if u == nil {
		return nil
	}
	return u.FiftyTwoWeekLow
}

func (u *Underlying) GetHighPrice() *float64 {
	if u == nil {
		return nil
	}
	return u.HighPrice
}

func (u *Underlying) GetLast() *float64 {
	if u == nil {
		return nil
	}
	return u.Last
}

func (u *Underlying) GetLowPrice() *float64 {
	if u == nil {
		return nil
	}
	return u.LowPrice
}

func (u *Underlying) GetMark() *float64 {
	if u == nil {
		return nil
	}
	return u.Mark
}

func (u *Underlying) GetMarkChange() *float64 {
	if u == nil {
		return nil
	}
	return u.MarkChange
}

func (u *Underlying) GetMarkPercentChange() *float64 {
	if u == nil {
		return nil
	}
	return u.MarkPercentChange
}

func (u *Underlying) GetOpenPrice() *float64 {
	if u == nil {
		return nil
	}
	return u.OpenPrice
}

func (u *Underlying) GetPercentChange() *float64 {
	if u == nil {
		return nil
	}
	return u.PercentChange
}

func (u *Underlying) GetQuoteTime() *int64 {
	if u == nil {
		return nil
	}
	return u.QuoteTime
}

func (u *Underlying) GetSymbol() *string {
	if u == nil {
		return nil
	}
	return u.Symbol
}

func (u *Underlying) GetTotalVolume() *int64 {
	if u == nil {
		return nil
	}
	return u.TotalVolume
}

func (u *Underlying) GetTradeTime() *int64 {
	if u == nil {
		return nil
	}
	return u.TradeTime
}
