// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"undefined/internal/utils"
)

type UserPreferenceAccount struct {
	AccountNumber  *string `json:"accountNumber,omitzero"`
	PrimaryAccount *bool   `default:"false" json:"primaryAccount"`
	Type           *string `json:"type,omitzero"`
	NickName       *string `json:"nickName,omitzero"`
	// Green | Blue
	AccountColor       *string `json:"accountColor,omitzero"`
	DisplayAcctID      *string `json:"displayAcctId,omitzero"`
	AutoPositionEffect *bool   `default:"false" json:"autoPositionEffect"`
}

func (u UserPreferenceAccount) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserPreferenceAccount) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UserPreferenceAccount) GetAccountNumber() *string {
	if u == nil {
		return nil
	}
	return u.AccountNumber
}

func (u *UserPreferenceAccount) GetPrimaryAccount() *bool {
	if u == nil {
		return nil
	}
	return u.PrimaryAccount
}

func (u *UserPreferenceAccount) GetType() *string {
	if u == nil {
		return nil
	}
	return u.Type
}

func (u *UserPreferenceAccount) GetNickName() *string {
	if u == nil {
		return nil
	}
	return u.NickName
}

func (u *UserPreferenceAccount) GetAccountColor() *string {
	if u == nil {
		return nil
	}
	return u.AccountColor
}

func (u *UserPreferenceAccount) GetDisplayAcctID() *string {
	if u == nil {
		return nil
	}
	return u.DisplayAcctID
}

func (u *UserPreferenceAccount) GetAutoPositionEffect() *bool {
	if u == nil {
		return nil
	}
	return u.AutoPositionEffect
}
