// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Chalupa-Tech/go-schwab-api-individual/internal/utils"
)

type UserPreference struct {
	Accounts     []UserPreferenceAccount `json:"accounts,omitzero"`
	StreamerInfo []StreamerInfo          `json:"streamerInfo,omitzero"`
	Offers       []Offer                 `json:"offers,omitzero"`
}

func (u UserPreference) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserPreference) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UserPreference) GetAccounts() []UserPreferenceAccount {
	if u == nil {
		return nil
	}
	return u.Accounts
}

func (u *UserPreference) GetStreamerInfo() []StreamerInfo {
	if u == nil {
		return nil
	}
	return u.StreamerInfo
}

func (u *UserPreference) GetOffers() []Offer {
	if u == nil {
		return nil
	}
	return u.Offers
}
