// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UserDetailsType string

const (
	UserDetailsTypeAdvisorUser UserDetailsType = "ADVISOR_USER"
	UserDetailsTypeBrokerUser  UserDetailsType = "BROKER_USER"
	UserDetailsTypeClientUser  UserDetailsType = "CLIENT_USER"
	UserDetailsTypeSystemUser  UserDetailsType = "SYSTEM_USER"
	UserDetailsTypeUnknown     UserDetailsType = "UNKNOWN"
)

func (e UserDetailsType) ToPointer() *UserDetailsType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *UserDetailsType) IsExact() bool {
	if e != nil {
		switch *e {
		case "ADVISOR_USER", "BROKER_USER", "CLIENT_USER", "SYSTEM_USER", "UNKNOWN":
			return true
		}
	}
	return false
}

type UserDetails struct {
	CdDomainID     *string          `json:"cdDomainId,omitzero"`
	Login          *string          `json:"login,omitzero"`
	Type           *UserDetailsType `json:"type,omitzero"`
	UserID         *int64           `json:"userId,omitzero"`
	SystemUserName *string          `json:"systemUserName,omitzero"`
	FirstName      *string          `json:"firstName,omitzero"`
	LastName       *string          `json:"lastName,omitzero"`
	BrokerRepCode  *string          `json:"brokerRepCode,omitzero"`
}

func (u *UserDetails) GetCdDomainID() *string {
	if u == nil {
		return nil
	}
	return u.CdDomainID
}

func (u *UserDetails) GetLogin() *string {
	if u == nil {
		return nil
	}
	return u.Login
}

func (u *UserDetails) GetType() *UserDetailsType {
	if u == nil {
		return nil
	}
	return u.Type
}

func (u *UserDetails) GetUserID() *int64 {
	if u == nil {
		return nil
	}
	return u.UserID
}

func (u *UserDetails) GetSystemUserName() *string {
	if u == nil {
		return nil
	}
	return u.SystemUserName
}

func (u *UserDetails) GetFirstName() *string {
	if u == nil {
		return nil
	}
	return u.FirstName
}

func (u *UserDetails) GetLastName() *string {
	if u == nil {
		return nil
	}
	return u.LastName
}

func (u *UserDetails) GetBrokerRepCode() *string {
	if u == nil {
		return nil
	}
	return u.BrokerRepCode
}
