// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/Chalupa-Tech/go-schwab-api-individual/models/components"
)

// ErrorResponse - Error response for generic client error 400
type ErrorResponse struct {
	Errors   []components.Error      `json:"errors,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ErrorResponse{}

func (e *ErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
