// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"undefined/models/components"
)

// ServiceError - An error message indicating the validation problem with the request.
type ServiceError struct {
	Message  *string                 `json:"message,omitzero"`
	Errors   []string                `json:"errors,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ServiceError{}

func (e *ServiceError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
